type Ticket={request_id:string;expression_id:string;expression_key:string;placement_id:string;placement_key:string;source_asset_id:string;source_asset_key:string;media_type:string;source_locator:Record<string,unknown>;expires_at:string};
const SUPABASE_URL=Deno.env.get('SUPABASE_URL')!;const SERVICE_KEY=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;const MAX_BYTES=20_000_000;
function json(status:number,body:unknown){return new Response(JSON.stringify(body),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'}})}
async function rpc(name:string,body:unknown){const r=await fetch(`${SUPABASE_URL}/rest/v1/rpc/${name}`,{method:'POST',headers:{apikey:SERVICE_KEY,authorization:`Bearer ${SERVICE_KEY}`,'content-type':'application/json'},body:JSON.stringify(body)});const t=await r.text();if(!r.ok)throw new Error(`${name} ${r.status}: ${t.slice(0,500)}`);return t?JSON.parse(t):null}
async function sha256Hex(bytes:Uint8Array){const d=new Uint8Array(await crypto.subtle.digest('SHA-256',bytes));return Array.from(d,b=>b.toString(16).padStart(2,'0')).join('')}
const IA_MAP:Record<string,{asset:string;leaf:string}>={
  'dewy:plate:frontispiece':{asset:'dewy:loc:source-surface:0006',leaf:'n5'},
  'dewy:plate:page-9':{asset:'dewy:loc:source-surface:0013',leaf:'n12'},
  'dewy:plate:page-19':{asset:'dewy:loc:source-surface:0023',leaf:'n22'},
  'dewy:plate:page-29':{asset:'dewy:loc:source-surface:0033',leaf:'n32'},
  'dewy:plate:page-37':{asset:'dewy:loc:source-surface:0041',leaf:'n40'},
  'dewy:plate:page-47':{asset:'dewy:loc:source-surface:0051',leaf:'n50'},
  'dewy:plate:page-55':{asset:'dewy:loc:source-surface:0059',leaf:'n58'},
};
Deno.serve(async(req)=>{if(req.method!=='GET')return json(405,{error:'GET required'});try{const u=new URL(req.url);const requestId=(u.searchParams.get('request_id')??'').trim();const token=(u.searchParams.get('token')??'').trim();const rendition=(u.searchParams.get('rendition')??'').trim();if(!/^[0-9a-f-]{36}$/.test(requestId)||!/^[0-9a-f]{64}$/.test(token))return json(401,{error:'valid one-time request_id and token required'});const ticket=await rpc('wnph_resolve_publication_media_receipt_request_v1',{p_request_id:requestId,p_token:token}) as Ticket;
if(rendition!=='ia-w1600')return json(400,{error:'unsupported rendition'});const mapped=IA_MAP[ticket.placement_key];if(!mapped||ticket.source_asset_key!==mapped.asset)return json(403,{error:'IA w1600 rendition is not authorized for this governed placement/source pair'});
const fetchUri=`https://archive.org/download/wishfairydewydea00colv/page/${mapped.leaf}_w1600.jpg`;const receiptKey='publication-raster:ia-bookreader-w1600:v1';
const upstream=await fetch(fetchUri,{headers:{accept:'image/jpeg','user-agent':'WNPH-publication-media-receipt/5.0'},redirect:'follow'});if(!upstream.ok)return json(502,{error:`publication raster upstream ${upstream.status}`});const contentType=(upstream.headers.get('content-type')??'').split(';')[0].trim().toLowerCase();if(contentType!=='image/jpeg')return json(502,{error:`unexpected upstream content type ${contentType}`});const bytes=new Uint8Array(await upstream.arrayBuffer());if(!bytes.byteLength||bytes.byteLength>MAX_BYTES)return json(502,{error:`raster size ${bytes.byteLength} outside supported range`});const hash=await sha256Hex(bytes);const committed=await rpc('wnph_commit_publication_media_source_receipt_v2',{p_request_id:requestId,p_token:token,p_receipt_key:receiptKey,p_fetch_uri:fetchUri,p_media_type:contentType,p_byte_length:bytes.byteLength,p_sha256:hash,p_evidence:{worker:'wnph-publication-media-receipt',worker_version:5,fetch_method:'internet_archive_bookreader_same_surrogate_w1600',rendition_width_request_px:1600,same_surrogate_derivative:true,internet_archive_item:'wishfairydewydea00colv',internet_archive_leaf:mapped.leaf,arbitrary_url_input_allowed:false,historical_witness_count_delta:0,source_image_verification_claim:false}});return json(200,{contract_version:'wnph_publication_media_receipt_v2',expression_key:ticket.expression_key,placement_key:ticket.placement_key,source_asset_key:ticket.source_asset_key,receipt_key:receiptKey,fetch_uri:fetchUri,media_type:contentType,byte_length:bytes.byteLength,sha256:hash,receipt:committed});}catch(e){return json(403,{error:e instanceof Error?e.message:String(e)})}});