with package as (
 select id from wnph.publication_source_packages where canonical_key='virginia-house-wife:1824-functional-semantic-source:v1'
)
insert into wnph.publication_source_observations(source_asset_id,observation_key,observation_kind,ordinal,coordinate_unit,x,y,width,height,confidence,derivation_method,source_format,processor,external_locator,metadata)
select a.id,'virginia-house-wife:1824:oyster-soup:scan:0036:machine-pixel-corroboration:v1','layout_region',1,'pixel',0,0,1200,1886,0.98,'bounded_machine_pixel_corroboration_v1','image/jpeg',
jsonb_build_object('provider','WNPH bounded source inspection','engine','ocrad.js 0.0.1','mode','whole_page_machine_corroboration'),
jsonb_build_object('asset_key',a.asset_key,'scan_sequence',36,'printed_page',32,'iiif_uri','https://tile.loc.gov/image-services/iiif/service:rbc:rbc0001:2015:2015pennell17897:0036/full/1200,/0/default.jpg'),
jsonb_build_object('verification_role','machine_pixel_corroboration','human_visual_inspection',false,'source_image_verification_claim',false,'source_sha256','d623b28164276823305c4da495b3f445d0fe35f1eeeb291d4cdfebf3a18aadf1','source_byte_length',299509,
'comparison_source_key','textgrid:virginia-house-wife:1824','comparison_agreement',true,'agreement_scope','lexical_and_semantic_claim_support','typographic_exactness_human_adjudicated',false,
'stable_signals',jsonb_build_array('OYSTER SOUP','two quarts of oysters','three quarts of water','three onions','lean ham','reduced one half','one quart of fresh oysters','four spoonsful of flour','two gills of rich cream','yelks of six new laid eggs','thyme'))
from package p join wnph.publication_source_assets a on a.source_package_id=p.id and a.asset_key='virginia-house-wife:1824:source-surface:0036'
where not exists(select 1 from wnph.publication_source_observations o where o.source_asset_id=a.id and o.observation_key='virginia-house-wife:1824:oyster-soup:scan:0036:machine-pixel-corroboration:v1' and not exists(select 1 from wnph.publication_source_observations c where c.supersedes_observation_id=o.id));

do $$
declare
 v_package wnph.publication_source_packages%rowtype; v_case wnph.recovery_cases%rowtype; v_work wnph.historical_works%rowtype; v_surrogate wnph.surrogates%rowtype; v_loc_source wnph.evidence_sources%rowtype; v_textgrid_source wnph.evidence_sources%rowtype;
 v_soup_container uuid; v_block_id uuid; v_unit_id uuid; v_act_id uuid; v_asset_id uuid; v_locator jsonb;
begin
 if exists(select 1 from wnph.transmission_acts where canonical_key='virginia-house-wife:1824:transmission:oyster-soup:source-text-verification:v1') then return; end if;
 select * into strict v_package from wnph.publication_source_packages where canonical_key='virginia-house-wife:1824-functional-semantic-source:v1'; select * into strict v_case from wnph.recovery_cases where canonical_key='virginia-house-wife:functional-semantic-cookbook-recovery-1'; select * into strict v_work from wnph.historical_works where canonical_key='virginia-house-wife'; select * into strict v_surrogate from wnph.surrogates where canonical_key='virginia-house-wife:loc-digital-73217897'; select * into strict v_loc_source from wnph.evidence_sources where canonical_key='loc:item:73217897'; select * into strict v_textgrid_source from wnph.evidence_sources where canonical_key='textgrid:virginia-house-wife:1824';
 select id into strict v_soup_container from wnph.publication_source_blocks b where b.source_package_id=v_package.id and b.block_key='virginia-house-wife:1824:sequence:soups' and not exists(select 1 from wnph.publication_source_blocks c where c.supersedes_block_id=b.id);
 select id into strict v_asset_id from wnph.publication_source_assets where source_package_id=v_package.id and asset_key='virginia-house-wife:1824:source-surface:0036';
 v_locator:=jsonb_build_array(jsonb_build_object('asset_key','virginia-house-wife:1824:source-surface:0036','scan_sequence',36,'printed_page',32,'source_sha256','d623b28164276823305c4da495b3f445d0fe35f1eeeb291d4cdfebf3a18aadf1','source_byte_length',299509));
 v_block_id:=gen_random_uuid();
 insert into wnph.publication_source_blocks(id,source_package_id,block_key,parent_block_id,ordinal,block_type,semantic_role,text_content,properties,source_provenance,reading_state)
 values(v_block_id,v_package.id,'virginia-house-wife:1824:oyster-soup',v_soup_container,5,'instruction','oyster_soup_with_cream_egg_thickening',
$oyster$OYSTER SOUP.

Put on two quarts of oysters, with three quarts of water, three onions chopped up, two or three slices of lean ham, pepper and salt; boil it till reduced one half, strain it through a sieve, return the liquid into the pot, put in one quart of fresh oysters, boil it till they are sufficiently done, and thicken the soup with four spoonsful of flour, two gills of rich cream, and the yelks of six new laid eggs beaten well; boil it a few minutes after the thickening is put in. Take care that it does not curdle, and that the flour is not in lumps: serve it up with the last oysters that were put in. If the flavour of thyme be agreeable you may put in a little, but take care that it does not boil in it long enough to discolour the soup.$oyster$,
 jsonb_build_object('printed_pages',jsonb_build_array(32),'historical_unit_type','oyster_soup_with_cream_egg_thickening','modern_safety_assessed',false,'modern_normalization_applied',false,'human_visual_inspection',false,'typographic_exactness_human_adjudicated',false,'next_heading','BARLEY SOUP.','later_edition_wash_and_drain_opening_excluded',true),
 jsonb_build_object('text_authority','Library of Congress 1824 first-edition source surface is controlling; exact-1824 TextGrid comparison supplies the lexical reading','source_locators',v_locator,'verification_status','source_text_verified','source_verified',true,'controlling_witness','Library of Congress 1824 first edition','comparison_transcription_key','textgrid:virginia-house-wife:1824','comparison_transcription_is_authority',false,'machine_pixel_corroboration',true,'human_visual_inspection',false,'source_image_verification_claim',false,'typographic_exactness_human_adjudicated',false,'verification_scope','lexical_and_semantic_content_for_functional_semantic_recovery','derivation_method','exact_1824_comparison_transcription_corroborated_against_loc_pixels'),'verified');
 v_act_id:=gen_random_uuid();
 insert into wnph.transmission_acts(id,canonical_key,recovery_case_id,work_id,operation_type,purpose,method_note,epistemic_status,confidence,metadata)
 values(v_act_id,'virginia-house-wife:1824:transmission:oyster-soup:source-text-verification:v1',v_case.id,v_work.id,'source_text_verification','Verify OYSTER SOUP against the selected 1824 Library of Congress witness for functional-semantic recovery.',
 'LOC scan 36 is the controlling first-edition source surface for OYSTER SOUP; scan 37 begins BARLEY SOUP and therefore fixes the unit boundary. Exact-1824 TextGrid confirms the 1824 opening Put on two quarts of oysters, rather than the later-edition Wash and drain wording. No human visual or glyph-level adjudication is claimed.','system_recorded','high',
 jsonb_build_object('canonical_text_admission',true,'canonical_text_adjudication',false,'source_text_verified',true,'source_image_verified',false,'machine_pixel_corroboration',true,'human_visual_inspection',false,'page_image_is_controlling_witness',true,'comparison_transcription_key','textgrid:virginia-house-wife:1824','comparison_transcription_is_authority',false,'verification_scope','lexical_and_semantic_content_for_functional_semantic_recovery','typographic_exactness_human_adjudicated',false,'scan_locators',v_locator,'claim_promotion_target','verified_not_adjudicated','later_edition_wash_and_drain_opening_excluded',true));
 insert into wnph.transmission_act_objects(transmission_act_id,direction,object_role,surrogate_id,locator) values(v_act_id,'input','preferred_historical_source',v_surrogate.id,jsonb_build_object('lccn','73217897','scan_sequences',jsonb_build_array(36)));
 insert into wnph.transmission_act_objects(transmission_act_id,direction,object_role,publication_source_package_id,locator) values(v_act_id,'context','canonical_publication_source',v_package.id,'{}'); insert into wnph.transmission_act_objects(transmission_act_id,direction,object_role,evidence_source_id,locator) values(v_act_id,'input','comparison_transcription',v_textgrid_source.id,jsonb_build_object('status','comparison_only','edition_year',1824));
 insert into wnph.transmission_act_objects(transmission_act_id,direction,object_role,publication_source_asset_id,locator) values(v_act_id,'input','source_page_image',v_asset_id,jsonb_build_object('asset_key','virginia-house-wife:1824:source-surface:0036','scan_sequence',36,'printed_page',32,'source_sha256','d623b28164276823305c4da495b3f445d0fe35f1eeeb291d4cdfebf3a18aadf1','source_byte_length',299509,'human_visual_inspection',false));
 insert into wnph.transmission_act_objects(transmission_act_id,direction,object_role,publication_source_block_id,locator) values(v_act_id,'output','verified_source_text',v_block_id,jsonb_build_object('block_key','virginia-house-wife:1824:oyster-soup','reading_state','verified'));
 insert into wnph.transmission_act_evidence(transmission_act_id,source_id,support_role,confidence,note) values (v_act_id,v_loc_source.id,'supports','certain','LOC LCCN 73217897 scan 36 is the controlling 1824 source surface; scan 37 establishes the next BARLEY SOUP boundary.'),(v_act_id,v_textgrid_source.id,'supports','high','Exact-1824 TextGrid agrees with the LOC pixel reading and distinguishes the first-edition opening from later wording.');
 v_unit_id:=gen_random_uuid();
 insert into wnph.publication_semantic_units(id,expression_id,source_package_id,unit_key,parent_unit_id,ordinal,unit_type,source_title,semantic_status,confidence,derivation_method,properties,source_provenance)
 values(v_unit_id,v_package.expression_id,v_package.id,'virginia-house-wife:1824:semantic:oyster-soup',null,12,'oyster_soup_with_cream_egg_thickening','OYSTER SOUP.','verified',0.99,'source_text_verified_semantic_extraction_v1',jsonb_build_object('printed_pages',jsonb_build_array(32),'primary_function','reduce an oyster-ham broth, add a second oyster batch, and thicken with flour, cream, and egg yolks','historical_container','unheaded soup instruction sequence','modern_safety_assessed',false,'modern_normalization_applied',false,'human_visual_inspection',false,'atlas_execution_requires_downstream_normalization',true),
 jsonb_build_object('source_verified',true,'source_block_id',v_block_id,'verification_status','source_text_verified','controlling_witness','LOC 1824','machine_pixel_corroboration',true,'human_visual_inspection',false,'typographic_exactness_human_adjudicated',false,'comparison_transcription_key','textgrid:virginia-house-wife:1824'));
 insert into wnph.publication_semantic_claims(semantic_unit_id,source_block_id,claim_key,ordinal,claim_kind,subject_key,predicate,object_text,quantity_value,quantity_unit,quantity_text,temporal_text,condition_text,claim_status,confidence,derivation_method,properties,source_provenance)
 select v_unit_id,v_block_id,x.claim_key,x.ordinal,x.claim_kind,x.subject_key,x.predicate,x.object_text,x.quantity_value,x.quantity_unit,x.quantity_text,x.temporal_text,x.condition_text,'verified',x.confidence,'source_text_verified_semantic_extraction_v1',x.properties,
 jsonb_build_object('source_pages',x.source_pages,'source_verified',true,'verification_status','source_text_verified','verified_source_block_id',v_block_id,'controlling_witness','LOC 1824','comparison_transcription','TextGrid exact 1824','machine_pixel_corroboration',true,'human_visual_inspection',false,'typographic_exactness_human_adjudicated',false,'modern_use_requires_downstream_safety_review',x.safety_review)
 from (values
 (1,'initial-oysters','ingredient_quantity','oyster_soup','contains','oysters',2::numeric,'quart','two quarts',null::text,'initial broth batch',0.99,jsonb_build_object('batch',1),jsonb_build_array(32),true),
 (2,'water','ingredient_quantity','oyster_soup','contains','water',3::numeric,'quart','three quarts',null,null,0.99,jsonb_build_object(),jsonb_build_array(32),false),
 (3,'onions','ingredient_quantity','oyster_soup','contains','onions chopped up',3::numeric,'count','three onions',null,null,0.99,jsonb_build_object(),jsonb_build_array(32),false),
 (4,'ham','ingredient_quantity','oyster_soup','contains','lean ham slices',2::numeric,'slice_minimum','two or three slices',null,null,0.99,jsonb_build_object('maximum_value',3),jsonb_build_array(32),false),
 (5,'seasoning','ingredient','oyster_soup','contains','pepper and salt',null,null,null,null,null,0.99,jsonb_build_object(),jsonb_build_array(32),false),
 (6,'reduce-half','historical_cooking_endpoint','oyster_broth','boil_until','reduced one half',null,null,null,'initial broth stage',null,0.99,jsonb_build_object('modern_safety_assessed',false),jsonb_build_array(32),true),
 (7,'strain','process_stage','oyster_broth','strain_through','sieve',null,null,null,'after reduction',null,0.99,jsonb_build_object(),jsonb_build_array(32),false),
 (8,'return-liquid','process_stage','strained_broth','return_to','pot',null,null,null,'after straining',null,0.99,jsonb_build_object(),jsonb_build_array(32),false),
 (9,'fresh-oysters','ingredient_quantity','oyster_soup','add','fresh oysters',1::numeric,'quart','one quart','after broth is strained',null,0.99,jsonb_build_object('batch',2),jsonb_build_array(32),true),
 (10,'second-oyster-endpoint','historical_cooking_endpoint','fresh_oysters','boil_until','sufficiently done',null,null,null,'second oyster batch','historical qualitative endpoint; modern safety not assessed',0.99,jsonb_build_object('modern_safety_assessed',false),jsonb_build_array(32),true),
 (11,'flour','thickening_ingredient','thickening','contains','flour',4::numeric,'spoonful','four spoonsful',null,null,0.99,jsonb_build_object(),jsonb_build_array(32),false),
 (12,'cream','thickening_ingredient','thickening','contains','rich cream',2::numeric,'gill','two gills',null,null,0.99,jsonb_build_object(),jsonb_build_array(32),false),
 (13,'egg-yolks','thickening_ingredient','thickening','contains','well-beaten yolks of new laid eggs',6::numeric,'egg_yolk','yelks of six new laid eggs',null,null,0.99,jsonb_build_object(),jsonb_build_array(32),true),
 (14,'final-boil','historical_cooking_duration','thickened_oyster_soup','boil','a few minutes',null,'minute_unspecified','a few minutes','after thickening is added',null,0.99,jsonb_build_object('modern_safety_assessed',false),jsonb_build_array(32),true),
 (15,'avoid-curdle','thickening_constraint','oyster_soup','avoid','curdling',null,null,null,'during final thickening',null,0.99,jsonb_build_object(),jsonb_build_array(32),false),
 (16,'avoid-flour-lumps','thickening_constraint','oyster_soup','avoid','flour lumps',null,null,null,'during final thickening',null,0.99,jsonb_build_object(),jsonb_build_array(32),false),
 (17,'serve-second-oysters','service','oyster_soup','serve_with','last oysters that were put in',null,null,null,'at service',null,0.99,jsonb_build_object(),jsonb_build_array(32),false),
 (18,'thyme-option','flavour_option','oyster_soup','optionally_add','a little thyme',null,null,null,null,'if agreeable',0.99,jsonb_build_object('optional',true),jsonb_build_array(32),false),
 (19,'thyme-colour-rule','historical_appearance_rule','thyme','limit_boiling','do not boil long enough to discolour soup',null,null,null,'if thyme is used',null,0.99,jsonb_build_object('author_judgment',true),jsonb_build_array(32),false)
 ) x(ordinal,claim_key,claim_kind,subject_key,predicate,object_text,quantity_value,quantity_unit,quantity_text,temporal_text,condition_text,confidence,properties,source_pages,safety_review);
end $$;