with package as (
 select id from wnph.publication_source_packages where canonical_key='virginia-house-wife:1824-functional-semantic-source:v1'
), scans(scan_sequence,printed_page,image_height,source_sha256,source_byte_length,signals) as (
 values
 (35,31,1938,'2926faa0f3e30b0691d6e96dc4ad6943c643ebb50947d8f4bcfad1a27fea763b',300251,jsonb_build_array('VEAL SOUP','three quarts of water','three onions','black pepper','two of salt','lean ham','two hours','shin of veal','two hours longer','gill of good cream','two table-spoonsful of flour','yelks of two eggs')),
 (36,32,1886,'d623b28164276823305c4da495b3f445d0fe35f1eeeb291d4cdfebf3a18aadf1',299509,jsonb_build_array('boiled two or three minutes','cream','eggs','curdle','dozen ripe tomatas','hot water','flour only','shin or knuckle','OYSTER SOUP'))
)
insert into wnph.publication_source_observations(source_asset_id,observation_key,observation_kind,ordinal,coordinate_unit,x,y,width,height,confidence,derivation_method,source_format,processor,external_locator,metadata)
select a.id,format('virginia-house-wife:1824:veal-soup:scan:%s:machine-pixel-corroboration:v1',lpad(s.scan_sequence::text,4,'0')),'layout_region',1,'pixel',0,0,1200,s.image_height,0.98,
'bounded_machine_pixel_corroboration_v1','image/jpeg',jsonb_build_object('provider','WNPH bounded source inspection','engine','ocrad.js 0.0.1','mode','whole_page_machine_corroboration'),
jsonb_build_object('asset_key',a.asset_key,'scan_sequence',s.scan_sequence,'printed_page',s.printed_page,'iiif_uri',format('https://tile.loc.gov/image-services/iiif/service:rbc:rbc0001:2015:2015pennell17897:%s/full/1200,/0/default.jpg',lpad(s.scan_sequence::text,4,'0'))),
jsonb_build_object('verification_role','machine_pixel_corroboration','human_visual_inspection',false,'source_image_verification_claim',false,'source_sha256',s.source_sha256,'source_byte_length',s.source_byte_length,'comparison_source_key','textgrid:virginia-house-wife:1824','comparison_agreement',true,'agreement_scope','lexical_and_semantic_claim_support','typographic_exactness_human_adjudicated',false,'stable_signals',s.signals)
from scans s join package p on true join wnph.publication_source_assets a on a.source_package_id=p.id and a.asset_key=format('virginia-house-wife:1824:source-surface:%s',lpad(s.scan_sequence::text,4,'0'))
where not exists(select 1 from wnph.publication_source_observations o where o.source_asset_id=a.id and o.observation_key=format('virginia-house-wife:1824:veal-soup:scan:%s:machine-pixel-corroboration:v1',lpad(s.scan_sequence::text,4,'0')) and not exists(select 1 from wnph.publication_source_observations c where c.supersedes_observation_id=o.id));

do $$
declare
 v_package wnph.publication_source_packages%rowtype; v_case wnph.recovery_cases%rowtype; v_work wnph.historical_works%rowtype; v_surrogate wnph.surrogates%rowtype; v_loc_source wnph.evidence_sources%rowtype; v_textgrid_source wnph.evidence_sources%rowtype;
 v_soup_container uuid; v_block_id uuid; v_unit_id uuid; v_act_id uuid; v_locators jsonb; s record;
begin
 if exists(select 1 from wnph.transmission_acts where canonical_key='virginia-house-wife:1824:transmission:veal-soup:source-text-verification:v1') then return; end if;
 select * into strict v_package from wnph.publication_source_packages where canonical_key='virginia-house-wife:1824-functional-semantic-source:v1';
 select * into strict v_case from wnph.recovery_cases where canonical_key='virginia-house-wife:functional-semantic-cookbook-recovery-1';
 select * into strict v_work from wnph.historical_works where canonical_key='virginia-house-wife';
 select * into strict v_surrogate from wnph.surrogates where canonical_key='virginia-house-wife:loc-digital-73217897';
 select * into strict v_loc_source from wnph.evidence_sources where canonical_key='loc:item:73217897'; select * into strict v_textgrid_source from wnph.evidence_sources where canonical_key='textgrid:virginia-house-wife:1824';
 select id into strict v_soup_container from wnph.publication_source_blocks b where b.source_package_id=v_package.id and b.block_key='virginia-house-wife:1824:sequence:soups' and not exists(select 1 from wnph.publication_source_blocks c where c.supersedes_block_id=b.id);
 select jsonb_agg(jsonb_build_object('asset_key',a.asset_key,'scan_sequence',m.scan_sequence,'printed_page',m.printed_page,'source_sha256',m.sha256,'source_byte_length',m.byte_length) order by m.scan_sequence) into v_locators
 from (values (35,31,'2926faa0f3e30b0691d6e96dc4ad6943c643ebb50947d8f4bcfad1a27fea763b',300251),(36,32,'d623b28164276823305c4da495b3f445d0fe35f1eeeb291d4cdfebf3a18aadf1',299509)) m(scan_sequence,printed_page,sha256,byte_length)
 join wnph.publication_source_assets a on a.source_package_id=v_package.id and a.asset_key=format('virginia-house-wife:1824:source-surface:%s',lpad(m.scan_sequence::text,4,'0'));
 v_block_id:=gen_random_uuid();
 insert into wnph.publication_source_blocks(id,source_package_id,block_key,parent_block_id,ordinal,block_type,semantic_role,text_content,properties,source_provenance,reading_state)
 values(v_block_id,v_package.id,'virginia-house-wife:1824:veal-soup',v_soup_container,4,'instruction','soup_recipe_with_thickening_variant',
$veal$VEAL SOUP.

Put into a pot three quarts of water, three onions cut small, one spoonful of black pepper pounded, and two of salt, with two or three slices of lean ham; let it boil steadily two hours; skim it occasionally, then put into it a shin of veal, let it boil two hours longer; take out the slices of ham, and skim off the grease if any should rise, take a gill of good cream, mix with it two table-spoonsful of flour very nicely, and the yelks of two eggs beaten well, strain this mixture, and add some chopped parsley; pour some soup on by degrees, stir it well, and pour it into the pot continuing to stir until it has boiled two or three minutes to take off the raw taste of the eggs. If the cream be not perfectly sweet, and the eggs quite new, the thickening will curdle in the soup. For a change, you may put a dozen ripe tomatas in, first taking off their skins, by letting them stand a few minutes in hot water, when they may be easily peeled. When made in this way, you must thicken it with the flour only. Any part of the veal may be used, but the shin or knuckle is the nicest.$veal$,
 jsonb_build_object('printed_pages',jsonb_build_array(31,32),'historical_unit_type','soup_recipe_with_thickening_variant','modern_safety_assessed',false,'modern_normalization_applied',false,'human_visual_inspection',false,'typographic_exactness_human_adjudicated',false,'next_heading','OYSTER SOUP.','variant_count',1),
 jsonb_build_object('text_authority','Library of Congress 1824 first-edition source surfaces are controlling; exact-1824 TextGrid comparison supplies the lexical reading','source_locators',v_locators,'verification_status','source_text_verified','source_verified',true,'controlling_witness','Library of Congress 1824 first edition','comparison_transcription_key','textgrid:virginia-house-wife:1824','comparison_transcription_is_authority',false,'machine_pixel_corroboration',true,'human_visual_inspection',false,'source_image_verification_claim',false,'typographic_exactness_human_adjudicated',false,'verification_scope','lexical_and_semantic_content_for_functional_semantic_recovery','derivation_method','exact_1824_comparison_transcription_corroborated_against_loc_pixels'),'verified');
 v_act_id:=gen_random_uuid();
 insert into wnph.transmission_acts(id,canonical_key,recovery_case_id,work_id,operation_type,purpose,method_note,epistemic_status,confidence,metadata)
 values(v_act_id,'virginia-house-wife:1824:transmission:veal-soup:source-text-verification:v1',v_case.id,v_work.id,'source_text_verification','Verify VEAL SOUP against the selected 1824 Library of Congress witness for functional-semantic recovery.',
 'LOC scans 35–36 bound VEAL SOUP through OYSTER SOUP. They independently recover the staged two-hour plus two-hour cooking process, cream/flour/egg thickening, short final boil, and tomato variant. Exact-1824 TextGrid supplies comparison wording. No human visual or glyph-level adjudication is claimed.','system_recorded','high',
 jsonb_build_object('canonical_text_admission',true,'canonical_text_adjudication',false,'source_text_verified',true,'source_image_verified',false,'machine_pixel_corroboration',true,'human_visual_inspection',false,'page_image_is_controlling_witness',true,'comparison_transcription_key','textgrid:virginia-house-wife:1824','comparison_transcription_is_authority',false,'verification_scope','lexical_and_semantic_content_for_functional_semantic_recovery','typographic_exactness_human_adjudicated',false,'scan_locators',v_locators,'claim_promotion_target','verified_not_adjudicated'));
 insert into wnph.transmission_act_objects(transmission_act_id,direction,object_role,surrogate_id,locator) values(v_act_id,'input','preferred_historical_source',v_surrogate.id,jsonb_build_object('lccn','73217897','scan_sequences',jsonb_build_array(35,36)));
 insert into wnph.transmission_act_objects(transmission_act_id,direction,object_role,publication_source_package_id,locator) values(v_act_id,'context','canonical_publication_source',v_package.id,'{}');
 insert into wnph.transmission_act_objects(transmission_act_id,direction,object_role,evidence_source_id,locator) values(v_act_id,'input','comparison_transcription',v_textgrid_source.id,jsonb_build_object('status','comparison_only','edition_year',1824));
 for s in select a.id,a.asset_key,m.scan_sequence,m.printed_page,m.sha256,m.byte_length from (values (35,31,'2926faa0f3e30b0691d6e96dc4ad6943c643ebb50947d8f4bcfad1a27fea763b',300251),(36,32,'d623b28164276823305c4da495b3f445d0fe35f1eeeb291d4cdfebf3a18aadf1',299509)) m(scan_sequence,printed_page,sha256,byte_length)
 join wnph.publication_source_assets a on a.source_package_id=v_package.id and a.asset_key=format('virginia-house-wife:1824:source-surface:%s',lpad(m.scan_sequence::text,4,'0')) loop insert into wnph.transmission_act_objects(transmission_act_id,direction,object_role,publication_source_asset_id,locator) values(v_act_id,'input','source_page_image',s.id,jsonb_build_object('asset_key',s.asset_key,'scan_sequence',s.scan_sequence,'printed_page',s.printed_page,'source_sha256',s.sha256,'source_byte_length',s.byte_length,'human_visual_inspection',false)); end loop;
 insert into wnph.transmission_act_objects(transmission_act_id,direction,object_role,publication_source_block_id,locator) values(v_act_id,'output','verified_source_text',v_block_id,jsonb_build_object('block_key','virginia-house-wife:1824:veal-soup','reading_state','verified'));
 insert into wnph.transmission_act_evidence(transmission_act_id,source_id,support_role,confidence,note) values (v_act_id,v_loc_source.id,'supports','certain','LOC LCCN 73217897 scans 35–36 are the controlling 1824 source surfaces.'),(v_act_id,v_textgrid_source.id,'supports','high','Exact-1824 TextGrid agrees with the LOC pixel reading and supplies comparison wording only.');
 v_unit_id:=gen_random_uuid();
 insert into wnph.publication_semantic_units(id,expression_id,source_package_id,unit_key,parent_unit_id,ordinal,unit_type,source_title,semantic_status,confidence,derivation_method,properties,source_provenance)
 values(v_unit_id,v_package.expression_id,v_package.id,'virginia-house-wife:1824:semantic:veal-soup',null,11,'soup_recipe_with_thickening_variant','VEAL SOUP.','verified',0.99,'source_text_verified_semantic_extraction_v1',
 jsonb_build_object('printed_pages',jsonb_build_array(31,32),'primary_function','make a veal soup with ham base and tempered cream-flour-egg thickening, with an optional tomato/flour-only variant','historical_container','unheaded soup instruction sequence','modern_safety_assessed',false,'modern_normalization_applied',false,'human_visual_inspection',false,'atlas_execution_requires_downstream_normalization',true,'variant_count',1),
 jsonb_build_object('source_verified',true,'source_block_id',v_block_id,'verification_status','source_text_verified','controlling_witness','LOC 1824','machine_pixel_corroboration',true,'human_visual_inspection',false,'typographic_exactness_human_adjudicated',false,'comparison_transcription_key','textgrid:virginia-house-wife:1824'));
 insert into wnph.publication_semantic_claims(semantic_unit_id,source_block_id,claim_key,ordinal,claim_kind,subject_key,predicate,object_text,quantity_value,quantity_unit,quantity_text,temporal_text,condition_text,claim_status,confidence,derivation_method,properties,source_provenance)
 select v_unit_id,v_block_id,x.claim_key,x.ordinal,x.claim_kind,x.subject_key,x.predicate,x.object_text,x.quantity_value,x.quantity_unit,x.quantity_text,x.temporal_text,x.condition_text,'verified',x.confidence,'source_text_verified_semantic_extraction_v1',x.properties,
 jsonb_build_object('source_pages',x.source_pages,'source_verified',true,'verification_status','source_text_verified','verified_source_block_id',v_block_id,'controlling_witness','LOC 1824','comparison_transcription','TextGrid exact 1824','machine_pixel_corroboration',true,'human_visual_inspection',false,'typographic_exactness_human_adjudicated',false,'modern_use_requires_downstream_safety_review',x.safety_review)
 from (values
 (1,'water','ingredient_quantity','veal_soup','contains','water',3::numeric,'quart','three quarts',null::text,null::text,0.99,jsonb_build_object(),jsonb_build_array(31),false),
 (2,'onions','ingredient_quantity','veal_soup','contains','onions cut small',3::numeric,'count','three onions',null,null,0.99,jsonb_build_object(),jsonb_build_array(31),false),
 (3,'pepper','ingredient_quantity','veal_soup','contains','pounded black pepper',1::numeric,'spoonful','one spoonful',null,null,0.99,jsonb_build_object(),jsonb_build_array(31),false),
 (4,'salt','ingredient_quantity','veal_soup','contains','salt',2::numeric,'spoonful','two spoonfuls',null,null,0.99,jsonb_build_object(),jsonb_build_array(31),false),
 (5,'ham','ingredient_quantity','veal_soup','contains','lean ham slices',2::numeric,'slice_minimum','two or three slices',null,null,0.99,jsonb_build_object('maximum_value',3),jsonb_build_array(31),false),
 (6,'base-boil','historical_cooking_duration','soup_base','boil','steadily',2::numeric,'hour','two hours','before veal addition',null,0.99,jsonb_build_object('modern_safety_assessed',false),jsonb_build_array(31),true),
 (7,'skim-base','cooking_maintenance','soup_base','skim','occasionally',null,null,null,'during first boil',null,0.99,jsonb_build_object(),jsonb_build_array(31),false),
 (8,'veal-cut','ingredient_selection','veal','add','shin of veal',null,null,null,'after first two hours',null,0.99,jsonb_build_object(),jsonb_build_array(31),false),
 (9,'veal-boil','historical_cooking_duration','veal_soup','boil','two hours longer',2::numeric,'hour','two hours longer','after veal addition',null,0.99,jsonb_build_object('modern_safety_assessed',false),jsonb_build_array(31),true),
 (10,'remove-ham','finishing','ham','remove','slices of ham',null,null,null,'after veal cooking',null,0.99,jsonb_build_object(),jsonb_build_array(31),false),
 (11,'skim-grease','finishing','veal_soup','skim','grease if it rises',null,null,null,'after veal cooking',null,0.99,jsonb_build_object(),jsonb_build_array(31),false),
 (12,'cream','thickening_ingredient','thickening','contains','good cream',1::numeric,'gill','one gill',null,null,0.99,jsonb_build_object(),jsonb_build_array(31),false),
 (13,'flour','thickening_ingredient','thickening','contains','flour',2::numeric,'tablespoon','two table-spoonsful',null,null,0.99,jsonb_build_object(),jsonb_build_array(31),false),
 (14,'egg-yolks','thickening_ingredient','thickening','contains','well-beaten egg yolks',2::numeric,'egg_yolk','yelks of two eggs',null,null,0.99,jsonb_build_object(),jsonb_build_array(31),true),
 (15,'strain-thickening','thickening_process','thickening','strain','cream-flour-egg mixture; add chopped parsley',null,null,null,'before tempering',null,0.99,jsonb_build_object(),jsonb_build_array(31),false),
 (16,'temper-thickening','thickening_process','thickening','temper_with','soup added by degrees while stirring, then return to pot',null,null,null,'before final boil',null,0.99,jsonb_build_object(),jsonb_build_array(31,32),false),
 (17,'final-boil','historical_cooking_duration','thickened_soup','boil','while continuing to stir',2::numeric,'minute_minimum','two or three minutes','after thickening added','Randolph says this removes raw taste of eggs',0.99,jsonb_build_object('maximum_value',3,'modern_safety_assessed',false),jsonb_build_array(32),true),
 (18,'curdle-condition','historical_kitchen_chemistry','thickening','may_curdle_if','cream not perfectly sweet or eggs not quite new',null,null,null,null,null,0.98,jsonb_build_object('modern_validity_assessed',false),jsonb_build_array(32),false),
 (19,'tomato-variant','recipe_variant','veal_soup','optionally_add','ripe tomatas',12::numeric,'count','a dozen ripe tomatas',null,'for a change',0.99,jsonb_build_object('variant_key','tomato'),jsonb_build_array(32),false),
 (20,'tomato-peel','variant_preparation','tomatas','peel_by','stand a few minutes in hot water',null,null,null,'before adding','tomato variant',0.99,jsonb_build_object('variant_key','tomato'),jsonb_build_array(32),false),
 (21,'tomato-thickener-change','variant_rule','tomato_veal_soup','thicken_with','flour only',null,null,null,'thickening stage','tomato variant',0.99,jsonb_build_object('variant_key','tomato','omits',jsonb_build_array('cream','egg_yolks')),jsonb_build_array(32),false),
 (22,'veal-cut-option','ingredient_option','veal','may_use','any part; shin or knuckle preferred',null,null,null,null,null,0.99,jsonb_build_object('preferred',jsonb_build_array('shin','knuckle')),jsonb_build_array(32),false)
 ) x(ordinal,claim_key,claim_kind,subject_key,predicate,object_text,quantity_value,quantity_unit,quantity_text,temporal_text,condition_text,confidence,properties,source_pages,safety_review);
end $$;