do $$
declare
  v_case uuid; v_work uuid; v_pkg uuid; v_parent uuid; v_asset uuid; v_surrogate uuid;
  v_commons uuid; v_wikisource uuid; v_catalog uuid; v_agent uuid; v_ws_obs uuid; v_visual_obs uuid;
  v_prop_subtitle uuid; v_prop_addition uuid; v_prop_date uuid; v_prop_imprint uuid; v_act uuid; v_block uuid;
begin
  select c.id,c.work_id into strict v_case,v_work from wnph.recovery_cases c where c.canonical_key='proper-new-booke-of-cookery:foundational-cookbook-recovery-1';
  select p.id into strict v_pkg from wnph.publication_source_packages p where p.canonical_key='proper-new-booke-of-cookery:1575-canonical-publication-source:v1' and not exists(select 1 from wnph.publication_source_packages n where n.supersedes_package_id=p.id);
  select b.id into strict v_parent from wnph.publication_source_blocks b where b.source_package_id=v_pkg and b.block_key='proper-new-booke:title-page:reading-stream' and not exists(select 1 from wnph.publication_source_blocks n where n.supersedes_block_id=b.id);
  select a.id into strict v_asset from wnph.publication_source_assets a where a.source_package_id=v_pkg and a.asset_key='proper-new-booke:1575:source-surface:0001' and not exists(select 1 from wnph.publication_source_assets n where n.supersedes_asset_id=a.id);
  select s.id into strict v_surrogate from wnph.surrogates s where s.canonical_key='proper-new-booke-of-cookery:commons-ia-1575';
  select id into strict v_commons from wnph.evidence_sources where canonical_key='wikimedia-commons:proper-new-booke-cookery-1575';
  select id into strict v_wikisource from wnph.evidence_sources where canonical_key='wikisource:proper-new-booke-of-cookery-1575';
  select id into strict v_catalog from wnph.evidence_sources where canonical_key='heidelberg:1055289360';
  select a.id into strict v_agent from wnph.transmission_agents a where a.canonical_key='wnph:recovery-process' and not exists(select 1 from wnph.transmission_agents n where n.supersedes_agent_id=a.id);

  insert into wnph.publication_source_observations(source_asset_id,observation_key,observation_kind,ordinal,text_candidate,coordinate_unit,confidence,derivation_method,source_format,processor,external_locator,metadata)
  values(v_asset,'proper-new-booke:1575:page1:wikisource:remaining-title-page-candidate','region',3,E'Declaring what maner\nof meates be best in season for\nal times of the yeere, and how\nthey ought to be dressed, &\nserued at the Table, both\nfor fleshe dayes and\nfish daies.\n\nwith a new addition,\nvery necessary for al\nthem that delight\nin Cookery.\n\n1575.\n\nImprinted at London in Fleet\nstreete, by William Dow\nfor Abraham Veale.','surface',0.90,'external_transcription_alignment','wikisource_proofreadpage',jsonb_build_object('provider','Wikisource','engine','ProofreadPage'),jsonb_build_object('scan_page',1,'url','https://en.wikisource.org/wiki/Page:A_Proper_New_Booke_of_Cookery_(1575).djvu/1'),jsonb_build_object('status','proofread_not_validated','canonical_authority',false,'known_conflict',jsonb_build_object('candidate','William Dow','source_image_reading','William How'))) returning id into v_ws_obs;

  insert into wnph.publication_source_observations(source_asset_id,observation_key,observation_kind,ordinal,text_candidate,coordinate_unit,confidence,derivation_method,source_format,processor,external_locator,metadata)
  values(v_asset,'proper-new-booke:1575:page1:visual:remaining-title-page-reading','region',4,E'Declaring what maner\nof meates be best in season for\nal times of the yeere, and how\nthey ought to be dressed, &\nserued at the Table, both\nfor fleshe dayes and\nfish daies.\n\nwith a new addition,\nvery necessary for al\nthem that delight\nin Cookery.\n\n1575.\n\nImprinted at London in Fleet\nstreete, by William How\nfor Abraham Veale.','surface',0.98,'direct_visual_inspection_of_source_page_image','commons_page_image_render',jsonb_build_object('provider','OpenAI','engine','GPT-5.6 Sol visual inspection'),jsonb_build_object('scan_page',1,'asset_key','proper-new-booke:1575:source-surface:0001'),jsonb_build_object('canonical_authority',false,'lineation_preserved',true,'wikisource_conflict_resolved_from_image',jsonb_build_object('wikisource','William Dow','image','William How'))) returning id into v_visual_obs;

  insert into wnph.publication_source_reconstruction_proposals(source_package_id,proposal_key,target_parent_block_id,proposed_block_key,proposed_ordinal,proposed_block_type,proposed_semantic_role,proposed_text_content,proposed_reading_state,source_observation_ids,confidence,disposition,review_reasons,proposed_properties,proposed_source_provenance,algorithm)
  values(v_pkg,'proper-new-booke:1575:reconstruction:title-subtitle:v1',v_parent,'proper-new-booke:title-page:subtitle',2,'paragraph','title_scope_statement','Declaring what maner of meates be best in season for al times of the yeere, and how they ought to be dressed, & serued at the Table, both for fleshe dayes and fish daies.','usable',array[v_ws_obs,v_visual_obs],0.98,'review',jsonb_build_array('canonical source-image verification required before admission'),jsonb_build_object('scan_page',1),jsonb_build_object('text_authority','direct_source_image_with_comparison_transcription','derivation_method','direct_visual_reading_with_comparison_alignment','source_locators',jsonb_build_array(jsonb_build_object('scan_page',1,'asset_key','proper-new-booke:1575:source-surface:0001'))),jsonb_build_object('engine','wnph_visual_reconstruction_review','version','1')) returning id into v_prop_subtitle;
  insert into wnph.publication_source_reconstruction_proposals(source_package_id,proposal_key,target_parent_block_id,proposed_block_key,proposed_ordinal,proposed_block_type,proposed_semantic_role,proposed_text_content,proposed_reading_state,source_observation_ids,confidence,disposition,review_reasons,proposed_properties,proposed_source_provenance,algorithm)
  values(v_pkg,'proper-new-booke:1575:reconstruction:title-addition:v1',v_parent,'proper-new-booke:title-page:addition-notice',3,'paragraph','edition_addition_notice','with a new addition, very necessary for al them that delight in Cookery.','usable',array[v_ws_obs,v_visual_obs],0.98,'review',jsonb_build_array('canonical source-image verification required before admission'),jsonb_build_object('scan_page',1),jsonb_build_object('text_authority','direct_source_image_with_comparison_transcription','derivation_method','direct_visual_reading_with_comparison_alignment','source_locators',jsonb_build_array(jsonb_build_object('scan_page',1,'asset_key','proper-new-booke:1575:source-surface:0001'))),jsonb_build_object('engine','wnph_visual_reconstruction_review','version','1')) returning id into v_prop_addition;
  insert into wnph.publication_source_reconstruction_proposals(source_package_id,proposal_key,target_parent_block_id,proposed_block_key,proposed_ordinal,proposed_block_type,proposed_semantic_role,proposed_text_content,proposed_reading_state,source_observation_ids,confidence,disposition,review_reasons,proposed_properties,proposed_source_provenance,algorithm)
  values(v_pkg,'proper-new-booke:1575:reconstruction:title-date:v1',v_parent,'proper-new-booke:title-page:date',4,'paragraph','publication_date_as_printed','1575.','usable',array[v_ws_obs,v_visual_obs],1.0,'review',jsonb_build_array('canonical source-image verification required before admission'),jsonb_build_object('scan_page',1),jsonb_build_object('text_authority','direct_source_image','derivation_method','direct_visual_reading','source_locators',jsonb_build_array(jsonb_build_object('scan_page',1,'asset_key','proper-new-booke:1575:source-surface:0001'))),jsonb_build_object('engine','wnph_visual_reconstruction_review','version','1')) returning id into v_prop_date;
  insert into wnph.publication_source_reconstruction_proposals(source_package_id,proposal_key,target_parent_block_id,proposed_block_key,proposed_ordinal,proposed_block_type,proposed_semantic_role,proposed_text_content,proposed_reading_state,source_observation_ids,confidence,disposition,review_reasons,proposed_properties,proposed_source_provenance,algorithm)
  values(v_pkg,'proper-new-booke:1575:reconstruction:title-imprint:v1',v_parent,'proper-new-booke:title-page:imprint',5,'paragraph','imprint_as_printed','Imprinted at London in Fleet streete, by William How for Abraham Veale.','usable',array[v_ws_obs,v_visual_obs],0.99,'review',jsonb_build_array('Wikisource reads William Dow; governed source image and independent catalog read William How','canonical source-image verification required before admission'),jsonb_build_object('scan_page',1,'resolved_reading','William How'),jsonb_build_object('text_authority','direct_source_image','derivation_method','direct_visual_reading_with_catalog_corroboration','source_locators',jsonb_build_array(jsonb_build_object('scan_page',1,'asset_key','proper-new-booke:1575:source-surface:0001')),'comparison_conflict','Wikisource: William Dow','catalog_support','Heidelberg STC 3367: William How for Abraham Veale'),jsonb_build_object('engine','wnph_visual_reconstruction_review','version','1')) returning id into v_prop_imprint;

  insert into wnph.transmission_acts(canonical_key,recovery_case_id,work_id,operation_type,purpose,method_note,epistemic_status,confidence,metadata)
  values('proper-new-booke:1575:transmission:title-page-completion:v1',v_case,v_work,'verified_transcription','Complete the source-image-verified semantic reading of the 1575 title page.','The remaining title-page text was read directly from scan page 1. Long-s and r-shaped typographic variants are represented with ordinary reading characters while historical spelling is retained. Lineation is preserved in observation evidence. The Wikisource proofread candidate is comparison only; its imprint reading William Dow is rejected because the governed source image reads William How, independently corroborated by the catalog record.','system_recorded','certain',jsonb_build_object('canonical_text_admission',true,'source_image_verified',true,'scan_page_scope',jsonb_build_array(1),'canonical_blocks_admitted',4,'normalization_performed',false,'typographic_reading_normalization','long-s/r-glyph forms to ordinary reading characters','wikisource_is_authority',false,'resolved_conflict',jsonb_build_object('candidate','William Dow','admitted','William How'))) returning id into v_act;

  insert into wnph.transmission_act_agents(transmission_act_id,agent_id,agent_role) values(v_act,v_agent,'source_image_transcription_and_verification');
  insert into wnph.transmission_act_objects(transmission_act_id,direction,object_role,surrogate_id,locator) values(v_act,'input','preferred_historical_source',v_surrogate,jsonb_build_object('scan_page',1));
  insert into wnph.transmission_act_objects(transmission_act_id,direction,object_role,publication_source_asset_id,locator) values(v_act,'input','source_page_image',v_asset,jsonb_build_object('scan_page',1,'asset_key','proper-new-booke:1575:source-surface:0001'));
  insert into wnph.transmission_act_objects(transmission_act_id,direction,object_role,evidence_source_id,locator) values(v_act,'input','comparison_transcription',v_wikisource,jsonb_build_object('scan_page',1,'status','proofread_not_validated','conflict','William Dow'));
  insert into wnph.transmission_act_objects(transmission_act_id,direction,object_role,evidence_source_id,locator) values(v_act,'input','bibliographic_corroboration',v_catalog,jsonb_build_object('identifier','STC 3367','imprint','William How for Abraham Veale'));
  insert into wnph.transmission_act_objects(transmission_act_id,direction,object_role,publication_source_package_id) values(v_act,'context','canonical_publication_source',v_pkg);
  insert into wnph.transmission_act_objects(transmission_act_id,direction,object_role,publication_source_block_id) values(v_act,'context','title_page_reading_stream',v_parent);
  insert into wnph.transmission_act_evidence(transmission_act_id,source_id,support_role,confidence,note) values(v_act,v_commons,'supports','certain','Governed scan page 1 is the canonical reading authority.');
  insert into wnph.transmission_act_evidence(transmission_act_id,source_id,support_role,confidence,note) values(v_act,v_wikisource,'context','high','ProofreadPage comparison agrees broadly but conflicts on the printer surname, reading Dow rather than How.');
  insert into wnph.transmission_act_evidence(transmission_act_id,source_id,support_role,confidence,note) values(v_act,v_catalog,'supports','high','Independent catalog evidence identifies William How for Abraham Veale, corroborating the page-image reading.');

  insert into wnph.publication_source_blocks(source_package_id,block_key,parent_block_id,ordinal,block_type,semantic_role,text_content,properties,source_provenance,reading_state)
  values(v_pkg,'proper-new-booke:title-page:subtitle',v_parent,2,'paragraph','title_scope_statement','Declaring what maner of meates be best in season for al times of the yeere, and how they ought to be dressed, & serued at the Table, both for fleshe dayes and fish daies.',jsonb_build_object('scan_page',1,'canonical_status','admitted','modernization_performed',false),jsonb_build_object('verification_status','source_image_verified','text_authority','governed_same_witness_page_image','source_surface_asset_key','proper-new-booke:1575:source-surface:0001','reconstruction_proposal_id',v_prop_subtitle,'source_locators',jsonb_build_array(jsonb_build_object('scan_page',1,'asset_key','proper-new-booke:1575:source-surface:0001'))),'verified') returning id into v_block;
  insert into wnph.transmission_act_objects(transmission_act_id,direction,object_role,publication_source_block_id,locator) values(v_act,'output','canonical_title_scope_statement',v_block,jsonb_build_object('scan_page',1,'ordinal',2));
  insert into wnph.publication_source_blocks(source_package_id,block_key,parent_block_id,ordinal,block_type,semantic_role,text_content,properties,source_provenance,reading_state)
  values(v_pkg,'proper-new-booke:title-page:addition-notice',v_parent,3,'paragraph','edition_addition_notice','with a new addition, very necessary for al them that delight in Cookery.',jsonb_build_object('scan_page',1,'canonical_status','admitted','modernization_performed',false),jsonb_build_object('verification_status','source_image_verified','text_authority','governed_same_witness_page_image','source_surface_asset_key','proper-new-booke:1575:source-surface:0001','reconstruction_proposal_id',v_prop_addition,'source_locators',jsonb_build_array(jsonb_build_object('scan_page',1,'asset_key','proper-new-booke:1575:source-surface:0001'))),'verified') returning id into v_block;
  insert into wnph.transmission_act_objects(transmission_act_id,direction,object_role,publication_source_block_id,locator) values(v_act,'output','canonical_addition_notice',v_block,jsonb_build_object('scan_page',1,'ordinal',3));
  insert into wnph.publication_source_blocks(source_package_id,block_key,parent_block_id,ordinal,block_type,semantic_role,text_content,properties,source_provenance,reading_state)
  values(v_pkg,'proper-new-booke:title-page:date',v_parent,4,'paragraph','publication_date_as_printed','1575.',jsonb_build_object('scan_page',1,'canonical_status','admitted'),jsonb_build_object('verification_status','source_image_verified','text_authority','governed_same_witness_page_image','source_surface_asset_key','proper-new-booke:1575:source-surface:0001','reconstruction_proposal_id',v_prop_date,'source_locators',jsonb_build_array(jsonb_build_object('scan_page',1,'asset_key','proper-new-booke:1575:source-surface:0001'))),'verified') returning id into v_block;
  insert into wnph.transmission_act_objects(transmission_act_id,direction,object_role,publication_source_block_id,locator) values(v_act,'output','canonical_printed_date',v_block,jsonb_build_object('scan_page',1,'ordinal',4));
  insert into wnph.publication_source_blocks(source_package_id,block_key,parent_block_id,ordinal,block_type,semantic_role,text_content,properties,source_provenance,reading_state)
  values(v_pkg,'proper-new-booke:title-page:imprint',v_parent,5,'paragraph','imprint_as_printed','Imprinted at London in Fleet streete, by William How for Abraham Veale.',jsonb_build_object('scan_page',1,'canonical_status','admitted','modernization_performed',false,'wikisource_conflict','William Dow','admitted_reading','William How'),jsonb_build_object('verification_status','source_image_verified','text_authority','governed_same_witness_page_image','source_surface_asset_key','proper-new-booke:1575:source-surface:0001','reconstruction_proposal_id',v_prop_imprint,'source_locators',jsonb_build_array(jsonb_build_object('scan_page',1,'asset_key','proper-new-booke:1575:source-surface:0001')),'corroborating_catalog_source','heidelberg:1055289360'),'verified') returning id into v_block;
  insert into wnph.transmission_act_objects(transmission_act_id,direction,object_role,publication_source_block_id,locator) values(v_act,'output','canonical_imprint',v_block,jsonb_build_object('scan_page',1,'ordinal',5));
end $$;