-- Reality Motif substrate v1
-- Structural motifs are recovered from Reality Alignment graphs before native labels are inspected.

create table if not exists draft.reality_motif_registry (
  motif_id bigint generated by default as identity primary key,
  motif_key text not null unique,
  structure_version text not null,
  canonical_signature text not null,
  edge_count integer not null,
  node_count integer not null,
  motif_status text not null default 'candidate',
  notes text,
  metadata jsonb not null default '{}'::jsonb,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint reality_motif_registry_edge_count_check check (edge_count between 2 and 5),
  unique(structure_version,canonical_signature)
);

create table if not exists draft.reality_motif_instances (
  motif_instance_id bigint generated by default as identity primary key,
  motif_id bigint not null references draft.reality_motif_registry(motif_id) on update cascade on delete cascade,
  occurrence_id bigint not null references draft.reality_occurrences(occurrence_id) on update cascade on delete cascade,
  instance_key text not null unique,
  independence_key text not null,
  edge_count integer not null,
  node_count integer not null,
  edge_keys text[] not null,
  node_keys text[] not null,
  coordinate_groups text[] not null default '{}'::text[],
  witness_keys text[] not null default '{}'::text[],
  role_signature text,
  structure jsonb not null,
  instance_status text not null default 'materialized',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(occurrence_id,edge_keys)
);

create index if not exists reality_motif_instances_motif_idx
on draft.reality_motif_instances(motif_id,independence_key);

create index if not exists reality_motif_instances_occurrence_idx
on draft.reality_motif_instances(occurrence_id);

create table if not exists draft.reality_motif_compositions (
  motif_composition_id bigint generated by default as identity primary key,
  parent_motif_id bigint not null references draft.reality_motif_registry(motif_id) on update cascade on delete cascade,
  child_motif_id bigint not null references draft.reality_motif_registry(motif_id) on update cascade on delete cascade,
  composition_role text not null,
  composition_status text not null default 'candidate',
  evidence_count integer not null default 0,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(parent_motif_id,child_motif_id,composition_role)
);

comment on table draft.reality_motif_registry is
'Registry of label-stripped recurring graph structures recovered from Reality Alignment graphs. A motif is structural form, not an interpretation or domain concept.';
comment on table draft.reality_motif_instances is
'Concrete appearances of a structural motif inside one Reality Occurrence. Native labels are recoverable through edge/node references but are excluded from the motif canonical signature.';
comment on table draft.reality_motif_compositions is
'Composition graph between recovered motifs. Populated only when larger recurring structures can be shown to contain or compose smaller motifs.';

alter table draft.reality_motif_registry enable row level security;
alter table draft.reality_motif_instances enable row level security;
alter table draft.reality_motif_compositions enable row level security;

revoke all on draft.reality_motif_registry from anon,authenticated;
revoke all on draft.reality_motif_instances from anon,authenticated;
revoke all on draft.reality_motif_compositions from anon,authenticated;
grant select,insert,update,delete on draft.reality_motif_registry to service_role;
grant select,insert,update,delete on draft.reality_motif_instances to service_role;
grant select,insert,update,delete on draft.reality_motif_compositions to service_role;
grant usage,select on all sequences in schema draft to service_role;

update draft.reality_occurrences
set metadata = metadata || jsonb_build_object(
  'independenceKey','proving:head_pressure_dizziness_right_knee_ache_intermittent'
),
updated_at=now()
where occurrence_key in (
  'body_map_proving_head_right_knee_v1',
  'body_map_proving_generic_adapter_v1'
);

create or replace view intelligence.v_reality_alignment_graph_edges_v1
with (security_invoker=true)
as
 WITH counts AS (
         SELECT s.alignment_segment_id,
            count(*) FILTER (WHERE m.side = 'reality'::text)::integer AS reality_member_count,
            count(*) FILTER (WHERE m.side = 'witness'::text)::integer AS witness_member_count
           FROM draft.reality_alignment_segments s
             JOIN draft.reality_alignment_members m USING (alignment_segment_id)
          GROUP BY s.alignment_segment_id
        )
 SELECT s.occurrence_id,
    o.occurrence_key,
    COALESCE(o.metadata ->> 'independenceKey'::text, o.occurrence_key) AS independence_key,
    'member:'::text || m.alignment_member_id::text AS edge_key,
    'reality_touch'::text AS edge_class,
    'coordinate:'::text || c.occurrence_coordinate_id::text AS source_node_key,
    'coordinate'::text AS source_node_class,
    (('coordinate:'::text || d.dimension_family) || ':'::text) || c.coordinate_role AS source_structural_type,
    'alignment:'::text || s.alignment_segment_id::text AS target_node_key,
    'alignment'::text AS target_node_class,
    (('alignment:r'::text || ct.reality_member_count::text) || ':w'::text) || ct.witness_member_count::text AS target_structural_type,
    (('touch:'::text || d.dimension_family) || ':'::text) || c.coordinate_role AS edge_structural_type,
    m.member_role,
    c.coordinate_group_key,
    c.dimension_key,
    d.dimension_family,
    NULL::text AS witness_key,
    NULL::text AS object_type,
    NULL::text AS object_id,
    s.alignment_kind,
    s.relation_type,
    m.alignment_member_id
   FROM draft.reality_alignment_members m
     JOIN draft.reality_alignment_segments s USING (alignment_segment_id)
     JOIN draft.reality_occurrences o USING (occurrence_id)
     JOIN counts ct USING (alignment_segment_id)
     JOIN draft.reality_occurrence_coordinates c ON c.occurrence_coordinate_id = m.occurrence_coordinate_id
     JOIN draft.reality_query_dimension_registry d USING (dimension_key)
  WHERE m.side = 'reality'::text
UNION ALL
 SELECT s.occurrence_id,
    o.occurrence_key,
    COALESCE(o.metadata ->> 'independenceKey'::text, o.occurrence_key) AS independence_key,
    'member:'::text || m.alignment_member_id::text AS edge_key,
    'witness_touch'::text AS edge_class,
    'alignment:'::text || s.alignment_segment_id::text AS source_node_key,
    'alignment'::text AS source_node_class,
    (('alignment:r'::text || ct.reality_member_count::text) || ':w'::text) || ct.witness_member_count::text AS source_structural_type,
    (((('witness:'::text || m.witness_key) || ':'::text) || m.object_type) || ':'::text) || m.object_id AS target_node_key,
    'witness_object'::text AS target_node_class,
    'witness_object'::text AS target_structural_type,
    'touch:witness_object'::text AS edge_structural_type,
    m.member_role,
    NULL::text AS coordinate_group_key,
    NULL::text AS dimension_key,
    NULL::text AS dimension_family,
    m.witness_key,
    m.object_type,
    m.object_id,
    s.alignment_kind,
    s.relation_type,
    m.alignment_member_id
   FROM draft.reality_alignment_members m
     JOIN draft.reality_alignment_segments s USING (alignment_segment_id)
     JOIN draft.reality_occurrences o USING (occurrence_id)
     JOIN counts ct USING (alignment_segment_id)
  WHERE m.side = 'witness'::text;;

comment on view intelligence.v_reality_alignment_graph_edges_v1 is
'Label-strippable graph projection of Reality Alignment. Coordinate values, source labels, and native object names are absent from structural node/edge types; native references remain available separately for instance recovery.';

revoke all on intelligence.v_reality_alignment_graph_edges_v1 from anon,authenticated;
grant select on intelligence.v_reality_alignment_graph_edges_v1 to service_role;
