BEGIN;

-- Atlas Financial Reality Kernel v1.
-- Canonical migration identity generated by Supabase CLI v2.116.0.
-- Release provenance: 20260901173456_atlas_financial_reality_kernel_v1
--
-- Provider-neutral financial evidence/reconciliation authority. Stripe, banks,
-- accounting systems, invoices, receipts, and future sources remain witnesses;
-- no provider becomes universal economic or accounting truth.


-- === Financial Reality base authority ===
-- Atlas Financial Reality Kernel v1 — executable architecture proof only.
--
-- This file is intentionally NOT a canonical Supabase migration. It proves the
-- provider-neutral schema/authority contract while the branch remains stacked on
-- the Money Collection design. A governed migration identity must be generated
-- only after this wider contract is reviewed.

create table atlas.financial_source_observations (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references atlas.organizations(id) on delete restrict,
  connected_source_id uuid not null references atlas.connected_sources(id) on delete restrict,
  provider_record_kind text not null check (btrim(provider_record_kind) <> ''),
  provider_record_id text not null check (btrim(provider_record_id) <> ''),
  observation_fingerprint text not null check (btrim(observation_fingerprint) <> ''),
  provider_event_id text,
  observed_at timestamptz not null default now(),
  effective_at timestamptz,
  direction text check (direction is null or direction in ('inflow','outflow','transfer','noncash')),
  gross_amount numeric(18,2) check (gross_amount is null or gross_amount >= 0),
  fee_amount numeric(18,2) check (fee_amount is null or fee_amount >= 0),
  net_amount numeric(18,2) check (net_amount is null or net_amount >= 0),
  currency text,
  counterparty_label text,
  document_number text,
  description text,
  provider_state text,
  normalized_data jsonb not null default '{}'::jsonb,
  payload_sha256 text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint financial_source_observation_identity_uq
    unique (connected_source_id,provider_record_kind,provider_record_id,observation_fingerprint),
  check (currency is null or btrim(currency) <> ''),
  check (jsonb_typeof(normalized_data)='object'),
  check (jsonb_typeof(metadata)='object')
);

comment on table atlas.financial_source_observations is
  'Append-only normalized evidence from an organization-owned connected financial source. A source observation reports provider truth; it is not itself the canonical economic event.';

create index financial_source_observations_org_effective_idx
  on atlas.financial_source_observations(organization_id,effective_at desc,created_at desc,id);
create index financial_source_observations_provider_object_idx
  on atlas.financial_source_observations(connected_source_id,provider_record_kind,provider_record_id,created_at desc,id);
create index financial_source_observations_provider_event_idx
  on atlas.financial_source_observations(connected_source_id,provider_event_id)
  where provider_event_id is not null;

create table atlas.financial_economic_events (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references atlas.organizations(id) on delete restrict,
  event_key text not null check (btrim(event_key) <> ''),
  event_kind text not null check (btrim(event_kind) <> ''),
  direction text not null check (direction in ('inflow','outflow','transfer','noncash')),
  amount numeric(18,2) not null check (amount >= 0),
  currency text not null check (btrim(currency) <> ''),
  occurred_at timestamptz not null,
  counterparty_kind text,
  counterparty_id text,
  counterparty_label text,
  source_domain text,
  source_kind text,
  source_id text,
  authority_kind text not null check (btrim(authority_kind) <> ''),
  authority_ref text not null check (btrim(authority_ref) <> ''),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint financial_economic_event_key_uq unique(organization_id,event_key),
  check (
    (source_domain is null and source_kind is null and source_id is null)
    or
    (nullif(btrim(coalesce(source_domain,'')),'') is not null
      and nullif(btrim(coalesce(source_kind,'')),'') is not null
      and nullif(btrim(coalesce(source_id,'')),'') is not null)
  ),
  check (jsonb_typeof(metadata)='object')
);

comment on table atlas.financial_economic_events is
  'Provider-neutral canonical economic occurrences. Provider observations may establish/corroborate an event, but provider object identity never becomes the universal financial model.';

create index financial_economic_events_org_occurred_idx
  on atlas.financial_economic_events(organization_id,occurred_at desc,id);
create index financial_economic_events_source_idx
  on atlas.financial_economic_events(organization_id,source_domain,source_kind,source_id)
  where source_id is not null;

create table atlas.financial_event_evidence_links (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references atlas.organizations(id) on delete restrict,
  economic_event_id uuid not null references atlas.financial_economic_events(id) on delete restrict,
  observation_id uuid not null references atlas.financial_source_observations(id) on delete restrict,
  evidence_role text not null check (evidence_role in (
    'establishes','corroborates','documents','classifies','settles','contradicts'
  )),
  admission_kind text not null check (btrim(admission_kind) <> ''),
  admission_ref text not null check (btrim(admission_ref) <> ''),
  confidence numeric(6,5) check (confidence is null or (confidence >= 0 and confidence <= 1)),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint financial_event_evidence_link_uq unique(
    economic_event_id,observation_id,evidence_role,admission_kind,admission_ref
  ),
  check (jsonb_typeof(metadata)='object')
);

comment on table atlas.financial_event_evidence_links is
  'Accepted provenance connecting source observations to canonical economic events. A contradiction is preserved as evidence rather than silently resolved.';

create index financial_event_evidence_observation_idx
  on atlas.financial_event_evidence_links(observation_id,economic_event_id);

create table atlas.financial_event_relations (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references atlas.organizations(id) on delete restrict,
  from_event_id uuid not null references atlas.financial_economic_events(id) on delete restrict,
  to_event_id uuid not null references atlas.financial_economic_events(id) on delete restrict,
  relation_kind text not null check (btrim(relation_kind) <> ''),
  admission_kind text not null check (btrim(admission_kind) <> ''),
  admission_ref text not null check (btrim(admission_ref) <> ''),
  confidence numeric(6,5) check (confidence is null or (confidence >= 0 and confidence <= 1)),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint financial_event_relation_not_self check (from_event_id <> to_event_id),
  constraint financial_event_relation_uq unique(
    from_event_id,to_event_id,relation_kind,admission_kind,admission_ref
  ),
  check (jsonb_typeof(metadata)='object')
);

comment on table atlas.financial_event_relations is
  'Accepted relationships between canonical economic events, such as fee_on, refund_of, settles, contains, bank_settlement_of, or transfer_counterpart. Relations prevent settlement layers from becoming duplicate revenue.';

create index financial_event_relations_to_idx
  on atlas.financial_event_relations(to_event_id,relation_kind,from_event_id);

create table atlas.financial_classification_assertions (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references atlas.organizations(id) on delete restrict,
  economic_event_id uuid not null references atlas.financial_economic_events(id) on delete restrict,
  taxonomy_key text not null check (btrim(taxonomy_key) <> ''),
  classification_key text not null check (btrim(classification_key) <> ''),
  classification_label text,
  source_kind text not null check (source_kind in (
    'accounting_system','human','organization_rule','provider_hint','model_suggestion'
  )),
  source_ref text not null check (btrim(source_ref) <> ''),
  authority_rank integer not null check (authority_rank >= 0),
  confidence numeric(6,5) check (confidence is null or (confidence >= 0 and confidence <= 1)),
  supersedes_assertion_id uuid references atlas.financial_classification_assertions(id) on delete restrict,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint financial_classification_assertion_uq unique(
    economic_event_id,taxonomy_key,classification_key,source_kind,source_ref
  ),
  check (jsonb_typeof(metadata)='object')
);

comment on table atlas.financial_classification_assertions is
  'Append-only classification evidence. Event existence is independent from bookkeeping/tax classification; model/provider hints cannot silently overwrite stronger accounting/human evidence.';

create index financial_classification_event_taxonomy_idx
  on atlas.financial_classification_assertions(economic_event_id,taxonomy_key,authority_rank desc,created_at desc,id desc);

create or replace function atlas.reject_financial_history_mutation_v1()
returns trigger
language plpgsql
security definer
set search_path=pg_catalog,atlas
as $function$
begin
  raise exception 'Atlas financial source/reconciliation history is append-only.' using errcode='55000';
end;
$function$;

revoke all on function atlas.reject_financial_history_mutation_v1() from public,anon,authenticated,service_role;

create trigger financial_source_observations_append_only_v1
before update or delete on atlas.financial_source_observations
for each row execute function atlas.reject_financial_history_mutation_v1();
create trigger financial_economic_events_append_only_v1
before update or delete on atlas.financial_economic_events
for each row execute function atlas.reject_financial_history_mutation_v1();
create trigger financial_event_evidence_links_append_only_v1
before update or delete on atlas.financial_event_evidence_links
for each row execute function atlas.reject_financial_history_mutation_v1();
create trigger financial_event_relations_append_only_v1
before update or delete on atlas.financial_event_relations
for each row execute function atlas.reject_financial_history_mutation_v1();
create trigger financial_classification_assertions_append_only_v1
before update or delete on atlas.financial_classification_assertions
for each row execute function atlas.reject_financial_history_mutation_v1();

create or replace function atlas.guard_financial_source_observation_custody_v1()
returns trigger
language plpgsql
security definer
set search_path=pg_catalog,atlas
as $function$
declare
  v_source atlas.connected_sources%rowtype;
begin
  select * into v_source
  from atlas.connected_sources s
  where s.id=new.connected_source_id;

  if v_source.id is null then
    raise exception 'Connected financial source not found.' using errcode='23503';
  end if;
  if v_source.custodian_organization_id is null
     or v_source.custodian_organization_id is distinct from new.organization_id then
    raise exception 'Financial source observation is outside organization source custody.' using errcode='42501';
  end if;
  return new;
end;
$function$;

revoke all on function atlas.guard_financial_source_observation_custody_v1() from public,anon,authenticated,service_role;

create trigger financial_source_observation_custody_guard_v1
before insert on atlas.financial_source_observations
for each row execute function atlas.guard_financial_source_observation_custody_v1();

create or replace function atlas.guard_financial_event_evidence_custody_v1()
returns trigger
language plpgsql
security definer
set search_path=pg_catalog,atlas
as $function$
declare
  v_event_org uuid;
  v_observation_org uuid;
begin
  select organization_id into v_event_org
  from atlas.financial_economic_events where id=new.economic_event_id;
  select organization_id into v_observation_org
  from atlas.financial_source_observations where id=new.observation_id;
  if v_event_org is null or v_observation_org is null then
    raise exception 'Financial event/evidence reference not found.' using errcode='23503';
  end if;
  if v_event_org is distinct from new.organization_id
     or v_observation_org is distinct from new.organization_id then
    raise exception 'Financial evidence link crosses organization custody.' using errcode='42501';
  end if;
  return new;
end;
$function$;

revoke all on function atlas.guard_financial_event_evidence_custody_v1() from public,anon,authenticated,service_role;

create trigger financial_event_evidence_custody_guard_v1
before insert on atlas.financial_event_evidence_links
for each row execute function atlas.guard_financial_event_evidence_custody_v1();

create or replace function atlas.guard_financial_event_relation_custody_v1()
returns trigger
language plpgsql
security definer
set search_path=pg_catalog,atlas
as $function$
declare
  v_from_org uuid;
  v_to_org uuid;
begin
  select organization_id into v_from_org from atlas.financial_economic_events where id=new.from_event_id;
  select organization_id into v_to_org from atlas.financial_economic_events where id=new.to_event_id;
  if v_from_org is null or v_to_org is null then
    raise exception 'Financial relation event not found.' using errcode='23503';
  end if;
  if v_from_org is distinct from new.organization_id
     or v_to_org is distinct from new.organization_id then
    raise exception 'Financial event relation crosses organization custody.' using errcode='42501';
  end if;
  return new;
end;
$function$;

revoke all on function atlas.guard_financial_event_relation_custody_v1() from public,anon,authenticated,service_role;

create trigger financial_event_relation_custody_guard_v1
before insert on atlas.financial_event_relations
for each row execute function atlas.guard_financial_event_relation_custody_v1();

create or replace function atlas.guard_financial_classification_custody_v1()
returns trigger
language plpgsql
security definer
set search_path=pg_catalog,atlas
as $function$
declare
  v_event_org uuid;
  v_superseded atlas.financial_classification_assertions%rowtype;
begin
  select organization_id into v_event_org
  from atlas.financial_economic_events where id=new.economic_event_id;
  if v_event_org is null or v_event_org is distinct from new.organization_id then
    raise exception 'Financial classification crosses organization custody.' using errcode='42501';
  end if;
  if new.supersedes_assertion_id is not null then
    select * into v_superseded
    from atlas.financial_classification_assertions
    where id=new.supersedes_assertion_id;
    if v_superseded.id is null
       or v_superseded.organization_id is distinct from new.organization_id
       or v_superseded.economic_event_id is distinct from new.economic_event_id
       or v_superseded.taxonomy_key is distinct from new.taxonomy_key then
      raise exception 'Financial classification supersession does not match event/taxonomy custody.' using errcode='23514';
    end if;
  end if;
  return new;
end;
$function$;

revoke all on function atlas.guard_financial_classification_custody_v1() from public,anon,authenticated,service_role;

create trigger financial_classification_custody_guard_v1
before insert on atlas.financial_classification_assertions
for each row execute function atlas.guard_financial_classification_custody_v1();

create or replace function atlas.record_financial_source_observation_core_v1(
  p_organization_id uuid,
  p_connected_source_id uuid,
  p_provider_record_kind text,
  p_provider_record_id text,
  p_observation_fingerprint text,
  p_provider_event_id text,
  p_observed_at timestamptz,
  p_effective_at timestamptz,
  p_direction text,
  p_gross_amount numeric,
  p_fee_amount numeric,
  p_net_amount numeric,
  p_currency text,
  p_counterparty_label text,
  p_document_number text,
  p_description text,
  p_provider_state text,
  p_normalized_data jsonb,
  p_payload_sha256 text,
  p_metadata jsonb default '{}'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path=pg_catalog,atlas
as $function$
declare
  v_existing atlas.financial_source_observations%rowtype;
  v_row atlas.financial_source_observations%rowtype;
begin
  if p_organization_id is null or p_connected_source_id is null
     or nullif(btrim(coalesce(p_provider_record_kind,'')),'') is null
     or nullif(btrim(coalesce(p_provider_record_id,'')),'') is null
     or nullif(btrim(coalesce(p_observation_fingerprint,'')),'') is null then
    raise exception 'Financial source observation requires organization, source, provider record identity, and fingerprint.' using errcode='22023';
  end if;

  select * into v_existing
  from atlas.financial_source_observations o
  where o.connected_source_id=p_connected_source_id
    and o.provider_record_kind=btrim(p_provider_record_kind)
    and o.provider_record_id=btrim(p_provider_record_id)
    and o.observation_fingerprint=btrim(p_observation_fingerprint);

  if v_existing.id is not null then
    return jsonb_build_object(
      'contractVersion','record_financial_source_observation_core_v1',
      'state','unchanged','observationId',v_existing.id,'deduplicated',true
    );
  end if;

  insert into atlas.financial_source_observations(
    organization_id,connected_source_id,provider_record_kind,provider_record_id,
    observation_fingerprint,provider_event_id,observed_at,effective_at,direction,
    gross_amount,fee_amount,net_amount,currency,counterparty_label,document_number,
    description,provider_state,normalized_data,payload_sha256,metadata
  ) values (
    p_organization_id,p_connected_source_id,btrim(p_provider_record_kind),btrim(p_provider_record_id),
    btrim(p_observation_fingerprint),nullif(btrim(coalesce(p_provider_event_id,'')),''),
    coalesce(p_observed_at,now()),p_effective_at,p_direction,
    case when p_gross_amount is null then null else round(p_gross_amount,2) end,
    case when p_fee_amount is null then null else round(p_fee_amount,2) end,
    case when p_net_amount is null then null else round(p_net_amount,2) end,
    nullif(lower(btrim(coalesce(p_currency,''))),''),nullif(btrim(coalesce(p_counterparty_label,'')),''),
    nullif(btrim(coalesce(p_document_number,'')),''),nullif(btrim(coalesce(p_description,'')),''),
    nullif(btrim(coalesce(p_provider_state,'')),''),coalesce(p_normalized_data,'{}'::jsonb),
    nullif(btrim(coalesce(p_payload_sha256,'')),''),coalesce(p_metadata,'{}'::jsonb)
  ) returning * into v_row;

  return jsonb_build_object(
    'contractVersion','record_financial_source_observation_core_v1',
    'state','recorded','observationId',v_row.id,'deduplicated',false
  );
end;
$function$;

create or replace function atlas.ensure_financial_economic_event_core_v1(
  p_organization_id uuid,
  p_event_key text,
  p_event_kind text,
  p_direction text,
  p_amount numeric,
  p_currency text,
  p_occurred_at timestamptz,
  p_counterparty_kind text,
  p_counterparty_id text,
  p_counterparty_label text,
  p_source_domain text,
  p_source_kind text,
  p_source_id text,
  p_authority_kind text,
  p_authority_ref text,
  p_metadata jsonb default '{}'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path=pg_catalog,atlas
as $function$
declare
  v_existing atlas.financial_economic_events%rowtype;
  v_row atlas.financial_economic_events%rowtype;
begin
  if p_organization_id is null
     or nullif(btrim(coalesce(p_event_key,'')),'') is null
     or nullif(btrim(coalesce(p_event_kind,'')),'') is null
     or p_direction not in ('inflow','outflow','transfer','noncash')
     or p_amount is null or p_amount<0
     or nullif(btrim(coalesce(p_currency,'')),'') is null
     or p_occurred_at is null
     or nullif(btrim(coalesce(p_authority_kind,'')),'') is null
     or nullif(btrim(coalesce(p_authority_ref,'')),'') is null then
    raise exception 'Financial economic event requires organization, stable key, kind, direction, non-negative amount, currency, occurredAt, and authority.' using errcode='22023';
  end if;

  select * into v_existing
  from atlas.financial_economic_events e
  where e.organization_id=p_organization_id and e.event_key=btrim(p_event_key);

  if v_existing.id is not null then
    if v_existing.event_kind is distinct from btrim(p_event_kind)
       or v_existing.direction is distinct from p_direction
       or v_existing.amount is distinct from round(p_amount,2)
       or v_existing.currency is distinct from lower(btrim(p_currency))
       or v_existing.occurred_at is distinct from p_occurred_at
       or v_existing.source_domain is distinct from nullif(btrim(coalesce(p_source_domain,'')),'')
       or v_existing.source_kind is distinct from nullif(btrim(coalesce(p_source_kind,'')),'')
       or v_existing.source_id is distinct from nullif(btrim(coalesce(p_source_id,'')),'')
       or v_existing.authority_kind is distinct from btrim(p_authority_kind)
       or v_existing.authority_ref is distinct from btrim(p_authority_ref) then
      raise exception 'Existing financial event key cannot be silently rewritten.' using errcode='55000';
    end if;
    return jsonb_build_object(
      'contractVersion','ensure_financial_economic_event_core_v1',
      'state','unchanged','economicEventId',v_existing.id,'deduplicated',true
    );
  end if;

  insert into atlas.financial_economic_events(
    organization_id,event_key,event_kind,direction,amount,currency,occurred_at,
    counterparty_kind,counterparty_id,counterparty_label,
    source_domain,source_kind,source_id,authority_kind,authority_ref,metadata
  ) values (
    p_organization_id,btrim(p_event_key),btrim(p_event_kind),p_direction,round(p_amount,2),lower(btrim(p_currency)),p_occurred_at,
    nullif(btrim(coalesce(p_counterparty_kind,'')),''),nullif(btrim(coalesce(p_counterparty_id,'')),''),
    nullif(btrim(coalesce(p_counterparty_label,'')),''),nullif(btrim(coalesce(p_source_domain,'')),''),
    nullif(btrim(coalesce(p_source_kind,'')),''),nullif(btrim(coalesce(p_source_id,'')),''),
    btrim(p_authority_kind),btrim(p_authority_ref),coalesce(p_metadata,'{}'::jsonb)
  ) returning * into v_row;

  return jsonb_build_object(
    'contractVersion','ensure_financial_economic_event_core_v1',
    'state','recorded','economicEventId',v_row.id,'deduplicated',false
  );
end;
$function$;

create or replace function atlas.link_financial_observation_to_event_core_v1(
  p_organization_id uuid,
  p_economic_event_id uuid,
  p_observation_id uuid,
  p_evidence_role text,
  p_admission_kind text,
  p_admission_ref text,
  p_confidence numeric,
  p_metadata jsonb default '{}'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path=pg_catalog,atlas
as $function$
declare
  v_row atlas.financial_event_evidence_links%rowtype;
begin
  if p_evidence_role not in ('establishes','corroborates','documents','classifies','settles','contradicts')
     or nullif(btrim(coalesce(p_admission_kind,'')),'') is null
     or nullif(btrim(coalesce(p_admission_ref,'')),'') is null then
    raise exception 'Financial evidence link requires a supported role and explicit admission basis.' using errcode='22023';
  end if;
  insert into atlas.financial_event_evidence_links(
    organization_id,economic_event_id,observation_id,evidence_role,admission_kind,admission_ref,confidence,metadata
  ) values (
    p_organization_id,p_economic_event_id,p_observation_id,p_evidence_role,
    btrim(p_admission_kind),btrim(p_admission_ref),p_confidence,coalesce(p_metadata,'{}'::jsonb)
  ) on conflict (economic_event_id,observation_id,evidence_role,admission_kind,admission_ref)
    do update set economic_event_id=excluded.economic_event_id
  returning * into v_row;
  return jsonb_build_object(
    'contractVersion','link_financial_observation_to_event_core_v1',
    'evidenceLinkId',v_row.id
  );
end;
$function$;

create or replace function atlas.relate_financial_economic_events_core_v1(
  p_organization_id uuid,
  p_from_event_id uuid,
  p_to_event_id uuid,
  p_relation_kind text,
  p_admission_kind text,
  p_admission_ref text,
  p_confidence numeric,
  p_metadata jsonb default '{}'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path=pg_catalog,atlas
as $function$
declare
  v_row atlas.financial_event_relations%rowtype;
begin
  if nullif(btrim(coalesce(p_relation_kind,'')),'') is null
     or nullif(btrim(coalesce(p_admission_kind,'')),'') is null
     or nullif(btrim(coalesce(p_admission_ref,'')),'') is null then
    raise exception 'Financial event relation requires relation kind and explicit admission basis.' using errcode='22023';
  end if;
  insert into atlas.financial_event_relations(
    organization_id,from_event_id,to_event_id,relation_kind,admission_kind,admission_ref,confidence,metadata
  ) values (
    p_organization_id,p_from_event_id,p_to_event_id,btrim(p_relation_kind),
    btrim(p_admission_kind),btrim(p_admission_ref),p_confidence,coalesce(p_metadata,'{}'::jsonb)
  ) on conflict (from_event_id,to_event_id,relation_kind,admission_kind,admission_ref)
    do update set from_event_id=excluded.from_event_id
  returning * into v_row;
  return jsonb_build_object(
    'contractVersion','relate_financial_economic_events_core_v1',
    'relationId',v_row.id
  );
end;
$function$;

create or replace function atlas.assert_financial_classification_core_v1(
  p_organization_id uuid,
  p_economic_event_id uuid,
  p_taxonomy_key text,
  p_classification_key text,
  p_classification_label text,
  p_source_kind text,
  p_source_ref text,
  p_authority_rank integer,
  p_confidence numeric,
  p_supersedes_assertion_id uuid,
  p_metadata jsonb default '{}'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path=pg_catalog,atlas
as $function$
declare
  v_row atlas.financial_classification_assertions%rowtype;
begin
  if nullif(btrim(coalesce(p_taxonomy_key,'')),'') is null
     or nullif(btrim(coalesce(p_classification_key,'')),'') is null
     or p_source_kind not in ('accounting_system','human','organization_rule','provider_hint','model_suggestion')
     or nullif(btrim(coalesce(p_source_ref,'')),'') is null
     or p_authority_rank is null or p_authority_rank<0 then
    raise exception 'Financial classification requires taxonomy, classification, source, and non-negative authority rank.' using errcode='22023';
  end if;
  insert into atlas.financial_classification_assertions(
    organization_id,economic_event_id,taxonomy_key,classification_key,classification_label,
    source_kind,source_ref,authority_rank,confidence,supersedes_assertion_id,metadata
  ) values (
    p_organization_id,p_economic_event_id,btrim(p_taxonomy_key),btrim(p_classification_key),
    nullif(btrim(coalesce(p_classification_label,'')),''),p_source_kind,btrim(p_source_ref),
    p_authority_rank,p_confidence,p_supersedes_assertion_id,coalesce(p_metadata,'{}'::jsonb)
  ) on conflict (economic_event_id,taxonomy_key,classification_key,source_kind,source_ref)
    do update set economic_event_id=excluded.economic_event_id
  returning * into v_row;
  return jsonb_build_object(
    'contractVersion','assert_financial_classification_core_v1',
    'classificationAssertionId',v_row.id
  );
end;
$function$;

-- Provider-neutral read position. This deliberately reports ambiguity instead of
-- selecting a category when multiple unsuperseded top-authority assertions disagree.
create or replace view atlas.financial_classification_position_v1 as
with current_assertions as (
  select a.*
  from atlas.financial_classification_assertions a
  where not exists (
    select 1 from atlas.financial_classification_assertions newer
    where newer.supersedes_assertion_id=a.id
  )
), ranked as (
  select a.*,
         max(a.authority_rank) over(partition by a.economic_event_id,a.taxonomy_key) as top_rank
  from current_assertions a
), top_set as (
  select * from ranked where authority_rank=top_rank
)
select
  e.organization_id,
  e.id as economic_event_id,
  t.taxonomy_key,
  count(distinct t.classification_key)::integer as top_classification_count,
  case when count(distinct t.classification_key)=1 then min(t.classification_key) else null end as effective_classification_key,
  case when count(distinct t.classification_key)=1 then min(t.classification_label) else null end as effective_classification_label,
  case
    when count(distinct t.classification_key)=0 then 'missing'
    when count(distinct t.classification_key)=1 then 'resolved'
    else 'conflict'
  end as classification_state,
  max(t.top_rank) as authority_rank
from atlas.financial_economic_events e
join top_set t on t.economic_event_id=e.id
Group by e.organization_id,e.id,t.taxonomy_key;

-- Minimal reconciliation position: external observations without an accepted
-- evidence link remain unresolved; explicit contradiction evidence remains visible.
create or replace view atlas.financial_observation_reconciliation_position_v1 as
select
  o.organization_id,
  o.id as observation_id,
  o.connected_source_id,
  o.provider_record_kind,
  o.provider_record_id,
  o.observation_fingerprint,
  count(l.id)::integer as accepted_link_count,
  count(l.id) filter(where l.evidence_role='contradicts')::integer as contradiction_count,
  case
    when count(l.id)=0 then 'unreconciled'
    when count(l.id) filter(where l.evidence_role='contradicts')>0 then 'contradictory'
    else 'linked'
  end as reconciliation_state
from atlas.financial_source_observations o
left join atlas.financial_event_evidence_links l on l.observation_id=o.id
Group by o.organization_id,o.id,o.connected_source_id,o.provider_record_kind,o.provider_record_id,o.observation_fingerprint;

alter table atlas.financial_source_observations enable row level security;
alter table atlas.financial_economic_events enable row level security;
alter table atlas.financial_event_evidence_links enable row level security;
alter table atlas.financial_event_relations enable row level security;
alter table atlas.financial_classification_assertions enable row level security;

revoke all on atlas.financial_source_observations from public,anon,authenticated,service_role;
revoke all on atlas.financial_economic_events from public,anon,authenticated,service_role;
revoke all on atlas.financial_event_evidence_links from public,anon,authenticated,service_role;
revoke all on atlas.financial_event_relations from public,anon,authenticated,service_role;
revoke all on atlas.financial_classification_assertions from public,anon,authenticated,service_role;
revoke all on atlas.financial_classification_position_v1 from public,anon,authenticated,service_role;
revoke all on atlas.financial_observation_reconciliation_position_v1 from public,anon,authenticated,service_role;

grant select,insert on atlas.financial_source_observations to service_role;
grant select,insert on atlas.financial_economic_events to service_role;
grant select,insert on atlas.financial_event_evidence_links to service_role;
grant select,insert on atlas.financial_event_relations to service_role;
grant select,insert on atlas.financial_classification_assertions to service_role;
grant select on atlas.financial_classification_position_v1 to service_role;
grant select on atlas.financial_observation_reconciliation_position_v1 to service_role;

revoke all on function atlas.record_financial_source_observation_core_v1(
  uuid,uuid,text,text,text,text,timestamptz,timestamptz,text,numeric,numeric,numeric,text,text,text,text,text,jsonb,text,jsonb
) from public,anon,authenticated;
grant execute on function atlas.record_financial_source_observation_core_v1(
  uuid,uuid,text,text,text,text,timestamptz,timestamptz,text,numeric,numeric,numeric,text,text,text,text,text,jsonb,text,jsonb
) to service_role;

revoke all on function atlas.ensure_financial_economic_event_core_v1(
  uuid,text,text,text,numeric,text,timestamptz,text,text,text,text,text,text,text,text,jsonb
) from public,anon,authenticated;
grant execute on function atlas.ensure_financial_economic_event_core_v1(
  uuid,text,text,text,numeric,text,timestamptz,text,text,text,text,text,text,text,text,jsonb
) to service_role;

revoke all on function atlas.link_financial_observation_to_event_core_v1(
  uuid,uuid,uuid,text,text,text,numeric,jsonb
) from public,anon,authenticated;
grant execute on function atlas.link_financial_observation_to_event_core_v1(
  uuid,uuid,uuid,text,text,text,numeric,jsonb
) to service_role;

revoke all on function atlas.relate_financial_economic_events_core_v1(
  uuid,uuid,uuid,text,text,text,numeric,jsonb
) from public,anon,authenticated;
grant execute on function atlas.relate_financial_economic_events_core_v1(
  uuid,uuid,uuid,text,text,text,numeric,jsonb
) to service_role;

revoke all on function atlas.assert_financial_classification_core_v1(
  uuid,uuid,text,text,text,text,text,integer,numeric,uuid,jsonb
) from public,anon,authenticated;
grant execute on function atlas.assert_financial_classification_core_v1(
  uuid,uuid,text,text,text,text,text,integer,numeric,uuid,jsonb
) to service_role;

-- Structural proofs.
do $proof$
declare
  v_missing integer;
begin
  if not exists(
    select 1 from pg_trigger t
    join pg_class c on c.oid=t.tgrelid
    join pg_namespace n on n.oid=c.relnamespace
    where n.nspname='atlas' and c.relname='financial_source_observations'
      and t.tgname='financial_source_observation_custody_guard_v1' and not t.tgisinternal
  ) then
    raise exception 'Financial Reality proof failed: connected-source organization custody guard missing.';
  end if;

  if has_table_privilege('authenticated','atlas.financial_source_observations','SELECT')
     or has_table_privilege('authenticated','atlas.financial_economic_events','SELECT') then
    raise exception 'Financial Reality proof failed: raw financial tables leaked to authenticated role.';
  end if;

  select count(*) into v_missing
  from (values
    ('record_financial_source_observation_core_v1'),
    ('ensure_financial_economic_event_core_v1'),
    ('link_financial_observation_to_event_core_v1'),
    ('relate_financial_economic_events_core_v1'),
    ('assert_financial_classification_core_v1')
  ) required(name)
  where not exists(
    select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace
    where n.nspname='atlas' and p.proname=required.name
  );
  if v_missing<>0 then
    raise exception 'Financial Reality proof failed: % core functions missing.',v_missing;
  end if;
end;
$proof$;

-- Architecture proof only.


-- === Append-only idempotency correction ===
-- Atlas Financial Reality Kernel v1 — append-only idempotency correction.
-- Reviewed architecture-source SQL only; assemble after atlas-financial-reality-kernel-v1.sql.
--
-- Append-only evidence tables cannot use ON CONFLICT DO UPDATE, even for a no-op,
-- because the update itself violates the history-mutation fence. Duplicate calls
-- must return the already-recorded row without issuing an UPDATE.

create or replace function atlas.link_financial_observation_to_event_core_v1(
  p_organization_id uuid,
  p_economic_event_id uuid,
  p_observation_id uuid,
  p_evidence_role text,
  p_admission_kind text,
  p_admission_ref text,
  p_confidence numeric,
  p_metadata jsonb default '{}'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path=pg_catalog,atlas
as $function$
declare
  v_row atlas.financial_event_evidence_links%rowtype;
begin
  if p_evidence_role not in ('establishes','corroborates','documents','classifies','settles','contradicts')
     or nullif(btrim(coalesce(p_admission_kind,'')),'') is null
     or nullif(btrim(coalesce(p_admission_ref,'')),'') is null then
    raise exception 'Financial evidence link requires a supported role and explicit admission basis.' using errcode='22023';
  end if;

  select * into v_row
  from atlas.financial_event_evidence_links l
  where l.economic_event_id=p_economic_event_id
    and l.observation_id=p_observation_id
    and l.evidence_role=p_evidence_role
    and l.admission_kind=btrim(p_admission_kind)
    and l.admission_ref=btrim(p_admission_ref);

  if v_row.id is not null then
    return jsonb_build_object(
      'contractVersion','link_financial_observation_to_event_core_v1',
      'state','unchanged','evidenceLinkId',v_row.id,'deduplicated',true
    );
  end if;

  begin
    insert into atlas.financial_event_evidence_links(
      organization_id,economic_event_id,observation_id,evidence_role,
      admission_kind,admission_ref,confidence,metadata
    ) values (
      p_organization_id,p_economic_event_id,p_observation_id,p_evidence_role,
      btrim(p_admission_kind),btrim(p_admission_ref),p_confidence,coalesce(p_metadata,'{}'::jsonb)
    ) returning * into v_row;
  exception when unique_violation then
    select * into v_row
    from atlas.financial_event_evidence_links l
    where l.economic_event_id=p_economic_event_id
      and l.observation_id=p_observation_id
      and l.evidence_role=p_evidence_role
      and l.admission_kind=btrim(p_admission_kind)
      and l.admission_ref=btrim(p_admission_ref);
  end;

  return jsonb_build_object(
    'contractVersion','link_financial_observation_to_event_core_v1',
    'state','recorded','evidenceLinkId',v_row.id,
    'deduplicated',false
  );
end;
$function$;

create or replace function atlas.relate_financial_economic_events_core_v1(
  p_organization_id uuid,
  p_from_event_id uuid,
  p_to_event_id uuid,
  p_relation_kind text,
  p_admission_kind text,
  p_admission_ref text,
  p_confidence numeric,
  p_metadata jsonb default '{}'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path=pg_catalog,atlas
as $function$
declare
  v_row atlas.financial_event_relations%rowtype;
begin
  if nullif(btrim(coalesce(p_relation_kind,'')),'') is null
     or nullif(btrim(coalesce(p_admission_kind,'')),'') is null
     or nullif(btrim(coalesce(p_admission_ref,'')),'') is null then
    raise exception 'Financial event relation requires relation kind and explicit admission basis.' using errcode='22023';
  end if;

  select * into v_row
  from atlas.financial_event_relations r
  where r.from_event_id=p_from_event_id
    and r.to_event_id=p_to_event_id
    and r.relation_kind=btrim(p_relation_kind)
    and r.admission_kind=btrim(p_admission_kind)
    and r.admission_ref=btrim(p_admission_ref);

  if v_row.id is not null then
    return jsonb_build_object(
      'contractVersion','relate_financial_economic_events_core_v1',
      'state','unchanged','relationId',v_row.id,'deduplicated',true
    );
  end if;

  begin
    insert into atlas.financial_event_relations(
      organization_id,from_event_id,to_event_id,relation_kind,
      admission_kind,admission_ref,confidence,metadata
    ) values (
      p_organization_id,p_from_event_id,p_to_event_id,btrim(p_relation_kind),
      btrim(p_admission_kind),btrim(p_admission_ref),p_confidence,coalesce(p_metadata,'{}'::jsonb)
    ) returning * into v_row;
  exception when unique_violation then
    select * into v_row
    from atlas.financial_event_relations r
    where r.from_event_id=p_from_event_id
      and r.to_event_id=p_to_event_id
      and r.relation_kind=btrim(p_relation_kind)
      and r.admission_kind=btrim(p_admission_kind)
      and r.admission_ref=btrim(p_admission_ref);
  end;

  return jsonb_build_object(
    'contractVersion','relate_financial_economic_events_core_v1',
    'state','recorded','relationId',v_row.id,'deduplicated',false
  );
end;
$function$;

create or replace function atlas.assert_financial_classification_core_v1(
  p_organization_id uuid,
  p_economic_event_id uuid,
  p_taxonomy_key text,
  p_classification_key text,
  p_classification_label text,
  p_source_kind text,
  p_source_ref text,
  p_authority_rank integer,
  p_confidence numeric,
  p_supersedes_assertion_id uuid,
  p_metadata jsonb default '{}'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path=pg_catalog,atlas
as $function$
declare
  v_row atlas.financial_classification_assertions%rowtype;
begin
  if nullif(btrim(coalesce(p_taxonomy_key,'')),'') is null
     or nullif(btrim(coalesce(p_classification_key,'')),'') is null
     or p_source_kind not in ('accounting_system','human','organization_rule','provider_hint','model_suggestion')
     or nullif(btrim(coalesce(p_source_ref,'')),'') is null
     or p_authority_rank is null or p_authority_rank<0 then
    raise exception 'Financial classification requires taxonomy, classification, source, and non-negative authority rank.' using errcode='22023';
  end if;

  select * into v_row
  from atlas.financial_classification_assertions a
  where a.economic_event_id=p_economic_event_id
    and a.taxonomy_key=btrim(p_taxonomy_key)
    and a.classification_key=btrim(p_classification_key)
    and a.source_kind=p_source_kind
    and a.source_ref=btrim(p_source_ref);

  if v_row.id is not null then
    if v_row.organization_id is distinct from p_organization_id
       or v_row.authority_rank is distinct from p_authority_rank
       or v_row.confidence is distinct from p_confidence
       or v_row.supersedes_assertion_id is distinct from p_supersedes_assertion_id then
      raise exception 'Existing financial classification assertion identity cannot be silently rewritten.' using errcode='55000';
    end if;
    return jsonb_build_object(
      'contractVersion','assert_financial_classification_core_v1',
      'state','unchanged','classificationAssertionId',v_row.id,'deduplicated',true
    );
  end if;

  begin
    insert into atlas.financial_classification_assertions(
      organization_id,economic_event_id,taxonomy_key,classification_key,classification_label,
      source_kind,source_ref,authority_rank,confidence,supersedes_assertion_id,metadata
    ) values (
      p_organization_id,p_economic_event_id,btrim(p_taxonomy_key),btrim(p_classification_key),
      nullif(btrim(coalesce(p_classification_label,'')),''),p_source_kind,btrim(p_source_ref),
      p_authority_rank,p_confidence,p_supersedes_assertion_id,coalesce(p_metadata,'{}'::jsonb)
    ) returning * into v_row;
  exception when unique_violation then
    select * into v_row
    from atlas.financial_classification_assertions a
    where a.economic_event_id=p_economic_event_id
      and a.taxonomy_key=btrim(p_taxonomy_key)
      and a.classification_key=btrim(p_classification_key)
      and a.source_kind=p_source_kind
      and a.source_ref=btrim(p_source_ref);
  end;

  return jsonb_build_object(
    'contractVersion','assert_financial_classification_core_v1',
    'state','recorded','classificationAssertionId',v_row.id,'deduplicated',false
  );
end;
$function$;


-- === Organization connected-source command membrane ===
-- Atlas Organization Connected Source Commands v1 — executable architecture source.
--
-- This is not a canonical migration. It closes the provider-neutral mutation seam
-- needed by Financial Reality before any Stripe/bank/accounting adapter is added.

create or replace function atlas.organization_connected_source_actor_authorized_v1(
  p_organization_id uuid
)
returns boolean
language sql
stable
security definer
set search_path=pg_catalog,atlas,auth
as $function$
  select auth.uid() is not null and (
    atlas.is_organization_owner(p_organization_id)
    or exists(
      select 1
      from atlas.organization_onboarding_actors a
      where a.organization_id=p_organization_id
        and a.human_user_id=auth.uid()
        and a.actor_kind='setup_actor'
        and a.active=true
        and a.ended_at is null
    )
  );
$function$;

revoke all on function atlas.organization_connected_source_actor_authorized_v1(uuid)
  from public,anon,authenticated,service_role;

create or replace function atlas.register_organization_connected_source_api_v1(
  p_organization_id uuid,
  p_provider_key text,
  p_provider_account_key text,
  p_display_label text,
  p_account_hint text,
  p_authorization_state text,
  p_granted_scopes text[],
  p_capabilities jsonb,
  p_metadata jsonb default '{}'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path=pg_catalog,atlas,auth
as $function$
declare
  v_provider_key text:=lower(nullif(btrim(coalesce(p_provider_key,'')),''));
  v_provider_account_key text:=nullif(btrim(coalesce(p_provider_account_key,'')),'');
  v_state text:=lower(nullif(btrim(coalesce(p_authorization_state,'')),''));
  v_existing atlas.connected_sources%rowtype;
  v_row atlas.connected_sources%rowtype;
begin
  if auth.uid() is null then
    raise exception 'Authenticated organization connector actor required.' using errcode='42501';
  end if;
  if p_organization_id is null
     or v_provider_key is null
     or v_provider_account_key is null then
    raise exception 'Organization, provider key, and stable provider account key are required.' using errcode='22023';
  end if;
  if not atlas.organization_connected_source_actor_authorized_v1(p_organization_id) then
    raise exception 'Organization owner or active setup actor authority required.' using errcode='42501';
  end if;
  if v_state not in ('pending','connected','reauthorization_required','error') then
    raise exception 'New source authorization state must be pending, connected, reauthorization_required, or error.' using errcode='22023';
  end if;
  if p_capabilities is null or jsonb_typeof(p_capabilities)<>'object' then
    raise exception 'Connected source capabilities must be a JSON object.' using errcode='22023';
  end if;
  if p_metadata is null or jsonb_typeof(p_metadata)<>'object' then
    raise exception 'Connected source metadata must be a JSON object.' using errcode='22023';
  end if;

  perform pg_advisory_xact_lock(hashtextextended(
    p_organization_id::text||':'||v_provider_key||':'||v_provider_account_key,0
  ));

  select * into v_existing
  from atlas.connected_sources s
  where s.custodian_organization_id=p_organization_id
    and s.provider_key=v_provider_key
    and s.provider_account_key=v_provider_account_key
  limit 1;

  if v_existing.id is not null then
    -- Source identity is stable. Registration retry may refresh descriptive
    -- provider evidence, but it may not silently resurrect a revoked source.
    if v_existing.custodian_user_id is not null then
      raise exception 'Connected source custody shape is invalid.' using errcode='23514';
    end if;
    if v_existing.authorization_state='revoked' then
      raise exception 'Revoked source requires explicit reauthorization command.' using errcode='55000';
    end if;

    update atlas.connected_sources
    set display_label=coalesce(nullif(btrim(coalesce(p_display_label,'')),''),display_label),
        account_hint=coalesce(nullif(btrim(coalesce(p_account_hint,'')),''),account_hint),
        authorization_state=v_state,
        granted_scopes=coalesce(p_granted_scopes,'{}'::text[]),
        capabilities=p_capabilities,
        metadata=coalesce(metadata,'{}'::jsonb)||p_metadata,
        revoked_at=null
    where id=v_existing.id
    returning * into v_row;

    return jsonb_build_object(
      'contractVersion','register_organization_connected_source_api_v1',
      'state','reused','sourceId',v_row.id,'deduplicated',true,
      'authorizationState',v_row.authorization_state
    );
  end if;

  insert into atlas.connected_sources(
    custodian_user_id,custodian_organization_id,provider_key,provider_account_key,
    display_label,account_hint,authorization_state,granted_scopes,capabilities,metadata
  ) values (
    null,p_organization_id,v_provider_key,v_provider_account_key,
    nullif(btrim(coalesce(p_display_label,'')),''),
    nullif(btrim(coalesce(p_account_hint,'')),''),
    v_state,coalesce(p_granted_scopes,'{}'::text[]),p_capabilities,p_metadata
  ) returning * into v_row;

  return jsonb_build_object(
    'contractVersion','register_organization_connected_source_api_v1',
    'state','registered','sourceId',v_row.id,'deduplicated',false,
    'authorizationState',v_row.authorization_state
  );
end;
$function$;

revoke all on function atlas.register_organization_connected_source_api_v1(
  uuid,text,text,text,text,text,text[],jsonb,jsonb
) from public,anon;
grant execute on function atlas.register_organization_connected_source_api_v1(
  uuid,text,text,text,text,text,text[],jsonb,jsonb
) to authenticated,service_role;

create or replace function atlas.transition_organization_connected_source_api_v1(
  p_organization_id uuid,
  p_connected_source_id uuid,
  p_to_state text,
  p_granted_scopes text[],
  p_capabilities jsonb,
  p_reason text,
  p_metadata jsonb default '{}'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path=pg_catalog,atlas,auth
as $function$
declare
  v_source atlas.connected_sources%rowtype;
  v_to text:=lower(nullif(btrim(coalesce(p_to_state,'')),''));
  v_reason text:=nullif(btrim(coalesce(p_reason,'')),'');
begin
  if auth.uid() is null then
    raise exception 'Authenticated organization connector actor required.' using errcode='42501';
  end if;
  if not atlas.organization_connected_source_actor_authorized_v1(p_organization_id) then
    raise exception 'Organization owner or active setup actor authority required.' using errcode='42501';
  end if;
  if p_connected_source_id is null or v_reason is null then
    raise exception 'Connected source and explicit transition reason are required.' using errcode='22023';
  end if;
  if v_to not in ('pending','connected','reauthorization_required','revoked','error') then
    raise exception 'Unsupported connected source authorization state.' using errcode='22023';
  end if;
  if p_capabilities is not null and jsonb_typeof(p_capabilities)<>'object' then
    raise exception 'Connected source capabilities must be a JSON object.' using errcode='22023';
  end if;

  select * into v_source
  from atlas.connected_sources s
  where s.id=p_connected_source_id
    and s.custodian_organization_id=p_organization_id
    and s.custodian_user_id is null
  for update;

  if v_source.id is null then
    raise exception 'Organization-owned connected source not found.' using errcode='P0002';
  end if;

  if v_source.authorization_state='revoked' and v_to<>'connected' then
    raise exception 'Revoked source may only return through an explicit fresh connected authorization.' using errcode='23514';
  end if;

  update atlas.connected_sources
  set authorization_state=v_to,
      granted_scopes=case when p_granted_scopes is null then granted_scopes else p_granted_scopes end,
      capabilities=case when p_capabilities is null then capabilities else p_capabilities end,
      revoked_at=case when v_to='revoked' then now() else null end,
      metadata=coalesce(metadata,'{}'::jsonb)||coalesce(p_metadata,'{}'::jsonb)||jsonb_build_object(
        'lastAuthorizationTransition',jsonb_build_object(
          'from',v_source.authorization_state,
          'to',v_to,
          'reason',v_reason,
          'actorUserId',auth.uid(),
          'at',now()
        )
      )
  where id=v_source.id
  returning * into v_source;

  return jsonb_build_object(
    'contractVersion','transition_organization_connected_source_api_v1',
    'state','transitioned','sourceId',v_source.id,
    'authorizationState',v_source.authorization_state
  );
end;
$function$;

revoke all on function atlas.transition_organization_connected_source_api_v1(
  uuid,uuid,text,text[],jsonb,text,jsonb
) from public,anon;
grant execute on function atlas.transition_organization_connected_source_api_v1(
  uuid,uuid,text,text[],jsonb,text,jsonb
) to authenticated,service_role;

-- Provider callbacks/synchronizers need a service-only path that cannot nominate
-- another organization. Source identity itself resolves organization custody.
create or replace function atlas.mark_connected_source_provider_state_core_v1(
  p_connected_source_id uuid,
  p_to_state text,
  p_reason text,
  p_last_sync_at timestamptz,
  p_metadata jsonb default '{}'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path=pg_catalog,atlas
as $function$
declare
  v_source atlas.connected_sources%rowtype;
  v_to text:=lower(nullif(btrim(coalesce(p_to_state,'')),''));
begin
  if p_connected_source_id is null
     or v_to not in ('connected','reauthorization_required','error')
     or nullif(btrim(coalesce(p_reason,'')),'') is null then
    raise exception 'Provider-state update requires source, supported state, and reason.' using errcode='22023';
  end if;

  select * into v_source
  from atlas.connected_sources s
  where s.id=p_connected_source_id
    and s.custodian_organization_id is not null
    and s.custodian_user_id is null
  for update;
  if v_source.id is null then
    raise exception 'Organization-owned connected source not found.' using errcode='P0002';
  end if;
  if v_source.authorization_state='revoked' then
    raise exception 'Provider evidence cannot silently resurrect a revoked connected source.' using errcode='23514';
  end if;

  update atlas.connected_sources
  set authorization_state=v_to,
      last_sync_at=coalesce(p_last_sync_at,last_sync_at),
      metadata=coalesce(metadata,'{}'::jsonb)||coalesce(p_metadata,'{}'::jsonb)||jsonb_build_object(
        'lastProviderStateEvidence',jsonb_build_object(
          'to',v_to,'reason',btrim(p_reason),'at',now()
        )
      )
  where id=v_source.id
  returning * into v_source;

  return jsonb_build_object(
    'contractVersion','mark_connected_source_provider_state_core_v1',
    'sourceId',v_source.id,'authorizationState',v_source.authorization_state,
    'lastSyncAt',v_source.last_sync_at
  );
end;
$function$;

revoke all on function atlas.mark_connected_source_provider_state_core_v1(
  uuid,text,text,timestamptz,jsonb
) from public,anon,authenticated;
grant execute on function atlas.mark_connected_source_provider_state_core_v1(
  uuid,text,text,timestamptz,jsonb
) to service_role;

-- Structural proof.
do $proof$
begin
  if has_function_privilege('anon','atlas.register_organization_connected_source_api_v1(uuid,text,text,text,text,text,text[],jsonb,jsonb)','EXECUTE') then
    raise exception 'Organization connected-source proof failed: anonymous mutation leaked.';
  end if;
  if not has_function_privilege('authenticated','atlas.register_organization_connected_source_api_v1(uuid,text,text,text,text,text,text[],jsonb,jsonb)','EXECUTE') then
    raise exception 'Organization connected-source proof failed: authenticated command unavailable.';
  end if;
  if has_function_privilege('authenticated','atlas.mark_connected_source_provider_state_core_v1(uuid,text,text,timestamptz,jsonb)','EXECUTE') then
    raise exception 'Organization connected-source proof failed: provider-state core leaked to authenticated.';
  end if;
end;
$proof$;


-- === Vault-backed connected-source secret custody ===
-- Atlas Connected Source Secret Custody v1 — executable architecture source.
--
-- Reusable OAuth/API credentials are encrypted in Supabase Vault. Atlas stores
-- only immutable references and append-only revocation/rotation provenance.
-- No authenticated API returns decrypted credential material.

create table atlas.connected_source_secret_refs (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references atlas.organizations(id) on delete restrict,
  connected_source_id uuid not null references atlas.connected_sources(id) on delete restrict,
  secret_kind text not null check (btrim(secret_kind) <> ''),
  version_number integer not null check (version_number > 0),
  vault_secret_id uuid not null,
  prior_secret_ref_id uuid references atlas.connected_source_secret_refs(id) on delete restrict,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint connected_source_secret_version_uq unique(connected_source_id,secret_kind,version_number),
  constraint connected_source_secret_vault_uq unique(vault_secret_id),
  check (jsonb_typeof(metadata)='object')
);

comment on table atlas.connected_source_secret_refs is
  'Immutable reference history for reusable credentials encrypted in Supabase Vault. This table contains no secret plaintext.';

create index connected_source_secret_refs_lookup_idx
  on atlas.connected_source_secret_refs(connected_source_id,secret_kind,version_number desc,id desc);

create table atlas.connected_source_secret_revocation_events (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references atlas.organizations(id) on delete restrict,
  secret_ref_id uuid not null references atlas.connected_source_secret_refs(id) on delete restrict,
  reason text not null check (btrim(reason) <> ''),
  replacement_secret_ref_id uuid references atlas.connected_source_secret_refs(id) on delete restrict,
  metadata jsonb not null default '{}'::jsonb,
  revoked_at timestamptz not null default now(),
  constraint connected_source_secret_revocation_once_uq unique(secret_ref_id),
  check (replacement_secret_ref_id is null or replacement_secret_ref_id <> secret_ref_id),
  check (jsonb_typeof(metadata)='object')
);

comment on table atlas.connected_source_secret_revocation_events is
  'Append-only evidence that a connected-source secret version is no longer current. Rotation creates a new Vault secret and revokes the prior reference.';

create or replace function atlas.reject_connected_source_secret_history_mutation_v1()
returns trigger
language plpgsql
security definer
set search_path=pg_catalog,atlas
as $function$
begin
  raise exception 'Connected-source credential reference history is append-only.' using errcode='55000';
end;
$function$;

revoke all on function atlas.reject_connected_source_secret_history_mutation_v1()
  from public,anon,authenticated,service_role;

create trigger connected_source_secret_refs_append_only_v1
before update or delete on atlas.connected_source_secret_refs
for each row execute function atlas.reject_connected_source_secret_history_mutation_v1();
create trigger connected_source_secret_revocation_events_append_only_v1
before update or delete on atlas.connected_source_secret_revocation_events
for each row execute function atlas.reject_connected_source_secret_history_mutation_v1();

create or replace function atlas.guard_connected_source_secret_ref_custody_v1()
returns trigger
language plpgsql
security definer
set search_path=pg_catalog,atlas
as $function$
declare
  v_source_org uuid;
  v_prior atlas.connected_source_secret_refs%rowtype;
begin
  select s.custodian_organization_id into v_source_org
  from atlas.connected_sources s
  where s.id=new.connected_source_id
    and s.custodian_user_id is null;
  if v_source_org is null or v_source_org is distinct from new.organization_id then
    raise exception 'Connected-source secret reference is outside organization custody.' using errcode='42501';
  end if;

  if new.prior_secret_ref_id is not null then
    select * into v_prior from atlas.connected_source_secret_refs where id=new.prior_secret_ref_id;
    if v_prior.id is null
       or v_prior.organization_id is distinct from new.organization_id
       or v_prior.connected_source_id is distinct from new.connected_source_id
       or v_prior.secret_kind is distinct from new.secret_kind
       or v_prior.version_number+1 is distinct from new.version_number then
      raise exception 'Connected-source secret rotation chain is invalid.' using errcode='23514';
    end if;
  elsif new.version_number<>1 then
    raise exception 'First connected-source secret version must be version 1.' using errcode='23514';
  end if;
  return new;
end;
$function$;

revoke all on function atlas.guard_connected_source_secret_ref_custody_v1()
  from public,anon,authenticated,service_role;

create trigger connected_source_secret_ref_custody_guard_v1
before insert on atlas.connected_source_secret_refs
for each row execute function atlas.guard_connected_source_secret_ref_custody_v1();

create or replace function atlas.guard_connected_source_secret_revocation_custody_v1()
returns trigger
language plpgsql
security definer
set search_path=pg_catalog,atlas
as $function$
declare
  v_secret atlas.connected_source_secret_refs%rowtype;
  v_replacement atlas.connected_source_secret_refs%rowtype;
begin
  select * into v_secret from atlas.connected_source_secret_refs where id=new.secret_ref_id;
  if v_secret.id is null or v_secret.organization_id is distinct from new.organization_id then
    raise exception 'Connected-source secret revocation is outside organization custody.' using errcode='42501';
  end if;
  if new.replacement_secret_ref_id is not null then
    select * into v_replacement from atlas.connected_source_secret_refs where id=new.replacement_secret_ref_id;
    if v_replacement.id is null
       or v_replacement.organization_id is distinct from new.organization_id
       or v_replacement.connected_source_id is distinct from v_secret.connected_source_id
       or v_replacement.secret_kind is distinct from v_secret.secret_kind
       or v_replacement.prior_secret_ref_id is distinct from v_secret.id then
      raise exception 'Replacement credential does not continue the revoked secret chain.' using errcode='23514';
    end if;
  end if;
  return new;
end;
$function$;

revoke all on function atlas.guard_connected_source_secret_revocation_custody_v1()
  from public,anon,authenticated,service_role;

create trigger connected_source_secret_revocation_custody_guard_v1
before insert on atlas.connected_source_secret_revocation_events
for each row execute function atlas.guard_connected_source_secret_revocation_custody_v1();

create or replace function atlas.current_connected_source_secret_ref_core_v1(
  p_connected_source_id uuid,
  p_secret_kind text
)
returns atlas.connected_source_secret_refs
language sql
stable
security definer
set search_path=pg_catalog,atlas
as $function$
  select r
  from atlas.connected_source_secret_refs r
  where r.connected_source_id=p_connected_source_id
    and r.secret_kind=btrim(p_secret_kind)
    and not exists(
      select 1 from atlas.connected_source_secret_revocation_events x
      where x.secret_ref_id=r.id
    )
  order by r.version_number desc,r.id desc
  limit 1;
$function$;

revoke all on function atlas.current_connected_source_secret_ref_core_v1(uuid,text)
  from public,anon,authenticated,service_role;

create or replace function atlas.put_connected_source_secret_core_v1(
  p_connected_source_id uuid,
  p_secret_kind text,
  p_secret_value text,
  p_reason text,
  p_metadata jsonb default '{}'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path=pg_catalog,atlas,vault
as $function$
declare
  v_source atlas.connected_sources%rowtype;
  v_kind text:=lower(nullif(btrim(coalesce(p_secret_kind,'')),''));
  v_reason text:=nullif(btrim(coalesce(p_reason,'')),'');
  v_prior atlas.connected_source_secret_refs%rowtype;
  v_new atlas.connected_source_secret_refs%rowtype;
  v_new_vault_id uuid;
  v_version integer;
  v_secret_name text;
begin
  if p_connected_source_id is null
     or v_kind is null
     or p_secret_value is null or p_secret_value=''
     or v_reason is null then
    raise exception 'Connected-source credential storage requires source, kind, secret value, and reason.' using errcode='22023';
  end if;
  if p_metadata is null or jsonb_typeof(p_metadata)<>'object' then
    raise exception 'Connected-source credential metadata must be a JSON object.' using errcode='22023';
  end if;

  select * into v_source
  from atlas.connected_sources s
  where s.id=p_connected_source_id
    and s.custodian_organization_id is not null
    and s.custodian_user_id is null;
  if v_source.id is null then
    raise exception 'Organization-owned connected source not found.' using errcode='P0002';
  end if;

  perform pg_advisory_xact_lock(hashtextextended(v_source.id::text||':'||v_kind,0));
  select * into v_prior from atlas.current_connected_source_secret_ref_core_v1(v_source.id,v_kind);
  v_version:=coalesce(v_prior.version_number,0)+1;
  v_secret_name:='atlas_source_'||replace(v_source.id::text,'-','')||'_'||regexp_replace(v_kind,'[^a-z0-9_]+','_','g')||'_v'||v_version::text||'_'||replace(gen_random_uuid()::text,'-','');

  v_new_vault_id:=vault.create_secret(
    p_secret_value,
    v_secret_name,
    'Atlas connected source credential. source='||v_source.id::text||' kind='||v_kind||' version='||v_version::text,
    null
  );

  insert into atlas.connected_source_secret_refs(
    organization_id,connected_source_id,secret_kind,version_number,vault_secret_id,
    prior_secret_ref_id,metadata
  ) values (
    v_source.custodian_organization_id,v_source.id,v_kind,v_version,v_new_vault_id,
    v_prior.id,coalesce(p_metadata,'{}'::jsonb)||jsonb_build_object('reason',v_reason)
  ) returning * into v_new;

  if v_prior.id is not null then
    insert into atlas.connected_source_secret_revocation_events(
      organization_id,secret_ref_id,reason,replacement_secret_ref_id,metadata
    ) values (
      v_source.custodian_organization_id,v_prior.id,'rotated: '||v_reason,v_new.id,
      jsonb_build_object('rotation',true)
    );
    -- Destroy the reusable prior plaintext in Vault while preserving its secret id
    -- as historical custody provenance. The generated marker is not usable auth material.
    perform vault.update_secret(
      v_prior.vault_secret_id,
      'revoked:'||gen_random_uuid()::text,
      null,
      'Revoked Atlas connected source credential reference '||v_prior.id::text,
      null
    );
  end if;

  return jsonb_build_object(
    'contractVersion','put_connected_source_secret_core_v1',
    'sourceId',v_source.id,
    'secretKind',v_kind,
    'secretRefId',v_new.id,
    'versionNumber',v_new.version_number,
    'rotated',v_prior.id is not null
  );
end;
$function$;

create or replace function atlas.read_connected_source_secret_core_v1(
  p_connected_source_id uuid,
  p_secret_kind text
)
returns text
language plpgsql
stable
security definer
set search_path=pg_catalog,atlas,vault
as $function$
declare
  v_ref atlas.connected_source_secret_refs%rowtype;
  v_secret text;
begin
  select * into v_ref
  from atlas.current_connected_source_secret_ref_core_v1(p_connected_source_id,btrim(p_secret_kind));
  if v_ref.id is null then
    return null;
  end if;
  select d.decrypted_secret into v_secret
  from vault.decrypted_secrets d
  where d.id=v_ref.vault_secret_id;
  return v_secret;
end;
$function$;

create or replace function atlas.revoke_connected_source_secret_core_v1(
  p_connected_source_id uuid,
  p_secret_kind text,
  p_reason text,
  p_metadata jsonb default '{}'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path=pg_catalog,atlas,vault
as $function$
declare
  v_ref atlas.connected_source_secret_refs%rowtype;
  v_source atlas.connected_sources%rowtype;
begin
  if nullif(btrim(coalesce(p_reason,'')),'') is null then
    raise exception 'Connected-source credential revocation requires an explicit reason.' using errcode='22023';
  end if;
  select * into v_source from atlas.connected_sources where id=p_connected_source_id and custodian_organization_id is not null;
  if v_source.id is null then raise exception 'Organization-owned connected source not found.' using errcode='P0002'; end if;
  perform pg_advisory_xact_lock(hashtextextended(v_source.id::text||':'||lower(btrim(p_secret_kind)),0));
  select * into v_ref from atlas.current_connected_source_secret_ref_core_v1(v_source.id,lower(btrim(p_secret_kind)));
  if v_ref.id is null then
    return jsonb_build_object(
      'contractVersion','revoke_connected_source_secret_core_v1','state','already_absent',
      'sourceId',v_source.id,'secretKind',lower(btrim(p_secret_kind))
    );
  end if;

  insert into atlas.connected_source_secret_revocation_events(
    organization_id,secret_ref_id,reason,metadata
  ) values (
    v_source.custodian_organization_id,v_ref.id,btrim(p_reason),coalesce(p_metadata,'{}'::jsonb)
  );
  perform vault.update_secret(
    v_ref.vault_secret_id,
    'revoked:'||gen_random_uuid()::text,
    null,
    'Revoked Atlas connected source credential reference '||v_ref.id::text,
    null
  );

  return jsonb_build_object(
    'contractVersion','revoke_connected_source_secret_core_v1','state','revoked',
    'sourceId',v_source.id,'secretKind',v_ref.secret_kind,'secretRefId',v_ref.id
  );
end;
$function$;

alter table atlas.connected_source_secret_refs enable row level security;
alter table atlas.connected_source_secret_revocation_events enable row level security;

revoke all on atlas.connected_source_secret_refs from public,anon,authenticated,service_role;
revoke all on atlas.connected_source_secret_revocation_events from public,anon,authenticated,service_role;
grant select,insert on atlas.connected_source_secret_refs to service_role;
grant select,insert on atlas.connected_source_secret_revocation_events to service_role;

revoke all on function atlas.put_connected_source_secret_core_v1(uuid,text,text,text,jsonb)
  from public,anon,authenticated;
grant execute on function atlas.put_connected_source_secret_core_v1(uuid,text,text,text,jsonb)
  to service_role;
revoke all on function atlas.read_connected_source_secret_core_v1(uuid,text)
  from public,anon,authenticated;
grant execute on function atlas.read_connected_source_secret_core_v1(uuid,text)
  to service_role;
revoke all on function atlas.revoke_connected_source_secret_core_v1(uuid,text,text,jsonb)
  from public,anon,authenticated;
grant execute on function atlas.revoke_connected_source_secret_core_v1(uuid,text,text,jsonb)
  to service_role;

-- Vault itself remains inaccessible to browser roles. Service code receives only
-- the requested secret through the narrow source/kind resolver above.
do $proof$
begin
  if has_table_privilege('anon','vault.decrypted_secrets','SELECT')
     or has_table_privilege('authenticated','vault.decrypted_secrets','SELECT') then
    raise exception 'Connected-source secret proof failed: Vault decrypted secrets leaked to browser role.';
  end if;
  if has_function_privilege('authenticated','atlas.read_connected_source_secret_core_v1(uuid,text)','EXECUTE') then
    raise exception 'Connected-source secret proof failed: decrypted secret resolver leaked to authenticated.';
  end if;
  if has_table_privilege('authenticated','atlas.connected_source_secret_refs','SELECT') then
    raise exception 'Connected-source secret proof failed: credential reference table leaked to authenticated.';
  end if;
end;
$proof$;


-- === Provider delivery/replay custody ===
-- Atlas Financial Source Delivery Custody v1 — executable architecture source.
--
-- Provider deliveries/webhooks are transport evidence, not canonical financial
-- truth. They are deduplicated independently from provider objects because a
-- provider can legitimately send multiple events about one changing object.

create table atlas.financial_source_delivery_events (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references atlas.organizations(id) on delete restrict,
  connected_source_id uuid not null references atlas.connected_sources(id) on delete restrict,
  provider_event_id text not null check (btrim(provider_event_id) <> ''),
  provider_event_kind text not null check (btrim(provider_event_kind) <> ''),
  payload_sha256 text not null check (btrim(payload_sha256) <> ''),
  provider_created_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  received_at timestamptz not null default now(),
  constraint financial_source_delivery_event_uq unique(connected_source_id,provider_event_id),
  check (jsonb_typeof(metadata)='object')
);

comment on table atlas.financial_source_delivery_events is
  'Immutable provider delivery identity/replay evidence. Recording a delivery does not establish any economic event by itself.';

create index financial_source_delivery_received_idx
  on atlas.financial_source_delivery_events(organization_id,received_at desc,id desc);

create table atlas.financial_source_delivery_processing_events (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references atlas.organizations(id) on delete restrict,
  delivery_event_id uuid not null references atlas.financial_source_delivery_events(id) on delete restrict,
  processing_kind text not null check (processing_kind in ('succeeded','failed','ignored')),
  processor_contract text not null check (btrim(processor_contract) <> ''),
  detail jsonb not null default '{}'::jsonb,
  processed_at timestamptz not null default now(),
  check (jsonb_typeof(detail)='object')
);

comment on table atlas.financial_source_delivery_processing_events is
  'Append-only processing outcomes for provider delivery evidence. A failed delivery remains retryable; idempotent observation/event commands make concurrent retries safe.';

create index financial_source_delivery_processing_idx
  on atlas.financial_source_delivery_processing_events(delivery_event_id,processed_at desc,id desc);

create trigger financial_source_delivery_events_append_only_v1
before update or delete on atlas.financial_source_delivery_events
for each row execute function atlas.reject_financial_history_mutation_v1();
create trigger financial_source_delivery_processing_events_append_only_v1
before update or delete on atlas.financial_source_delivery_processing_events
for each row execute function atlas.reject_financial_history_mutation_v1();

create or replace function atlas.guard_financial_source_delivery_custody_v1()
returns trigger
language plpgsql
security definer
set search_path=pg_catalog,atlas
as $function$
declare
  v_source_org uuid;
begin
  select s.custodian_organization_id into v_source_org
  from atlas.connected_sources s
  where s.id=new.connected_source_id
    and s.custodian_user_id is null;
  if v_source_org is null or v_source_org is distinct from new.organization_id then
    raise exception 'Financial provider delivery is outside organization source custody.' using errcode='42501';
  end if;
  return new;
end;
$function$;

revoke all on function atlas.guard_financial_source_delivery_custody_v1()
  from public,anon,authenticated,service_role;

create trigger financial_source_delivery_custody_guard_v1
before insert on atlas.financial_source_delivery_events
for each row execute function atlas.guard_financial_source_delivery_custody_v1();

create or replace function atlas.guard_financial_source_delivery_processing_custody_v1()
returns trigger
language plpgsql
security definer
set search_path=pg_catalog,atlas
as $function$
declare
  v_delivery_org uuid;
begin
  select d.organization_id into v_delivery_org
  from atlas.financial_source_delivery_events d where d.id=new.delivery_event_id;
  if v_delivery_org is null or v_delivery_org is distinct from new.organization_id then
    raise exception 'Financial delivery processing event crosses organization custody.' using errcode='42501';
  end if;
  return new;
end;
$function$;

revoke all on function atlas.guard_financial_source_delivery_processing_custody_v1()
  from public,anon,authenticated,service_role;

create trigger financial_source_delivery_processing_custody_guard_v1
before insert on atlas.financial_source_delivery_processing_events
for each row execute function atlas.guard_financial_source_delivery_processing_custody_v1();

create or replace function atlas.record_financial_source_delivery_core_v1(
  p_connected_source_id uuid,
  p_provider_event_id text,
  p_provider_event_kind text,
  p_payload_sha256 text,
  p_provider_created_at timestamptz,
  p_metadata jsonb default '{}'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path=pg_catalog,atlas
as $function$
declare
  v_source atlas.connected_sources%rowtype;
  v_existing atlas.financial_source_delivery_events%rowtype;
  v_row atlas.financial_source_delivery_events%rowtype;
begin
  if p_connected_source_id is null
     or nullif(btrim(coalesce(p_provider_event_id,'')),'') is null
     or nullif(btrim(coalesce(p_provider_event_kind,'')),'') is null
     or nullif(btrim(coalesce(p_payload_sha256,'')),'') is null then
    raise exception 'Financial provider delivery requires source, provider event identity/kind, and payload hash.' using errcode='22023';
  end if;
  select * into v_source
  from atlas.connected_sources s
  where s.id=p_connected_source_id
    and s.custodian_organization_id is not null
    and s.custodian_user_id is null;
  if v_source.id is null then
    raise exception 'Organization-owned financial connected source not found.' using errcode='P0002';
  end if;

  select * into v_existing
  from atlas.financial_source_delivery_events d
  where d.connected_source_id=v_source.id
    and d.provider_event_id=btrim(p_provider_event_id);
  if v_existing.id is not null then
    if v_existing.provider_event_kind is distinct from btrim(p_provider_event_kind)
       or v_existing.payload_sha256 is distinct from btrim(p_payload_sha256) then
      raise exception 'Provider event id replayed with contradictory event kind or payload.' using errcode='55000';
    end if;
    return jsonb_build_object(
      'contractVersion','record_financial_source_delivery_core_v1',
      'state','duplicate','deliveryEventId',v_existing.id,
      'alreadySucceeded',exists(
        select 1 from atlas.financial_source_delivery_processing_events p
        where p.delivery_event_id=v_existing.id and p.processing_kind='succeeded'
      )
    );
  end if;

  begin
    insert into atlas.financial_source_delivery_events(
      organization_id,connected_source_id,provider_event_id,provider_event_kind,
      payload_sha256,provider_created_at,metadata
    ) values (
      v_source.custodian_organization_id,v_source.id,btrim(p_provider_event_id),
      btrim(p_provider_event_kind),btrim(p_payload_sha256),p_provider_created_at,
      coalesce(p_metadata,'{}'::jsonb)
    ) returning * into v_row;
  exception when unique_violation then
    select * into v_row
    from atlas.financial_source_delivery_events d
    where d.connected_source_id=v_source.id
      and d.provider_event_id=btrim(p_provider_event_id);
  end;

  return jsonb_build_object(
    'contractVersion','record_financial_source_delivery_core_v1',
    'state','recorded','deliveryEventId',v_row.id,'alreadySucceeded',false
  );
end;
$function$;

create or replace function atlas.record_financial_source_delivery_processing_core_v1(
  p_delivery_event_id uuid,
  p_processing_kind text,
  p_processor_contract text,
  p_detail jsonb default '{}'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path=pg_catalog,atlas
as $function$
declare
  v_delivery atlas.financial_source_delivery_events%rowtype;
  v_row atlas.financial_source_delivery_processing_events%rowtype;
begin
  if p_delivery_event_id is null
     or p_processing_kind not in ('succeeded','failed','ignored')
     or nullif(btrim(coalesce(p_processor_contract,'')),'') is null then
    raise exception 'Financial delivery processing outcome requires delivery, supported outcome, and processor contract.' using errcode='22023';
  end if;
  select * into v_delivery from atlas.financial_source_delivery_events where id=p_delivery_event_id;
  if v_delivery.id is null then raise exception 'Financial provider delivery not found.' using errcode='P0002'; end if;

  insert into atlas.financial_source_delivery_processing_events(
    organization_id,delivery_event_id,processing_kind,processor_contract,detail
  ) values (
    v_delivery.organization_id,v_delivery.id,p_processing_kind,btrim(p_processor_contract),coalesce(p_detail,'{}'::jsonb)
  ) returning * into v_row;

  return jsonb_build_object(
    'contractVersion','record_financial_source_delivery_processing_core_v1',
    'processingEventId',v_row.id,'processingKind',v_row.processing_kind
  );
end;
$function$;

alter table atlas.financial_source_delivery_events enable row level security;
alter table atlas.financial_source_delivery_processing_events enable row level security;
revoke all on atlas.financial_source_delivery_events from public,anon,authenticated,service_role;
revoke all on atlas.financial_source_delivery_processing_events from public,anon,authenticated,service_role;
grant select,insert on atlas.financial_source_delivery_events to service_role;
grant select,insert on atlas.financial_source_delivery_processing_events to service_role;

revoke all on function atlas.record_financial_source_delivery_core_v1(uuid,text,text,text,timestamptz,jsonb)
  from public,anon,authenticated;
grant execute on function atlas.record_financial_source_delivery_core_v1(uuid,text,text,text,timestamptz,jsonb)
  to service_role;
revoke all on function atlas.record_financial_source_delivery_processing_core_v1(uuid,text,text,jsonb)
  from public,anon,authenticated;
grant execute on function atlas.record_financial_source_delivery_processing_core_v1(uuid,text,text,jsonb)
  to service_role;


COMMIT;
