create table if not exists draft.sacred_time_witness_divergences (
  divergence_id bigint generated by default as identity primary key,
  divergence_key text not null unique,
  witness_family text not null default 'old_greek_vs_mt',
  canonical_book_code text not null,
  chapter integer not null,
  verse_start integer not null,
  verse_end integer,
  topic text not null,
  hebrew_anchor text,
  greek_anchor text,
  hebrew_reading_summary text not null,
  old_greek_reading_summary text not null,
  divergence_type text not null,
  materiality text not null,
  calculation_effect text,
  semantic_effect text,
  likely_explanation_state text not null default 'unresolved',
  source_basis text not null default 'Noel MT/LXX alignment corpus',
  alignment_evidence jsonb not null default '{}'::jsonb,
  evidence_state text not null default 'captured',
  review_status text not null default 'needs_review',
  priority integer,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint sacred_time_witness_divergences_verse_range_chk check (verse_end is null or verse_end >= verse_start),
  constraint sacred_time_witness_divergences_priority_chk check (priority is null or priority between 1 and 5)
);

create index if not exists sacred_time_witness_divergences_passage_idx
  on draft.sacred_time_witness_divergences (canonical_book_code, chapter, verse_start, verse_end);

create index if not exists sacred_time_witness_divergences_topic_idx
  on draft.sacred_time_witness_divergences (topic);

create index if not exists sacred_time_witness_divergences_review_idx
  on draft.sacred_time_witness_divergences (review_status, priority);

comment on table draft.sacred_time_witness_divergences is
  'Noel research registry for material Old Greek / MT differences that can alter or pressure feast, Sabbath, Jubilee, month-head, release, counting, or sacred-time interpretation. A row records a witness divergence, not an adjudicated canon rule.';

comment on column draft.sacred_time_witness_divergences.likely_explanation_state is
  'Keep textual variant, alternate Vorlage, semantic translation, harmonization, explicitation, and other explanations unresolved until separately adjudicated.';