-- ATLAS_REALITY_ORGANIZATION_TOPOLOGY_V1
select reality.register_topology_axis_service_v1('operating_structure','Operating structure','Direct operating containment for units, branches, locations, departments, clinics, and schools. Corporate control, franchise, chapter, and brand relationships are intentionally excluded.',false,'acyclic',jsonb_build_object('coreContract','ATLAS_REALITY_ORGANIZATION_TOPOLOGY_V1'));
select reality.register_presence_class_service_v1('direct_operating_presence','Direct operating presence','The child is a direct operating component of the parent for topology and presence traversal. This does not assert legal identity equality or communication authority.','direct',jsonb_build_object('coreContract','ATLAS_REALITY_ORGANIZATION_TOPOLOGY_V1'));
select reality.register_relationship_kind_service_v1('operating_unit_of','Operating unit of','An Organization Unit is a direct operating unit of the canonical parent organization.',null,false,array['organization_unit'],array['business','organization','nonprofit'],jsonb_build_object('coreContract','ATLAS_REALITY_ORGANIZATION_TOPOLOGY_V1','sourceClass','canonical_internal_structure'));
select reality.register_relationship_kind_service_v1('operating_unit_parent','Operating unit parent','A child Organization Unit is directly contained by its parent Organization Unit.',null,false,array['organization_unit'],array['organization_unit'],jsonb_build_object('coreContract','ATLAS_REALITY_ORGANIZATION_TOPOLOGY_V1','sourceClass','canonical_internal_structure'));
select reality.register_relationship_kind_service_v1('location_of','Location of','The subject is a distinct operating location of the parent organization.',null,false,array['business','organization','nonprofit','place'],array['business','organization','nonprofit'],jsonb_build_object('coreContract','ATLAS_REALITY_ORGANIZATION_TOPOLOGY_V1','sharedIntelligenceRelationshipKind','location_of'));
select reality.register_relationship_kind_service_v1('branch_of','Branch of','The subject is a local or operating branch of the parent organization.',null,false,array['business','organization','nonprofit'],array['business','organization','nonprofit'],jsonb_build_object('coreContract','ATLAS_REALITY_ORGANIZATION_TOPOLOGY_V1','sharedIntelligenceRelationshipKind','branch_of'));
select reality.register_relationship_kind_service_v1('department_of','Department of','The subject is an internal department or division of the parent organization.',null,false,array['business','organization','nonprofit'],array['business','organization','nonprofit'],jsonb_build_object('coreContract','ATLAS_REALITY_ORGANIZATION_TOPOLOGY_V1','sharedIntelligenceRelationshipKind','department_of'));
select reality.register_relationship_kind_service_v1('clinic_of','Clinic of','The subject clinic is part of the parent health system or practice group.',null,false,array['business','organization','nonprofit'],array['business','organization','nonprofit'],jsonb_build_object('coreContract','ATLAS_REALITY_ORGANIZATION_TOPOLOGY_V1','sharedIntelligenceRelationshipKind','clinic_of'));
select reality.register_relationship_kind_service_v1('school_of','School of','The subject school is part of the parent district or educational system.',null,false,array['organization'],array['organization'],jsonb_build_object('coreContract','ATLAS_REALITY_ORGANIZATION_TOPOLOGY_V1','sharedIntelligenceRelationshipKind','school_of'));
select reality.register_relationship_topology_semantics_service_v1('operating_unit_of','operating_structure',true,'subject_to_object',true,true,'direct_operating_presence',jsonb_build_object('coreContract','ATLAS_REALITY_ORGANIZATION_TOPOLOGY_V1'));
select reality.register_relationship_topology_semantics_service_v1('operating_unit_parent','operating_structure',true,'subject_to_object',true,true,'direct_operating_presence',jsonb_build_object('coreContract','ATLAS_REALITY_ORGANIZATION_TOPOLOGY_V1'));
select reality.register_relationship_topology_semantics_service_v1('location_of','operating_structure',true,'subject_to_object',true,true,'direct_operating_presence',jsonb_build_object('coreContract','ATLAS_REALITY_ORGANIZATION_TOPOLOGY_V1'));
select reality.register_relationship_topology_semantics_service_v1('branch_of','operating_structure',true,'subject_to_object',true,true,'direct_operating_presence',jsonb_build_object('coreContract','ATLAS_REALITY_ORGANIZATION_TOPOLOGY_V1'));
select reality.register_relationship_topology_semantics_service_v1('department_of','operating_structure',true,'subject_to_object',true,true,'direct_operating_presence',jsonb_build_object('coreContract','ATLAS_REALITY_ORGANIZATION_TOPOLOGY_V1'));
select reality.register_relationship_topology_semantics_service_v1('clinic_of','operating_structure',true,'subject_to_object',true,true,'direct_operating_presence',jsonb_build_object('coreContract','ATLAS_REALITY_ORGANIZATION_TOPOLOGY_V1'));
select reality.register_relationship_topology_semantics_service_v1('school_of','operating_structure',true,'subject_to_object',true,true,'direct_operating_presence',jsonb_build_object('coreContract','ATLAS_REALITY_ORGANIZATION_TOPOLOGY_V1'));