with farm as (select id from atlas.farms where stable_key='elm_farm' limit 1)
insert into atlas.capacity_measurements(farm_id,stable_key,label,measurement_kind,value,unit,confidence,note,metadata)
select id,'snapdragon_rows_per_three_foot_bed','Snapdragon rows per 3-foot bed','rows_per_bed',9,'rows','confirmed','4x4 single-stem commercial cut-flower spacing.',jsonb_build_object('source_title','Johnny''s Selected Seeds — Snapdragon Production','spacing_system','4x4_single_stem_unpinched','source_checked_on','2026-08-29') from farm
union all
select id,'snapdragon_in_row_spacing_inches','Snapdragon in-row spacing','spacing_inches',4,'inches','confirmed','4x4 single-stem commercial cut-flower spacing.',jsonb_build_object('source_title','Johnny''s Selected Seeds — Snapdragon Production','spacing_system','4x4_single_stem_unpinched','source_checked_on','2026-08-29') from farm
on conflict(farm_id,stable_key) do update set measurement_kind=excluded.measurement_kind,value=excluded.value,unit=excluded.unit,confidence=excluded.confidence,note=excluded.note,metadata=atlas.capacity_measurements.metadata||excluded.metadata,updated_at=now();

update atlas.crop_profiles set rows_per_3ft_bed=9,in_row_spacing_in=4,plants_per_sqft=9,expected_stems_per_plant=1,metadata=coalesce(metadata,'{}'::jsonb)||jsonb_build_object('spacing_source','Johnny''s Selected Seeds — Snapdragon Production','spacing_system','4x4_single_stem_unpinched','spacing_verified_on','2026-08-29'),updated_at=now() where stable_key in ('snapdragon_chantilly_overwinter_2026','snapdragon_first_lady_overwinter_2026','snapdragon_potomac_overwinter_2026','snapdragon_rocket_overwinter_2026');

with farm as (select id from atlas.farms where stable_key='elm_farm' limit 1), src as (
select cp.id crop_profile_id,cp.stable_key profile_key,case cp.stable_key when 'snapdragon_chantilly_overwinter_2026' then 'Chantilly overwinter 2026 → BW1–BW3' when 'snapdragon_first_lady_overwinter_2026' then 'First Lady overwinter 2026 → BW1–BW3' when 'snapdragon_potomac_overwinter_2026' then 'Potomac Berry Blend overwinter 2026 → BW1–BW3' when 'snapdragon_rocket_overwinter_2026' then 'Rocket Mix overwinter 2026 → BW1–BW3' end plan_label from atlas.crop_profiles cp where cp.stable_key in ('snapdragon_chantilly_overwinter_2026','snapdragon_first_lady_overwinter_2026','snapdragon_potomac_overwinter_2026','snapdragon_rocket_overwinter_2026'))
insert into atlas.production_plans(farm_id,crop_profile_id,stable_key,season_year,plan_label,plan_kind,first_window_start,succession_count,spacing_days,window_length_days,late_window_days,skip_threshold_days,missed_strategy,intended_uses,protect_final_succession,active,notes,metadata)
select f.id,s.crop_profile_id,s.profile_key||'_transplant_plan',2026,s.plan_label,'transplant_existing_cohort',date '2026-09-15',1,0,6,0,0,'preserve',array['cut_flower','overwintered_cohort']::text[],true,true,'Current overwintered snapdragon cohort assigned to Berry Walk Beds 1–3.',jsonb_build_object('source_path','/Lex/Atlas/Elm Farm 2027 Bed and Crop Plan - Working Property Checkpoint - 2026-08-28.md','destination_program','BW1-BW3','planning_bed_length_ft',20,'spacing','4x4') from farm f cross join src s
on conflict(farm_id,stable_key,season_year) do update set crop_profile_id=excluded.crop_profile_id,plan_label=excluded.plan_label,plan_kind=excluded.plan_kind,first_window_start=excluded.first_window_start,window_length_days=excluded.window_length_days,intended_uses=excluded.intended_uses,active=true,notes=excluded.notes,metadata=atlas.production_plans.metadata||excluded.metadata,updated_at=now();

with farm as (select id from atlas.farms where stable_key='elm_farm' limit 1), cp as (select id from atlas.crop_profiles where stable_key='snow_in_summer' limit 1)
insert into atlas.production_plans(farm_id,crop_profile_id,stable_key,season_year,plan_label,plan_kind,first_window_start,succession_count,spacing_days,window_length_days,late_window_days,skip_threshold_days,missed_strategy,intended_uses,protect_final_succession,active,notes,metadata)
select f.id,cp.id,'snow_in_summer_2026_use_allocation',2026,'Snow in Summer 2026 — landscape + workshop gifts','perennial_use_allocation',date '2026-09-01',1,0,45,0,0,'preserve',array['landscaping','workshop_gift_material']::text[],true,true,'One full tray reserved for workshop/event gifting; remaining non-spiral plants reserved for Elm landscaping.',jsonb_build_object('owner_direction_date','2026-08-29','source_path','/Lex/Atlas/Elm Farm 2027 Bed and Crop Plan - Working Property Checkpoint - 2026-08-28.md') from farm f cross join cp
on conflict(farm_id,stable_key,season_year) do update set intended_uses=excluded.intended_uses,active=true,notes=excluded.notes,metadata=atlas.production_plans.metadata||excluded.metadata,updated_at=now();

update atlas.production_lots pl set production_plan_id=pp.id,metadata=coalesce(pl.metadata,'{}'::jsonb)||jsonb_build_object('destination_program','BW1-BW3','plan_source','owner_checkpoint_2026-08-28'),updated_at=now() from atlas.production_plans pp,atlas.crop_profiles cp where pl.crop_profile_id=cp.id and pp.crop_profile_id=cp.id and pp.farm_id=pl.farm_id and pp.season_year=2026 and pp.stable_key=cp.stable_key||'_transplant_plan' and pl.stable_key in ('snapdragon_chantilly_overwinter_2026_live','snapdragon_first_lady_overwinter_2026_live','snapdragon_potomac_overwinter_2026_live','snapdragon_rocket_overwinter_2026_live');
update atlas.production_lots pl set production_plan_id=pp.id,intended_uses=array['landscaping','workshop_gift_material']::text[],metadata=coalesce(pl.metadata,'{}'::jsonb)||jsonb_build_object('use_allocation_owner_confirmed_on','2026-08-29'),updated_at=now() from atlas.production_plans pp where pl.stable_key='snow_in_summer_2026_potted_cohort' and pp.farm_id=pl.farm_id and pp.stable_key='snow_in_summer_2026_use_allocation' and pp.season_year=2026;

update atlas.production_capacity_requirements r set quantity_needed=case pl.stable_key when 'snapdragon_chantilly_overwinter_2026_live' then 8 when 'snapdragon_first_lady_overwinter_2026_live' then 13 when 'snapdragon_potomac_overwinter_2026_live' then 12 when 'snapdragon_rocket_overwinter_2026_live' then 27 end,calculation_status='calculated',preparation_due_date=date '2026-09-14',metadata=coalesce(r.metadata,'{}'::jsonb)||jsonb_build_object('quantity_basis','current_count_provisional','rows_per_three_foot_bed',9,'in_row_spacing_inches',4,'recalculate_on_readiness',true,'planning_bed_length_ft',20),updated_at=now() from atlas.production_lots pl where pl.id=r.production_lot_id and pl.stable_key in ('snapdragon_chantilly_overwinter_2026_live','snapdragon_first_lady_overwinter_2026_live','snapdragon_potomac_overwinter_2026_live','snapdragon_rocket_overwinter_2026_live') and r.capacity_kind='bed_feet';

with specs(lot_key,bed_key,bed_ft,plants) as (values ('snapdragon_rocket_overwinter_2026_live','bw_1',20::numeric,540::numeric),('snapdragon_rocket_overwinter_2026_live','bw_3',7::numeric,180::numeric),('snapdragon_first_lady_overwinter_2026_live','bw_2',12::numeric,324::numeric),('snapdragon_first_lady_overwinter_2026_live','bw_3',1::numeric,6::numeric),('snapdragon_chantilly_overwinter_2026_live','bw_2',8::numeric,210::numeric),('snapdragon_potomac_overwinter_2026_live','bw_3',12::numeric,310::numeric)), farm as (select id from atlas.farms where stable_key='elm_farm' limit 1)
insert into atlas.production_bed_assignments(farm_id,production_lot_id,requirement_id,object_id,quantity_assigned,unit,planned_transplant_date,assignment_status,source,metadata)
select f.id,pl.id,r.id,go.id,s.bed_ft,'bed_ft',date '2026-09-15','assigned','owner_checkpoint_20260829',jsonb_build_object('planned_seedlings',s.plants,'spacing','4x4','planning_bed_length_ft',20,'window_end','2026-09-20','source_path','/Lex/Atlas/Elm Farm 2027 Bed and Crop Plan - Working Property Checkpoint - 2026-08-28.md') from specs s cross join farm f join atlas.production_lots pl on pl.farm_id=f.id and pl.stable_key=s.lot_key join atlas.production_capacity_requirements r on r.production_lot_id=pl.id and r.capacity_kind='bed_feet' join atlas.growing_objects go on go.farm_id=f.id and go.stable_key=s.bed_key
on conflict(production_lot_id,object_id) where assignment_status='assigned' do update set requirement_id=excluded.requirement_id,quantity_assigned=excluded.quantity_assigned,unit=excluded.unit,planned_transplant_date=excluded.planned_transplant_date,source=excluded.source,metadata=atlas.production_bed_assignments.metadata||excluded.metadata,updated_at=now();

update atlas.production_tray_batches tb set action_required=false,action_key='transplant',action_due_date=date '2026-09-15',destination_object_id=case when pl.stable_key='snapdragon_chantilly_overwinter_2026_live' then (select id from atlas.growing_objects where farm_id=tb.farm_id and stable_key='bw_2') when pl.stable_key='snapdragon_potomac_overwinter_2026_live' then (select id from atlas.growing_objects where farm_id=tb.farm_id and stable_key='bw_3') else null end,action_note=case pl.stable_key when 'snapdragon_rocket_overwinter_2026_live' then 'Transplant at 4×4 in BW1 and BW3: 540 plants / 20 bed-ft in BW1, then remaining 180 plants / 7 bed-ft in BW3. Window Sep 15–20.' when 'snapdragon_first_lady_overwinter_2026_live' then 'Transplant at 4×4 in BW2 and BW3: 324 plants / 12 bed-ft in BW2, then remaining 6 plants / 1 bed-ft in BW3. Window Sep 15–20.' when 'snapdragon_chantilly_overwinter_2026_live' then 'Transplant all 210 at 4×4 in BW2 using 8 bed-ft. Window Sep 15–20.' when 'snapdragon_potomac_overwinter_2026_live' then 'Transplant all 310 at 4×4 in BW3 using 12 bed-ft. Window Sep 15–20.' end,metadata=coalesce(tb.metadata,'{}'::jsonb)||jsonb_build_object('planned_destination_program','BW1-BW3','spacing','4x4_single_stem_unpinched','plan_linked_on','2026-08-29'),updated_at=now() from atlas.production_lots pl where pl.id=tb.production_lot_id and pl.stable_key in ('snapdragon_chantilly_overwinter_2026_live','snapdragon_first_lady_overwinter_2026_live','snapdragon_potomac_overwinter_2026_live','snapdragon_rocket_overwinter_2026_live');

update atlas.production_tray_batches set metadata=coalesce(metadata,'{}'::jsonb)||jsonb_build_object('planned_use','elm_landscaping','owner_direction_date','2026-08-29'),updated_at=now() where id=(select tb.id from atlas.production_tray_batches tb join atlas.production_lots pl on pl.id=tb.production_lot_id where pl.stable_key='snow_in_summer_2026_potted_cohort' and tb.batch_number=1 limit 1);
update atlas.production_tray_batches set action_required=false,action_key='hold_for_workshops_events',action_due_date=null,destination_object_id=null,action_note='Reserve this full 200-plant tray as gifted plant material for Elm workshops and events. Do not allocate to landscaping unless the owner changes this use.',metadata=coalesce(metadata,'{}'::jsonb)||jsonb_build_object('planned_use','workshop_event_gift_material','owner_direction_date','2026-08-29'),updated_at=now() where id=(select tb.id from atlas.production_tray_batches tb join atlas.production_lots pl on pl.id=tb.production_lot_id where pl.stable_key='snow_in_summer_2026_potted_cohort' and tb.batch_number=2 limit 1);
update atlas.production_tray_batches set action_required=false,action_key='landscape_allocation',action_due_date=null,destination_object_id=null,action_note='Reserved for Elm landscaping. Keep in nursery inventory until a specific landscape destination is selected.',metadata=coalesce(metadata,'{}'::jsonb)||jsonb_build_object('planned_use','elm_landscaping','owner_direction_date','2026-08-29'),updated_at=now() where id in (select tb.id from atlas.production_tray_batches tb join atlas.production_lots pl on pl.id=tb.production_lot_id where pl.stable_key='snow_in_summer_2026_potted_cohort' and tb.batch_number in (3,4));