-- Reality Alignment substrate v1
-- One observed reality coordinate space; many intact witnesses; explicit bridges.

create table if not exists draft.reality_witness_registry (
  witness_key text primary key,
  witness_name text not null,
  witness_kind text not null,
  native_domain text,
  source_object_type text,
  source_object_id text,
  source_role text,
  provenance_status text not null default 'registered',
  is_active boolean not null default true,
  notes text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on table draft.reality_witness_registry is
'Registry of sources, frameworks, instruments, corpora, practitioners, reports, and other witnesses that can contribute objects to one Reality Alignment space. Witness identity is preserved; registration does not merge witness ontologies.';

create unique index if not exists reality_witness_registry_source_uq
on draft.reality_witness_registry(source_object_type,source_object_id)
where source_object_type is not null and source_object_id is not null;

create table if not exists draft.reality_occurrences (
  occurrence_id bigint generated by default as identity primary key,
  occurrence_key text not null unique,
  occurrence_kind text not null,
  subject_ref_type text,
  subject_ref text,
  occurred_at timestamptz,
  captured_by_witness_key text references draft.reality_witness_registry(witness_key)
    on update cascade on delete set null,
  raw_summary text,
  raw_payload jsonb not null default '{}'::jsonb,
  occurrence_status text not null default 'captured',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on table draft.reality_occurrences is
'An occurrence is the shared reality anchor around which multiple witnesses may align. It is not owned by any medical, spiritual, mechanical, emotional, or other disciplinary ontology.';

create table if not exists draft.reality_occurrence_coordinates (
  occurrence_coordinate_id bigint generated by default as identity primary key,
  occurrence_id bigint not null references draft.reality_occurrences(occurrence_id)
    on update cascade on delete cascade,
  coordinate_group_key text not null default 'root',
  dimension_key text not null references draft.reality_query_dimension_registry(dimension_key)
    on update cascade on delete restrict,
  dimension_value text not null,
  normalized_value text not null,
  coordinate_role text not null default 'feature',
  coordinate_order integer not null default 0,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on table draft.reality_occurrence_coordinates is
'Coordinate spine for an observed occurrence. Coordinates preserve local grouping independently of any witness explanation.';

create unique index if not exists reality_occurrence_coordinates_uq
on draft.reality_occurrence_coordinates(
  occurrence_id,coordinate_group_key,dimension_key,normalized_value
);

create index if not exists reality_occurrence_coordinates_lookup_idx
on draft.reality_occurrence_coordinates(dimension_key,normalized_value,occurrence_id);

create table if not exists draft.reality_alignment_segments (
  alignment_segment_id bigint generated by default as identity primary key,
  alignment_key text not null unique,
  occurrence_id bigint not null references draft.reality_occurrences(occurrence_id)
    on update cascade on delete cascade,
  alignment_kind text not null,
  relation_type text not null,
  alignment_status text not null default 'working',
  resolution_confidence text,
  review_status text not null default 'unreviewed',
  source_basis text,
  notes text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on table draft.reality_alignment_segments is
'First-class bridge between an observed reality occurrence and one or more witness-native objects. The segment records contact/alignment without requiring object identity or ontology equivalence.';

create index if not exists reality_alignment_segments_occurrence_idx
on draft.reality_alignment_segments(occurrence_id,alignment_kind,relation_type);

create table if not exists draft.reality_alignment_members (
  alignment_member_id bigint generated by default as identity primary key,
  alignment_segment_id bigint not null references draft.reality_alignment_segments(alignment_segment_id)
    on update cascade on delete cascade,
  side text not null,
  witness_key text references draft.reality_witness_registry(witness_key)
    on update cascade on delete restrict,
  occurrence_coordinate_id bigint references draft.reality_occurrence_coordinates(occurrence_coordinate_id)
    on update cascade on delete cascade,
  object_type text,
  object_id text,
  member_role text not null,
  member_order integer not null default 0,
  resolution_status text not null default 'working',
  source_locator text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint reality_alignment_members_side_check check (side in ('reality','witness')),
  constraint reality_alignment_members_shape_check check (
    (side='reality' and occurrence_coordinate_id is not null)
    or
    (side='witness' and witness_key is not null and object_type is not null and object_id is not null)
  )
);

comment on table draft.reality_alignment_members is
'Members of a Reality Alignment segment. Reality-side members point to occurrence coordinates; witness-side members point to native source objects and retain witness identity. One-to-one, one-to-many, many-to-one, and many-to-many alignments are all representable.';

create unique index if not exists reality_alignment_members_uq
on draft.reality_alignment_members(
  alignment_segment_id,
  side,
  coalesce(witness_key,''),
  coalesce(occurrence_coordinate_id,0),
  coalesce(object_type,''),
  coalesce(object_id,''),
  member_role
);

create index if not exists reality_alignment_members_coordinate_idx
on draft.reality_alignment_members(occurrence_coordinate_id)
where occurrence_coordinate_id is not null;

create index if not exists reality_alignment_members_object_idx
on draft.reality_alignment_members(object_type,object_id)
where object_type is not null and object_id is not null;

create table if not exists draft.reality_alignment_residue_registry (
  residue_id bigint generated by default as identity primary key,
  occurrence_id bigint not null references draft.reality_occurrences(occurrence_id)
    on update cascade on delete cascade,
  occurrence_coordinate_id bigint references draft.reality_occurrence_coordinates(occurrence_coordinate_id)
    on update cascade on delete cascade,
  witness_key text references draft.reality_witness_registry(witness_key)
    on update cascade on delete set null,
  residue_class text not null,
  disposition text not null default 'hold',
  residue_status text not null default 'open',
  notes text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on table draft.reality_alignment_residue_registry is
'Explicit registry for coordinates or witness material not accounted for by current alignments. Residue is preserved as information rather than forced into an existing explanation.';

create unique index if not exists reality_alignment_residue_uq
on draft.reality_alignment_residue_registry(
  occurrence_id,
  coalesce(occurrence_coordinate_id,0),
  coalesce(witness_key,''),
  residue_class
);

insert into draft.reality_witness_registry
(witness_key,witness_name,witness_kind,native_domain,source_object_type,source_object_id,source_role,provenance_status,is_active,metadata)
select
  'framework:'||f.framework_key,
  f.framework_name,
  'framework',
  f.framework_family,
  'reality_framework',
  f.framework_key,
  f.framework_kind,
  f.framework_status,
  true,
  jsonb_build_object('source_table','draft.reality_frameworks')
from draft.reality_frameworks f
on conflict (witness_key) do update set
  witness_name=excluded.witness_name,
  witness_kind=excluded.witness_kind,
  native_domain=excluded.native_domain,
  source_object_type=excluded.source_object_type,
  source_object_id=excluded.source_object_id,
  source_role=excluded.source_role,
  provenance_status=excluded.provenance_status,
  is_active=excluded.is_active,
  metadata=excluded.metadata,
  updated_at=now();

with j as (
  select source_jurisdiction,min(source_domain) source_domain
  from intelligence.v_universal_vocabulary_index_v1
  where framework_key is null
  group by source_jurisdiction
)
insert into draft.reality_witness_registry
(witness_key,witness_name,witness_kind,native_domain,source_role,provenance_status,is_active,metadata)
select
  'jurisdiction:'||j.source_jurisdiction,
  case
    when j.source_jurisdiction='neutral_anatomy' then 'Anatomy'
    when j.source_jurisdiction='neutral_observation' then 'Observed phenomena'
    when j.source_jurisdiction='canon_vocabulary' then 'Canon vocabulary'
    when j.source_jurisdiction='noel_function' then 'Noel functions'
    when j.source_jurisdiction='cross_domain_term' then 'Cross-domain terms'
    when j.source_jurisdiction='practitioner_vocabulary' then 'Practitioner vocabulary'
    when j.source_jurisdiction='song' then 'Song'
    when j.source_jurisdiction='research_claim' then 'Research claims'
    when j.source_jurisdiction='celestial_research_hypothesis' then 'Celestial research'
    else initcap(replace(j.source_jurisdiction,'_',' '))
  end,
  'source_jurisdiction',
  j.source_domain,
  j.source_jurisdiction,
  'registered',
  true,
  jsonb_build_object('source_view','intelligence.v_universal_vocabulary_index_v1')
from j
on conflict (witness_key) do update set
  witness_name=excluded.witness_name,
  witness_kind=excluded.witness_kind,
  native_domain=excluded.native_domain,
  source_role=excluded.source_role,
  is_active=excluded.is_active,
  metadata=excluded.metadata,
  updated_at=now();

insert into draft.reality_witness_registry
(witness_key,witness_name,witness_kind,native_domain,source_role,provenance_status,is_active,metadata)
values
('observation:human_report','Human report','direct_observation','human_experience','reported_observation','registered',true,
 '{"purpose":"capture what a person reports before framework interpretation"}'::jsonb)
on conflict (witness_key) do nothing;

alter table draft.reality_witness_registry enable row level security;
alter table draft.reality_occurrences enable row level security;
alter table draft.reality_occurrence_coordinates enable row level security;
alter table draft.reality_alignment_segments enable row level security;
alter table draft.reality_alignment_members enable row level security;
alter table draft.reality_alignment_residue_registry enable row level security;

revoke all on draft.reality_witness_registry from anon,authenticated;
revoke all on draft.reality_occurrences from anon,authenticated;
revoke all on draft.reality_occurrence_coordinates from anon,authenticated;
revoke all on draft.reality_alignment_segments from anon,authenticated;
revoke all on draft.reality_alignment_members from anon,authenticated;
revoke all on draft.reality_alignment_residue_registry from anon,authenticated;

grant select,insert,update,delete on draft.reality_witness_registry to service_role;
grant select,insert,update,delete on draft.reality_occurrences to service_role;
grant select,insert,update,delete on draft.reality_occurrence_coordinates to service_role;
grant select,insert,update,delete on draft.reality_alignment_segments to service_role;
grant select,insert,update,delete on draft.reality_alignment_members to service_role;
grant select,insert,update,delete on draft.reality_alignment_residue_registry to service_role;
grant usage,select on all sequences in schema draft to service_role;
