with farm as (select id from atlas.farms where stable_key='elm_farm' limit 1), specs(object_key,content_label,content_type,variety,note,source_key) as (
  values
    ('asparagus_1','Asparagus','perennial',null,'Established asparagus bed.','owner_measurement_20260716'),
    ('asparagus_2','Asparagus','perennial',null,'Established asparagus bed.','owner_measurement_20260716'),
    ('asparagus_3','Asparagus','perennial',null,'Established asparagus bed.','owner_measurement_20260716'),
    ('asparagus_4','Asparagus','perennial',null,'Established asparagus bed.','owner_measurement_20260716'),
    ('front_porch_foundation_bed','Mature evergreens','perennial',null,'Established foundation evergreens; exact species inventory remains under assessment.','front_porch_object_metadata'),
    ('front_porch_foundation_bed','Liriope','perennial',null,'Established liriope edging.','front_porch_object_metadata'),
    ('garage_west_corner_spirea','Spirea','perennial shrub','cultivar unknown','Mature spirea shrubs recovering from severe pruning.','garage_exterior_photo_truth_pass_20260712'),
    ('south_lawn_round_island','Crape myrtle','perennial shrub',null,'Offshoot from Janice''s original crape myrtle.','south_lawn_object_inventory'),
    ('south_lawn_round_island','Purple spiderwort','perennial',null,'Established legacy perennial.','south_lawn_object_inventory'),
    ('south_lawn_round_island','Irises','perennial',null,'Established legacy irises.','south_lawn_object_inventory'),
    ('south_lawn_round_island','Primroses','perennial',null,'Established legacy primroses.','south_lawn_object_inventory')
)
insert into atlas.object_contents(farm_id,object_id,content_label,content_type,variety,status,confidence,note,metadata)
select f.id,go.id,s.content_label,s.content_type,s.variety,'planted','confirmed',s.note,jsonb_build_object('source',s.source_key,'reconciled_on','2026-08-29')
from farm f join specs s on true join atlas.growing_objects go on go.farm_id=f.id and go.stable_key=s.object_key
where not exists(select 1 from atlas.object_contents oc where oc.object_id=go.id and lower(oc.content_label)=lower(s.content_label) and coalesce(oc.status,'') not in ('removed','dead','cleared','archived'));

with farm as (select id from atlas.farms where stable_key='elm_farm' limit 1), inv as (
  select object_id,crop_label||coalesce(' · '||nullif(variety,''),'') label from atlas.crop_cycles where farm_id=(select id from farm) and lifecycle_status='active' and cleared_date is null and turnover_date is null
  union all
  select object_id,content_label||coalesce(' · '||nullif(variety,''),'') label from atlas.object_contents where farm_id=(select id from farm) and coalesce(status,'') not in ('removed','dead','cleared','archived')
), agg as (select object_id,string_agg(distinct label,'; ' order by label) inventory from inv group by object_id)
update atlas.object_state os
set operational_truth=case when os.operational_truth is null or btrim(os.operational_truth)='' then 'Occupied: '||a.inventory else os.operational_truth end,
    operational_truth_source=case when os.operational_truth is null or btrim(os.operational_truth)='' then 'current_crop_inventory_reconciliation' else os.operational_truth_source end,
    operational_truth_changed_at=case when os.operational_truth is null or btrim(os.operational_truth)='' then now() else os.operational_truth_changed_at end,
    metadata=coalesce(os.metadata,'{}'::jsonb)||jsonb_build_object('occupancy_state','occupied','current_inventory_summary',a.inventory,'current_inventory_reconciled_at',now()),
    updated_at=now()
from agg a join atlas.growing_objects go on go.id=a.object_id
where os.object_id=a.object_id and go.object_type in ('bed','arch_bed');

update atlas.object_state os set operational_truth='No active crop. Empty except weeds/dead sprayed biomass. Existing reset chain must inspect regrowth: re-spray if green; otherwise clear dead material and prepare the bed.',operational_truth_source='owner_truth_20260829',operational_truth_changed_at=now(),decision_required=true,metadata=coalesce(os.metadata,'{}'::jsonb)||jsonb_build_object('occupancy_state','empty_reset_required','crop_occupancy','confirmed_empty','reset_chain_key','entry_billboard_reset_daily_v1','owner_truth_date','2026-08-29'),updated_at=now() from atlas.growing_objects go where os.object_id=go.id and go.farm_id=(select id from atlas.farms where stable_key='elm_farm' limit 1) and go.stable_key in ('eb_sunflower_1','eb_sunflower_2','eb_sunflower_3','eb_sunflower_4','eb_sunflower_5','eb_sunflower_6');

update atlas.object_state os set operational_truth='Not yet a usable bed. Wood pieces are laid out in a square where this bed will be installed; construction is blocked until Marshall is at Elm with cutting capability and repair materials.',operational_truth_source='owner_truth_20260829',operational_truth_changed_at=now(),decision_required=true,metadata=coalesce(os.metadata,'{}'::jsonb)||jsonb_build_object('occupancy_state','not_built','physical_frame_state','wood_pieces_laid_out','capability_blocker','marshall_at_elm_with_cutting_capability','repair_task_id','d256f453-c5fc-4562-8c9b-ab3fc5ee22e2','owner_truth_date','2026-08-29'),updated_at=now() from atlas.growing_objects go where os.object_id=go.id and go.farm_id=(select id from atlas.farms where stable_key='elm_farm' limit 1) and go.stable_key in ('curve_arch_03_left_bed','curve_arch_03_right_bed');

update atlas.object_state os set operational_truth='Managed salvage / non-production state. Severe weeds dominate; only a few visible sunflower islands may remain. Do not count this as a productive crop stand. Hold for planned fall tillage.',operational_truth_source='u_pick_management_plan_20260722',operational_truth_changed_at=now(),metadata=coalesce(os.metadata,'{}'::jsonb)||jsonb_build_object('occupancy_state','managed_salvage_nonproduction','productive_crop_stand',false,'fall_tillage_planned',true),updated_at=now() from atlas.growing_objects go where os.object_id=go.id and go.farm_id=(select id from atlas.farms where stable_key='elm_farm' limit 1) and go.stable_key like 'u_pick_bed_%';

update atlas.object_state os set operational_truth='No active crop is recorded. Bed is reserved for florist tulips / cottage succession; physical occupancy must remain clear before fall planting.',operational_truth_source='berry_walk_rail_tie_plan',operational_truth_changed_at=now(),metadata=coalesce(os.metadata,'{}'::jsonb)||jsonb_build_object('occupancy_state','reserved_no_active_crop','planned_use','florist tulips / cottage succession'),updated_at=now() from atlas.growing_objects go where os.object_id=go.id and go.farm_id=(select id from atlas.farms where stable_key='elm_farm' limit 1) and go.stable_key in ('berry_walk_rail_tie_bed_north','berry_walk_rail_tie_bed_south');

update atlas.object_state os set operational_truth='Planned destination: Snow in Summer Tray 1, 200 plants. Current bed is still in preparation/planning state with high weeds; do not treat the planting as physically completed until the transplant task is recorded done.',operational_truth_source='snow_in_summer_plan_20260829',operational_truth_changed_at=now(),decision_required=true,metadata=coalesce(os.metadata,'{}'::jsonb)||jsonb_build_object('occupancy_state','planned_destination','planned_crop','Snow in Summer','planned_quantity',200,'planned_unit','plants','physical_planting_complete',false),updated_at=now() from atlas.growing_objects go where os.object_id=go.id and go.farm_id=(select id from atlas.farms where stable_key='elm_farm' limit 1) and go.stable_key='berry_walk_spiral_perennial_pockets';

update atlas.object_state os set operational_truth='Permanent Entry Billboard perennial strip. The bed is confirmed to exist and is maintained, but the exact current perennial inventory has not yet been mapped into Atlas.',operational_truth_source='entry_billboard_perennial_strip_owner_confirmation',operational_truth_changed_at=now(),decision_required=true,metadata=coalesce(os.metadata,'{}'::jsonb)||jsonb_build_object('occupancy_state','perennial_inventory_incomplete','inventory_mapping_required',true),updated_at=now() from atlas.growing_objects go where os.object_id=go.id and go.farm_id=(select id from atlas.farms where stable_key='elm_farm' limit 1) and go.stable_key='entry_billboard_perennial_strip';

update atlas.object_state os set operational_truth='Physical state requires reconciliation. Atlas still has Weed MG2 open and has no recorded MG2 planting, crop-cycle creation, activity event, field log, or task transition from tonight. Do not assume empty and do not assume planted until the actual work is confirmed.',operational_truth_source='atlas_evidence_gap_20260829',operational_truth_changed_at=now(),decision_required=true,metadata=coalesce(os.metadata,'{}'::jsonb)||jsonb_build_object('occupancy_state','physical_reconciliation_required','owner_report','Anna may have weeded and planted fall crops tonight','atlas_execution_evidence_found',false,'reconciliation_date','2026-08-29'),updated_at=now() from atlas.growing_objects go where os.object_id=go.id and go.farm_id=(select id from atlas.farms where stable_key='elm_farm' limit 1) and go.stable_key='mg2';

update atlas.tasks t set metadata=coalesce(t.metadata,'{}'::jsonb)||jsonb_build_object('physical_truth_reconciliation_required',true,'reconciliation_reason','Owner reports Anna may have weeded/planted MG2, but Atlas has no execution evidence. Confirm actual work before completing or superseding this task.','reconciliation_flagged_on','2026-08-29'),updated_at=now() from atlas.task_objects x join atlas.growing_objects go on go.id=x.object_id where t.id=x.task_id and go.farm_id=(select id from atlas.farms where stable_key='elm_farm' limit 1) and go.stable_key='mg2' and t.status in ('open','blocked') and t.title='Weed MG2';

update atlas.object_state os set operational_truth='No active crop inventory is linked. Physical occupancy must be verified before this bed is treated as empty, plantable, or assigned a crop.',operational_truth_source='bed_truth_closure_audit_20260829',operational_truth_changed_at=now(),decision_required=true,metadata=coalesce(os.metadata,'{}'::jsonb)||jsonb_build_object('occupancy_state','verification_required','inventory_mapping_required',true),updated_at=now() from atlas.growing_objects go where os.object_id=go.id and go.farm_id=(select id from atlas.farms where stable_key='elm_farm' limit 1) and go.object_type in ('bed','arch_bed') and (os.operational_truth is null or btrim(os.operational_truth)='');