do $block$
declare v_work_id uuid; v_creator_id uuid; v_title text; v_author text; r record;
begin
  select e.work_id,w.canonical_label into v_work_id,v_title
  from wnph.expressions e join wnph.historical_works w on w.id=e.work_id
  where e.canonical_key='wish-fairy-dewy-dear:wnph-publication-e1';
  select id,preferred_label into v_creator_id,v_author from wnph.creator_authorities where canonical_key='alice-ross-colver' and status='established' order by created_at desc limit 1;
  if v_work_id is null or v_creator_id is null then raise exception 'WNPH Dewy front matter: governed Work or creator authority missing' using errcode='P0002'; end if;

  if not exists(select 1 from wnph.work_creator_credits c where c.work_id=v_work_id and c.creator_id=v_creator_id and c.role='author' and not exists(select 1 from wnph.work_creator_credits x where x.supersedes_credit_id=c.id)) then
    insert into wnph.work_creator_credits(work_id,creator_id,role,credit_status,notes)
    values(v_work_id,v_creator_id,'author','established','Library of Congress LCCN 22008427 identifies Alice Ross Colver as creator; title-page OCR “ALICE ROSSTOLVER” is not used as bibliographic authority.');
  end if;

  perform public.wnph_record_publication_expression_block_v2('wish-fairy-dewy-dear:wnph-publication-e1','dewy:publication-expression:front-matter:v1','wnph:dewy:front-matter',null,0,'section_group','front_matter',null,'admitted','structural_adjudication',0.99,'wnph_publication_front_matter_structure_v1',array['dewy:front-matter'],'[]'::jsonb,jsonb_build_object('publication_admission',true,'publication_expression_only',true,'source_image_verification_required',false,'canonical_admission',false,'front_matter_semantic_structure',true),null);

  perform public.wnph_record_publication_expression_block_v2('wish-fairy-dewy-dear:wnph-publication-e1','dewy:publication-expression:title-page:v1','wnph:dewy:front-matter:title-page','wnph:dewy:front-matter',1,'front_matter_component','title_page',null,'admitted','structural_adjudication',0.99,'wnph_publication_front_matter_structure_v1',array['dewy:title-page'],'[]'::jsonb,jsonb_build_object('publication_admission',true,'publication_expression_only',true,'source_image_verification_required',false,'canonical_admission',false,'generated_from_bibliographic_authority',true),null);

  perform public.wnph_record_publication_expression_block_v2('wish-fairy-dewy-dear:wnph-publication-e1','dewy:publication-expression:title-page:title:v1','wnph:dewy:front-matter:title-page:title','wnph:dewy:front-matter:title-page',1,'heading','title',v_title,'admitted','structural_adjudication',0.99,'wnph_publication_bibliographic_authority_v1',array['dewy:title-page'],jsonb_build_array(jsonb_build_object('source_key','loc:item:22008427','evidence_role','source_repository','notes','Library of Congress bibliographic authority for Work title.')),jsonb_build_object('publication_admission',true,'publication_expression_only',true,'source_image_verification_required',false,'canonical_admission',false,'authority_source','historical_work.canonical_label'),null);

  perform public.wnph_record_publication_expression_block_v2('wish-fairy-dewy-dear:wnph-publication-e1','dewy:publication-expression:title-page:author:v1','wnph:dewy:front-matter:title-page:author','wnph:dewy:front-matter:title-page',2,'credit','author',v_author,'admitted','structural_adjudication',0.99,'wnph_publication_bibliographic_authority_v1',array['dewy:title-page'],jsonb_build_array(jsonb_build_object('source_key','loc:item:22008427','evidence_role','source_repository','notes','Library of Congress LCCN 22008427 identifies Alice Ross Colver as creator.')),jsonb_build_object('publication_admission',true,'publication_expression_only',true,'source_image_verification_required',false,'canonical_admission',false,'authority_source','creator_authorities/work_creator_credits','ocr_misread_rejected','ALICE ROSSTOLVER'),null);

  perform public.wnph_record_publication_expression_block_v2('wish-fairy-dewy-dear:wnph-publication-e1','dewy:publication-expression:rights-page:v1','wnph:dewy:front-matter:rights-page','wnph:dewy:front-matter',2,'front_matter_component','edition_rights_page',null,'admitted','structural_adjudication',0.99,'wnph_publication_front_matter_structure_v1',array['dewy:copyright-page'],'[]'::jsonb,jsonb_build_object('publication_admission',true,'publication_expression_only',true,'source_image_verification_required',false,'canonical_admission',false,'generated_from_rights_authority',true,'underlying_work_status','public_domain','historical_1922_copyright_page_is_source_history_not_current_claim',true),null);

  perform public.wnph_record_publication_expression_block_v2('wish-fairy-dewy-dear:wnph-publication-e1','dewy:publication-expression:toc:v1','wnph:dewy:front-matter:contents','wnph:dewy:front-matter',3,'front_matter_component','table_of_contents',null,'admitted','structural_adjudication',0.99,'wnph_publication_front_matter_structure_v1',array['dewy:contents'],'[]'::jsonb,jsonb_build_object('publication_admission',true,'publication_expression_only',true,'source_image_verification_required',false,'canonical_admission',false,'generated_from_active_chapter_structure',true,'page_numbers_owned_by_paginated_manifestation',true,'digital_navigation_owned_by_reflow_manifestation',true),null);

  perform public.wnph_record_publication_expression_block_v2('wish-fairy-dewy-dear:wnph-publication-e1','dewy:publication-expression:half-title:v1','wnph:dewy:front-matter:half-title','wnph:dewy:front-matter',4,'heading','half_title',v_title,'admitted','structural_adjudication',0.99,'wnph_publication_bibliographic_authority_v1',array['dewy:body-title'],jsonb_build_array(jsonb_build_object('source_key','loc:item:22008427','evidence_role','source_repository')),jsonb_build_object('publication_admission',true,'publication_expression_only',true,'source_image_verification_required',false,'canonical_admission',false,'authority_source','historical_work.canonical_label'),null);

  for r in select * from (values
    (1,'Dewy Dear'),(2,'Roarabout and Wisselit'),(3,'Twinkletoes'),(4,'Silver Nose and Star'),(5,'Bumps'),(6,'Black Face and White Face')
  ) v(chapter_number,chapter_title)
  loop
    perform public.wnph_record_publication_expression_block_v2('wish-fairy-dewy-dear:wnph-publication-e1',format('dewy:publication-expression:chapter%s:title:v1',r.chapter_number),format('wnph:dewy:chapter:%s:title',r.chapter_number),format('wnph:dewy:chapter:%s',r.chapter_number),0,'heading','chapter_title',r.chapter_title,'admitted','structural_adjudication',0.99,'wnph_publication_chapter_title_structure_v1',array[format('dewy:chapter:%s',r.chapter_number)],'[]'::jsonb,jsonb_build_object('publication_admission',true,'publication_expression_only',true,'source_image_verification_required',false,'canonical_admission',false,'generated_from_governed_source_chapter_structure',true),null);
  end loop;

  perform public.wnph_attach_publication_expression_media_v1('wish-fairy-dewy-dear:wnph-publication-e1','dewy:plate:frontispiece','dewy:loc:source-surface:0006','frontispiece',0,'front_matter','wnph:dewy:front-matter',jsonb_build_object('source_pdf_page',6,'printed_position','frontispiece'),jsonb_build_object('preserve_historical_sequence',true,'geometry_owned_by_manifestation',true,'physical_preference','full_page_plate_facing_title_page','reflow_preference','front_matter_figure_before_title_page'),jsonb_build_object('decorative',false,'alt_text_status','pending_editorial_description'),jsonb_build_object('historical_color_plate',true,'source_basis','governed_LOC_IIIF_asset','color_diagnostic','wikimedia-commons:ia:wishfairydewydea00colv:interior-color-plate-diagnostic'),null);
  perform public.wnph_attach_publication_expression_media_v1('wish-fairy-dewy-dear:wnph-publication-e1','dewy:plate:page-9','dewy:loc:source-surface:0013','interior_color_plate',1,'source_surface_boundary',null,jsonb_build_object('after_source_surface','dewy:loc:source-surface:0012','before_source_surface','dewy:loc:source-surface:0014','source_pdf_page',13,'historical_printed_position',9,'chapter_number',1),jsonb_build_object('preserve_historical_sequence',true,'geometry_owned_by_manifestation',true,'physical_preference','full_page_plate_near_historical_boundary','reflow_preference','nearest_semantic_break_after_boundary'),jsonb_build_object('decorative',false,'alt_text_status','pending_editorial_description'),jsonb_build_object('historical_color_plate',true,'source_basis','governed_LOC_IIIF_asset'),null);
  perform public.wnph_attach_publication_expression_media_v1('wish-fairy-dewy-dear:wnph-publication-e1','dewy:plate:page-19','dewy:loc:source-surface:0023','interior_color_plate',2,'source_surface_boundary',null,jsonb_build_object('after_source_surface','dewy:loc:source-surface:0022','before_source_surface','dewy:loc:source-surface:0024','source_pdf_page',23,'historical_printed_position',19,'chapter_number',2),jsonb_build_object('preserve_historical_sequence',true,'geometry_owned_by_manifestation',true,'physical_preference','full_page_plate_near_historical_boundary','reflow_preference','nearest_semantic_break_after_boundary'),jsonb_build_object('decorative',false,'alt_text_status','pending_editorial_description'),jsonb_build_object('historical_color_plate',true,'source_basis','governed_LOC_IIIF_asset'),null);
  perform public.wnph_attach_publication_expression_media_v1('wish-fairy-dewy-dear:wnph-publication-e1','dewy:plate:page-29','dewy:loc:source-surface:0033','interior_color_plate',3,'source_surface_boundary',null,jsonb_build_object('after_source_surface','dewy:loc:source-surface:0032','before_source_surface','dewy:loc:source-surface:0034','source_pdf_page',33,'historical_printed_position',29,'chapter_number',3),jsonb_build_object('preserve_historical_sequence',true,'geometry_owned_by_manifestation',true,'physical_preference','full_page_plate_near_historical_boundary','reflow_preference','nearest_semantic_break_after_boundary'),jsonb_build_object('decorative',false,'alt_text_status','pending_editorial_description'),jsonb_build_object('historical_color_plate',true,'source_basis','governed_LOC_IIIF_asset'),null);
  perform public.wnph_attach_publication_expression_media_v1('wish-fairy-dewy-dear:wnph-publication-e1','dewy:plate:page-37','dewy:loc:source-surface:0041','interior_color_plate',4,'source_surface_boundary',null,jsonb_build_object('after_source_surface','dewy:loc:source-surface:0040','before_source_surface','dewy:loc:source-surface:0042','source_pdf_page',41,'historical_printed_position',37,'chapter_number',4),jsonb_build_object('preserve_historical_sequence',true,'geometry_owned_by_manifestation',true,'physical_preference','full_page_plate_near_historical_boundary','reflow_preference','nearest_semantic_break_after_boundary'),jsonb_build_object('decorative',false,'alt_text_status','pending_editorial_description'),jsonb_build_object('historical_color_plate',true,'source_basis','governed_LOC_IIIF_asset'),null);
  perform public.wnph_attach_publication_expression_media_v1('wish-fairy-dewy-dear:wnph-publication-e1','dewy:plate:page-47','dewy:loc:source-surface:0051','interior_color_plate',5,'source_surface_boundary',null,jsonb_build_object('after_source_surface','dewy:loc:source-surface:0050','before_source_surface','dewy:loc:source-surface:0052','source_pdf_page',51,'historical_printed_position',47,'chapter_number',5),jsonb_build_object('preserve_historical_sequence',true,'geometry_owned_by_manifestation',true,'physical_preference','full_page_plate_near_historical_boundary','reflow_preference','nearest_semantic_break_after_boundary'),jsonb_build_object('decorative',false,'alt_text_status','pending_editorial_description'),jsonb_build_object('historical_color_plate',true,'source_basis','governed_LOC_IIIF_asset'),null);
  perform public.wnph_attach_publication_expression_media_v1('wish-fairy-dewy-dear:wnph-publication-e1','dewy:plate:page-55','dewy:loc:source-surface:0059','interior_color_plate',6,'source_surface_boundary',null,jsonb_build_object('after_source_surface','dewy:loc:source-surface:0058','before_source_surface','dewy:loc:source-surface:0060','source_pdf_page',59,'historical_printed_position',55,'chapter_number',6),jsonb_build_object('preserve_historical_sequence',true,'geometry_owned_by_manifestation',true,'physical_preference','full_page_plate_near_historical_boundary','reflow_preference','nearest_semantic_break_after_boundary'),jsonb_build_object('decorative',false,'alt_text_status','pending_editorial_description'),jsonb_build_object('historical_color_plate',true,'source_basis','governed_LOC_IIIF_asset'),null);
end;
$block$;

insert into wnph.publication_render_profiles(canonical_key,output_family,profile_version,rules,profile_status,notes,supersedes_profile_id)
select replace(p.canonical_key,':v1',':v2'),p.output_family,'2',p.rules||jsonb_build_object('master_snapshot_contract','wnph_publication_expression_snapshot_v2','text_input_view','v_wnph_expression_render_input_v1','media_input_view','v_wnph_expression_media_input_v1','text_and_media_master',true,'geometry_owned_by_manifestation',true),'active',coalesce(p.notes,'')||' v2 adds governed Expression media placements to the master contract.',p.id
from wnph.publication_render_profiles p
where p.canonical_key in ('wnph:render:paperback:v1','wnph:render:print-pdf:v1','wnph:render:epub3:v1','wnph:render:web:v1')
  and not exists(select 1 from wnph.publication_render_profiles c where c.supersedes_profile_id=p.id);

with e as (select id,canonical_key from wnph.expressions where canonical_key='wish-fairy-dewy-dear:wnph-publication-e1'), snap as (select public.wnph_publication_expression_snapshot_v2('wish-fairy-dewy-dear:wnph-publication-e1') s), active_old as (
 select d.*,r.output_family from wnph.publication_manifestation_derivations d join wnph.publication_render_profiles r on r.id=d.render_profile_id,e
 where d.publication_expression_id=e.id and not exists(select 1 from wnph.publication_manifestation_derivations c where c.supersedes_derivation_id=d.id)
), new_profiles as (
 select p.id,p.output_family from wnph.publication_render_profiles p where p.canonical_key in ('wnph:render:paperback:v2','wnph:render:print-pdf:v2','wnph:render:epub3:v2','wnph:render:web:v2')
)
insert into wnph.publication_manifestation_derivations(source_package_id,publication_expression_id,render_profile_id,manifestation_id,derivation_status,build_metadata,supersedes_derivation_id)
select null,d.publication_expression_id,np.id,d.manifestation_id,'planned',coalesce(d.build_metadata,'{}'::jsonb)||jsonb_build_object('master_snapshot',snap.s,'master_authority','publication_expression','text_and_media_master',true,'render_contract_version',2,'profile_upgrade','v1_to_v2_text_and_media','source_image_verification_is_parallel_not_blocking',true,'refreshed_at',now()),d.id
from active_old d join new_profiles np on np.output_family=d.output_family cross join snap;

select public.wnph_refresh_expression_manifestation_derivations_v2('wish-fairy-dewy-dear:wnph-publication-e1');