
create table if not exists draft.reality_motif_registry (
  motif_id bigint generated by default as identity primary key,
  motif_key text not null unique,
  structure_version text not null,
  canonical_signature text not null,
  edge_count integer not null,
  node_count integer not null,
  motif_status text not null default 'candidate',
  notes text,
  metadata jsonb not null default '{}'::jsonb,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint reality_motif_registry_edge_count_check check (edge_count between 2 and 5),
  unique(structure_version,canonical_signature)
);

comment on table draft.reality_motif_registry is
'Registry of label-stripped recurring graph structures recovered from Reality Alignment graphs. A motif is structural form, not an interpretation or domain concept.';

create table if not exists draft.reality_motif_instances (
  motif_instance_id bigint generated by default as identity primary key,
  motif_id bigint not null references draft.reality_motif_registry(motif_id)
    on update cascade on delete cascade,
  occurrence_id bigint not null references draft.reality_occurrences(occurrence_id)
    on update cascade on delete cascade,
  instance_key text not null unique,
  independence_key text not null,
  edge_count integer not null,
  node_count integer not null,
  edge_keys text[] not null,
  node_keys text[] not null,
  coordinate_groups text[] not null default '{}'::text[],
  witness_keys text[] not null default '{}'::text[],
  role_signature text,
  structure jsonb not null,
  instance_status text not null default 'materialized',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(occurrence_id,edge_keys)
);

comment on table draft.reality_motif_instances is
'Concrete appearances of a structural motif inside one Reality Occurrence. Native labels are recoverable through edge/node references but are excluded from the motif canonical signature.';

create index if not exists reality_motif_instances_motif_idx
on draft.reality_motif_instances(motif_id,independence_key);

create index if not exists reality_motif_instances_occurrence_idx
on draft.reality_motif_instances(occurrence_id);

create table if not exists draft.reality_motif_compositions (
  motif_composition_id bigint generated by default as identity primary key,
  parent_motif_id bigint not null references draft.reality_motif_registry(motif_id)
    on update cascade on delete cascade,
  child_motif_id bigint not null references draft.reality_motif_registry(motif_id)
    on update cascade on delete cascade,
  composition_role text not null,
  composition_status text not null default 'candidate',
  evidence_count integer not null default 0,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(parent_motif_id,child_motif_id,composition_role)
);

comment on table draft.reality_motif_compositions is
'Composition graph between recovered motifs. Populated only when larger recurring structures can be shown to contain or compose smaller motifs.';

alter table draft.reality_motif_registry enable row level security;
alter table draft.reality_motif_instances enable row level security;
alter table draft.reality_motif_compositions enable row level security;

revoke all on draft.reality_motif_registry from anon,authenticated;
revoke all on draft.reality_motif_instances from anon,authenticated;
revoke all on draft.reality_motif_compositions from anon,authenticated;

grant select,insert,update,delete on draft.reality_motif_registry to service_role;
grant select,insert,update,delete on draft.reality_motif_instances to service_role;
grant select,insert,update,delete on draft.reality_motif_compositions to service_role;
grant usage,select on all sequences in schema draft to service_role;

update draft.reality_occurrences
set metadata = metadata || jsonb_build_object(
  'independenceKey','proving:head_pressure_dizziness_right_knee_ache_intermittent'
),
updated_at=now()
where occurrence_key in (
  'body_map_proving_head_right_knee_v1',
  'body_map_proving_generic_adapter_v1'
);

create or replace view intelligence.v_reality_alignment_graph_edges_v1
with (security_invoker=true)
as
with counts as (
  select
    s.alignment_segment_id,
    count(*) filter(where m.side='reality')::integer reality_member_count,
    count(*) filter(where m.side='witness')::integer witness_member_count
  from draft.reality_alignment_segments s
  join draft.reality_alignment_members m using(alignment_segment_id)
  group by s.alignment_segment_id
)
select
  s.occurrence_id,
  o.occurrence_key,
  coalesce(o.metadata->>'independenceKey',o.occurrence_key) independence_key,
  'member:'||m.alignment_member_id::text edge_key,
  'reality_touch'::text edge_class,
  'coordinate:'||c.occurrence_coordinate_id::text source_node_key,
  'coordinate'::text source_node_class,
  'coordinate:'||d.dimension_family||':'||c.coordinate_role source_structural_type,
  'alignment:'||s.alignment_segment_id::text target_node_key,
  'alignment'::text target_node_class,
  'alignment:r'||ct.reality_member_count::text||':w'||ct.witness_member_count::text target_structural_type,
  'touch:'||d.dimension_family||':'||c.coordinate_role edge_structural_type,
  m.member_role,
  c.coordinate_group_key,
  c.dimension_key,
  d.dimension_family,
  null::text witness_key,
  null::text object_type,
  null::text object_id,
  s.alignment_kind,
  s.relation_type,
  m.alignment_member_id
from draft.reality_alignment_members m
join draft.reality_alignment_segments s using(alignment_segment_id)
join draft.reality_occurrences o using(occurrence_id)
join counts ct using(alignment_segment_id)
join draft.reality_occurrence_coordinates c
  on c.occurrence_coordinate_id=m.occurrence_coordinate_id
join draft.reality_query_dimension_registry d using(dimension_key)
where m.side='reality'

union all
select
  s.occurrence_id,
  o.occurrence_key,
  coalesce(o.metadata->>'independenceKey',o.occurrence_key),
  'member:'||m.alignment_member_id::text,
  'witness_touch',
  'alignment:'||s.alignment_segment_id::text,
  'alignment',
  'alignment:r'||ct.reality_member_count::text||':w'||ct.witness_member_count::text,
  'witness:'||m.witness_key||':'||m.object_type||':'||m.object_id,
  'witness_object',
  'witness_object',
  'touch:witness_object',
  m.member_role,
  null,
  null,
  null,
  m.witness_key,
  m.object_type,
  m.object_id,
  s.alignment_kind,
  s.relation_type,
  m.alignment_member_id
from draft.reality_alignment_members m
join draft.reality_alignment_segments s using(alignment_segment_id)
join draft.reality_occurrences o using(occurrence_id)
join counts ct using(alignment_segment_id)
where m.side='witness';

comment on view intelligence.v_reality_alignment_graph_edges_v1 is
'Label-strippable graph projection of Reality Alignment. Coordinate values, source labels, and native object names are absent from structural node/edge types; native references remain available separately for instance recovery.';

revoke all on intelligence.v_reality_alignment_graph_edges_v1 from anon,authenticated;
grant select on intelligence.v_reality_alignment_graph_edges_v1 to service_role;
