-- Atlas Canonical Person v1.
-- Migration identity generated by Supabase CLI on the candidate branch.
-- Establishes an additive Person root beneath existing credential-rooted paths.

create table atlas.people (
  id uuid primary key default gen_random_uuid(),
  stable_key text generated always as ('person:' || id::text) stored,
  display_name text,
  status text not null default 'active'
    check (status in ('active','retired')),
  metadata jsonb not null default '{}'::jsonb
    check (jsonb_typeof(metadata) = 'object'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (stable_key),
  check (display_name is null or btrim(display_name) <> '')
);

alter table atlas.people enable row level security;
revoke all on atlas.people from anon, authenticated;

create table atlas.person_auth_credentials (
  id uuid primary key default gen_random_uuid(),
  person_id uuid not null references atlas.people(id) on delete restrict,
  credential_kind text not null default 'supabase_auth_user'
    check (credential_kind = 'supabase_auth_user'),
  auth_user_id uuid not null references auth.users(id) on delete cascade,
  status text not null default 'active'
    check (status in ('active','retired')),
  bound_at timestamptz not null default now(),
  retired_at timestamptz,
  provenance jsonb not null default '{}'::jsonb
    check (jsonb_typeof(provenance) = 'object'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (auth_user_id),
  check (
    (status = 'active' and retired_at is null)
    or
    (status = 'retired' and retired_at is not null)
  )
);

create index person_auth_credentials_person_active_idx
  on atlas.person_auth_credentials (person_id)
  where status = 'active';

alter table atlas.person_auth_credentials enable row level security;
revoke all on atlas.person_auth_credentials from anon, authenticated;

alter table atlas.principals
  add column person_id uuid references atlas.people(id) on delete restrict;

create unique index principals_person_id_uq
  on atlas.principals (person_id)
  where person_id is not null;

alter table atlas.organization_memberships
  add column person_id uuid references atlas.people(id) on delete restrict;

create unique index organization_memberships_organization_person_uq
  on atlas.organization_memberships (organization_id, person_id)
  where person_id is not null;

alter table atlas.household_members
  add column person_id uuid references atlas.people(id) on delete restrict;

create index household_members_person_idx
  on atlas.household_members (person_id)
  where person_id is not null;

create or replace function atlas.ensure_person_for_auth_user_v1(
  p_user_id uuid,
  p_display_name text default null
)
returns uuid
language plpgsql
security definer
set search_path = pg_catalog, atlas, auth
as $function$
declare
  v_person_id uuid;
  v_display_name text := nullif(btrim(coalesce(p_display_name, '')), '');
begin
  if p_user_id is null then
    raise exception 'Authentication credential id required.' using errcode = '22023';
  end if;

  -- Serialize first binding for one Supabase auth identity without deriving
  -- Person identity from email or display-name uniqueness.
  perform 1
  from auth.users u
  where u.id = p_user_id
  for update;

  if not found then
    raise exception 'Authentication credential does not exist.' using errcode = '23503';
  end if;

  select c.person_id
  into v_person_id
  from atlas.person_auth_credentials c
  where c.auth_user_id = p_user_id
    and c.status = 'active'
  limit 1;

  if v_person_id is not null then
    if v_display_name is not null then
      update atlas.people p
      set display_name = coalesce(p.display_name, v_display_name),
          updated_at = case when p.display_name is null then now() else p.updated_at end
      where p.id = v_person_id;
    end if;
    return v_person_id;
  end if;

  insert into atlas.people (display_name, status, metadata)
  values (
    v_display_name,
    'active',
    jsonb_build_object('establishmentBasis','existing_auth_credential_compatibility')
  )
  returning id into v_person_id;

  insert into atlas.person_auth_credentials (
    person_id,
    credential_kind,
    auth_user_id,
    status,
    provenance
  ) values (
    v_person_id,
    'supabase_auth_user',
    p_user_id,
    'active',
    jsonb_build_object('basis','compatibility_binding')
  );

  return v_person_id;
end;
$function$;

revoke all on function atlas.ensure_person_for_auth_user_v1(uuid,text) from public, anon, authenticated;

create or replace function atlas.current_person_id_v1()
returns uuid
language sql
stable
security definer
set search_path = pg_catalog, atlas, auth
as $function$
  select c.person_id
  from atlas.person_auth_credentials c
  join atlas.people p on p.id = c.person_id
  where c.auth_user_id = auth.uid()
    and c.status = 'active'
    and p.status = 'active'
  limit 1;
$function$;

revoke all on function atlas.current_person_id_v1() from public, anon, authenticated;

-- Existing Principal rows are the highest-confidence personal human root.
update atlas.principals p
set person_id = atlas.ensure_person_for_auth_user_v1(p.user_id, p.name)
where p.user_id is not null
  and p.person_id is null;

-- Existing organization memberships are durable human/organization relations.
update atlas.organization_memberships m
set person_id = atlas.ensure_person_for_auth_user_v1(
  m.user_id,
  (select up.display_name from atlas.user_profiles up where up.user_id = m.user_id limit 1)
)
where m.user_id is not null
  and m.person_id is null;

-- Bind only household members that already carry an authenticated credential.
-- Accountless household humans remain valid and are not guessed from names.
update atlas.household_members hm
set person_id = atlas.ensure_person_for_auth_user_v1(hm.user_id, hm.display_name)
where hm.user_id is not null
  and hm.person_id is null;

create or replace function atlas.principal_person_compatibility_v1()
returns trigger
language plpgsql
security definer
set search_path = pg_catalog, atlas, auth
as $function$
declare
  v_person_id uuid;
begin
  if new.user_id is null then
    return new;
  end if;

  v_person_id := atlas.ensure_person_for_auth_user_v1(new.user_id, new.name);

  if new.person_id is null then
    new.person_id := v_person_id;
  elsif new.person_id <> v_person_id then
    raise exception 'Principal user/person identity contradiction.' using errcode = '23514';
  end if;

  return new;
end;
$function$;

revoke all on function atlas.principal_person_compatibility_v1() from public, anon, authenticated;

drop trigger if exists principal_person_compatibility_v1 on atlas.principals;
create trigger principal_person_compatibility_v1
before insert or update of user_id, person_id, name
on atlas.principals
for each row execute function atlas.principal_person_compatibility_v1();

create or replace function atlas.organization_membership_person_compatibility_v1()
returns trigger
language plpgsql
security definer
set search_path = pg_catalog, atlas, auth
as $function$
declare
  v_person_id uuid;
begin
  if new.user_id is null then
    return new;
  end if;

  v_person_id := atlas.ensure_person_for_auth_user_v1(new.user_id, null);

  if new.person_id is null then
    new.person_id := v_person_id;
  elsif new.person_id <> v_person_id then
    raise exception 'Organization membership user/person identity contradiction.' using errcode = '23514';
  end if;

  return new;
end;
$function$;

revoke all on function atlas.organization_membership_person_compatibility_v1() from public, anon, authenticated;

drop trigger if exists organization_membership_person_compatibility_v1 on atlas.organization_memberships;
create trigger organization_membership_person_compatibility_v1
before insert or update of user_id, person_id
on atlas.organization_memberships
for each row execute function atlas.organization_membership_person_compatibility_v1();

create or replace function atlas.household_member_person_compatibility_v1()
returns trigger
language plpgsql
security definer
set search_path = pg_catalog, atlas, auth
as $function$
declare
  v_person_id uuid;
begin
  if new.user_id is null then
    return new;
  end if;

  v_person_id := atlas.ensure_person_for_auth_user_v1(new.user_id, new.display_name);

  if new.person_id is null then
    new.person_id := v_person_id;
  elsif new.person_id <> v_person_id then
    raise exception 'Household member user/person identity contradiction.' using errcode = '23514';
  end if;

  return new;
end;
$function$;

revoke all on function atlas.household_member_person_compatibility_v1() from public, anon, authenticated;

drop trigger if exists household_member_person_compatibility_v1 on atlas.household_members;
create trigger household_member_person_compatibility_v1
before insert or update of user_id, person_id, display_name
on atlas.household_members
for each row execute function atlas.household_member_person_compatibility_v1();

-- Migration-time data guard: every current credential-rooted durable human row
-- must resolve to the same Person as its active credential binding.
do $proof$
begin
  if exists (
    select 1
    from atlas.principals p
    left join atlas.person_auth_credentials c
      on c.auth_user_id = p.user_id and c.status = 'active'
    where p.user_id is not null
      and (p.person_id is null or c.person_id is distinct from p.person_id)
  ) then
    raise exception 'Canonical Person migration failed for principals.';
  end if;

  if exists (
    select 1
    from atlas.organization_memberships m
    left join atlas.person_auth_credentials c
      on c.auth_user_id = m.user_id and c.status = 'active'
    where m.user_id is not null
      and (m.person_id is null or c.person_id is distinct from m.person_id)
  ) then
    raise exception 'Canonical Person migration failed for organization memberships.';
  end if;

  if exists (
    select 1
    from atlas.household_members hm
    left join atlas.person_auth_credentials c
      on c.auth_user_id = hm.user_id and c.status = 'active'
    where hm.user_id is not null
      and (hm.person_id is null or c.person_id is distinct from hm.person_id)
  ) then
    raise exception 'Canonical Person migration failed for household members.';
  end if;

  if (
    select count(*)
    from atlas.person_auth_credentials c
    where c.status = 'active'
  ) <> (
    select count(distinct user_id)
    from (
      select user_id from atlas.principals where user_id is not null
      union all
      select user_id from atlas.organization_memberships where user_id is not null
      union all
      select user_id from atlas.household_members where user_id is not null
    ) roots
  ) then
    raise exception 'Canonical Person migration failed: credential-root count mismatch.';
  end if;

  if has_table_privilege('anon', 'atlas.people', 'SELECT')
     or has_table_privilege('authenticated', 'atlas.people', 'SELECT')
     or has_table_privilege('anon', 'atlas.person_auth_credentials', 'SELECT')
     or has_table_privilege('authenticated', 'atlas.person_auth_credentials', 'SELECT') then
    raise exception 'Canonical Person migration failed: direct browser table read widened.';
  end if;
end;
$proof$;
