
create table draft.reality_witness_registry (
  witness_key text primary key,
  witness_name text not null,
  witness_kind text not null,
  native_domain text,
  source_object_type text,
  source_object_id text,
  source_role text,
  provenance_status text not null default 'registered',
  is_active boolean not null default true,
  notes text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on table draft.reality_witness_registry is
'Registry of sources, frameworks, instruments, corpora, practitioners, reports, and other witnesses that can contribute objects to one Reality Alignment space. Witness identity is preserved; registration does not merge witness ontologies.';

create unique index reality_witness_registry_source_uq
on draft.reality_witness_registry(source_object_type,source_object_id)
where source_object_type is not null and source_object_id is not null;

create table draft.reality_occurrences (
  occurrence_id bigint generated by default as identity primary key,
  occurrence_key text not null unique,
  occurrence_kind text not null,
  subject_ref_type text,
  subject_ref text,
  occurred_at timestamptz,
  captured_by_witness_key text references draft.reality_witness_registry(witness_key)
    on update cascade on delete set null,
  raw_summary text,
  raw_payload jsonb not null default '{}'::jsonb,
  occurrence_status text not null default 'captured',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on table draft.reality_occurrences is
'An occurrence is the shared reality anchor around which multiple witnesses may align. It is not owned by any medical, spiritual, mechanical, emotional, or other disciplinary ontology.';

create table draft.reality_occurrence_coordinates (
  occurrence_coordinate_id bigint generated by default as identity primary key,
  occurrence_id bigint not null references draft.reality_occurrences(occurrence_id)
    on update cascade on delete cascade,
  coordinate_group_key text not null default 'root',
  dimension_key text not null references draft.reality_query_dimension_registry(dimension_key)
    on update cascade on delete restrict,
  dimension_value text not null,
  normalized_value text not null,
  coordinate_role text not null default 'feature',
  coordinate_order integer not null default 0,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on table draft.reality_occurrence_coordinates is
'Coordinate spine for an observed occurrence. Coordinates preserve local grouping independently of any witness explanation.';

create unique index reality_occurrence_coordinates_uq
on draft.reality_occurrence_coordinates(
  occurrence_id,coordinate_group_key,dimension_key,normalized_value
);

create index reality_occurrence_coordinates_lookup_idx
on draft.reality_occurrence_coordinates(dimension_key,normalized_value,occurrence_id);

create table draft.reality_alignment_segments (
  alignment_segment_id bigint generated by default as identity primary key,
  alignment_key text not null unique,
  occurrence_id bigint not null references draft.reality_occurrences(occurrence_id)
    on update cascade on delete cascade,
  alignment_kind text not null,
  relation_type text not null,
  alignment_status text not null default 'working',
  resolution_confidence text,
  review_status text not null default 'unreviewed',
  source_basis text,
  notes text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on table draft.reality_alignment_segments is
'First-class bridge between an observed reality occurrence and one or more witness-native objects. The segment records contact/alignment without requiring object identity or ontology equivalence.';

create index reality_alignment_segments_occurrence_idx
on draft.reality_alignment_segments(occurrence_id,alignment_kind,relation_type);

create table draft.reality_alignment_members (
  alignment_member_id bigint generated by default as identity primary key,
  alignment_segment_id bigint not null references draft.reality_alignment_segments(alignment_segment_id)
    on update cascade on delete cascade,
  side text not null,
  witness_key text references draft.reality_witness_registry(witness_key)
    on update cascade on delete restrict,
  occurrence_coordinate_id bigint references draft.reality_occurrence_coordinates(occurrence_coordinate_id)
    on update cascade on delete cascade,
  object_type text,
  object_id text,
  member_role text not null,
  member_order integer not null default 0,
  resolution_status text not null default 'working',
  source_locator text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint reality_alignment_members_side_check check (side in ('reality','witness')),
  constraint reality_alignment_members_shape_check check (
    (side='reality' and occurrence_coordinate_id is not null)
    or
    (side='witness' and witness_key is not null and object_type is not null and object_id is not null)
  )
);

comment on table draft.reality_alignment_members is
'Members of a Reality Alignment segment. Reality-side members point to occurrence coordinates; witness-side members point to native source objects and retain witness identity. One-to-one, one-to-many, many-to-one, and many-to-many alignments are all representable.';

create unique index reality_alignment_members_uq
on draft.reality_alignment_members(
  alignment_segment_id,
  side,
  coalesce(witness_key,''),
  coalesce(occurrence_coordinate_id,0),
  coalesce(object_type,''),
  coalesce(object_id,''),
  member_role
);

create index reality_alignment_members_coordinate_idx
on draft.reality_alignment_members(occurrence_coordinate_id)
where occurrence_coordinate_id is not null;

create index reality_alignment_members_object_idx
on draft.reality_alignment_members(object_type,object_id)
where object_type is not null and object_id is not null;

create table draft.reality_alignment_residue_registry (
  residue_id bigint generated by default as identity primary key,
  occurrence_id bigint not null references draft.reality_occurrences(occurrence_id)
    on update cascade on delete cascade,
  occurrence_coordinate_id bigint references draft.reality_occurrence_coordinates(occurrence_coordinate_id)
    on update cascade on delete cascade,
  witness_key text references draft.reality_witness_registry(witness_key)
    on update cascade on delete set null,
  residue_class text not null,
  disposition text not null default 'hold',
  residue_status text not null default 'open',
  notes text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on table draft.reality_alignment_residue_registry is
'Explicit registry for coordinates or witness material not accounted for by current alignments. Residue is preserved as information rather than forced into an existing explanation.';

create unique index reality_alignment_residue_uq
on draft.reality_alignment_residue_registry(
  occurrence_id,
  coalesce(occurrence_coordinate_id,0),
  coalesce(witness_key,''),
  residue_class
);

alter table draft.reality_witness_registry enable row level security;
alter table draft.reality_occurrences enable row level security;
alter table draft.reality_occurrence_coordinates enable row level security;
alter table draft.reality_alignment_segments enable row level security;
alter table draft.reality_alignment_members enable row level security;
alter table draft.reality_alignment_residue_registry enable row level security;

revoke all on draft.reality_witness_registry from anon,authenticated;
revoke all on draft.reality_occurrences from anon,authenticated;
revoke all on draft.reality_occurrence_coordinates from anon,authenticated;
revoke all on draft.reality_alignment_segments from anon,authenticated;
revoke all on draft.reality_alignment_members from anon,authenticated;
revoke all on draft.reality_alignment_residue_registry from anon,authenticated;

grant select,insert,update,delete on draft.reality_witness_registry to service_role;
grant select,insert,update,delete on draft.reality_occurrences to service_role;
grant select,insert,update,delete on draft.reality_occurrence_coordinates to service_role;
grant select,insert,update,delete on draft.reality_alignment_segments to service_role;
grant select,insert,update,delete on draft.reality_alignment_members to service_role;
grant select,insert,update,delete on draft.reality_alignment_residue_registry to service_role;

create view intelligence.v_reality_alignment_segment_evidence_v1
with (security_invoker=true)
as
select
  s.alignment_segment_id,
  s.alignment_key,
  s.occurrence_id,
  o.occurrence_key,
  s.alignment_kind,
  s.relation_type,
  s.alignment_status,
  s.resolution_confidence,
  s.review_status,
  s.source_basis,
  count(m.alignment_member_id) filter(where m.side='reality')::integer as reality_member_count,
  count(m.alignment_member_id) filter(where m.side='witness')::integer as witness_member_count,
  count(distinct m.witness_key) filter(where m.side='witness')::integer as witness_count,
  jsonb_agg(
    jsonb_build_object(
      'side',m.side,
      'witnessKey',m.witness_key,
      'witnessName',w.witness_name,
      'coordinateId',m.occurrence_coordinate_id,
      'objectType',m.object_type,
      'objectId',m.object_id,
      'memberRole',m.member_role,
      'memberOrder',m.member_order,
      'resolutionStatus',m.resolution_status,
      'sourceLocator',m.source_locator,
      'metadata',m.metadata
    )
    order by case when m.side='reality' then 0 else 1 end,m.member_order,m.alignment_member_id
  ) filter(where m.alignment_member_id is not null) as members,
  s.metadata,
  s.created_at,
  s.updated_at
from draft.reality_alignment_segments s
join draft.reality_occurrences o using(occurrence_id)
left join draft.reality_alignment_members m using(alignment_segment_id)
left join draft.reality_witness_registry w on w.witness_key=m.witness_key
group by
  s.alignment_segment_id,s.alignment_key,s.occurrence_id,o.occurrence_key,
  s.alignment_kind,s.relation_type,s.alignment_status,s.resolution_confidence,
  s.review_status,s.source_basis,s.metadata,s.created_at,s.updated_at;

comment on view intelligence.v_reality_alignment_segment_evidence_v1 is
'Cross-domain analogue of alignment-segment evidence: one reality anchor, native witness objects, and the explicit member structure of the bridge between them.';

create view intelligence.v_reality_occurrence_viewport_v1
with (security_invoker=true)
as
select
  o.occurrence_id,
  o.occurrence_key,
  o.occurrence_kind,
  o.subject_ref_type,
  o.subject_ref,
  o.occurred_at,
  o.raw_summary,
  o.occurrence_status,
  coalesce((
    select jsonb_agg(
      jsonb_build_object(
        'coordinateId',c.occurrence_coordinate_id,
        'groupKey',c.coordinate_group_key,
        'dimensionKey',c.dimension_key,
        'value',c.dimension_value,
        'normalizedValue',c.normalized_value,
        'role',c.coordinate_role,
        'order',c.coordinate_order
      )
      order by c.coordinate_group_key,c.coordinate_order,c.occurrence_coordinate_id
    )
    from draft.reality_occurrence_coordinates c
    where c.occurrence_id=o.occurrence_id
  ),'[]'::jsonb) as coordinates,
  coalesce((
    select jsonb_agg(
      jsonb_build_object(
        'alignmentSegmentId',a.alignment_segment_id,
        'alignmentKey',a.alignment_key,
        'alignmentKind',a.alignment_kind,
        'relationType',a.relation_type,
        'alignmentStatus',a.alignment_status,
        'resolutionConfidence',a.resolution_confidence,
        'reviewStatus',a.review_status,
        'sourceBasis',a.source_basis,
        'realityMemberCount',a.reality_member_count,
        'witnessMemberCount',a.witness_member_count,
        'witnessCount',a.witness_count,
        'members',a.members
      )
      order by a.alignment_segment_id
    )
    from intelligence.v_reality_alignment_segment_evidence_v1 a
    where a.occurrence_id=o.occurrence_id
  ),'[]'::jsonb) as alignments,
  coalesce((
    select jsonb_agg(
      jsonb_build_object(
        'residueId',r.residue_id,
        'coordinateId',r.occurrence_coordinate_id,
        'witnessKey',r.witness_key,
        'residueClass',r.residue_class,
        'disposition',r.disposition,
        'status',r.residue_status,
        'notes',r.notes,
        'metadata',r.metadata
      )
      order by r.residue_id
    )
    from draft.reality_alignment_residue_registry r
    where r.occurrence_id=o.occurrence_id
  ),'[]'::jsonb) as residue,
  o.metadata,
  o.created_at,
  o.updated_at
from draft.reality_occurrences o;

comment on view intelligence.v_reality_occurrence_viewport_v1 is
'Unified occurrence viewport. It composes coordinates, cross-witness alignments, and unresolved residue while preserving every witness as a separate source object.';

revoke all on intelligence.v_reality_alignment_segment_evidence_v1 from anon,authenticated;
revoke all on intelligence.v_reality_occurrence_viewport_v1 from anon,authenticated;
grant select on intelligence.v_reality_alignment_segment_evidence_v1 to service_role;
grant select on intelligence.v_reality_occurrence_viewport_v1 to service_role;
