with package as (
 select id from wnph.publication_source_packages where canonical_key='virginia-house-wife:1824-functional-semantic-source:v1'
), scans(scan_sequence,printed_page,image_height,source_sha256,source_byte_length,signals) as (
 values
 (34,30,1886,'5c4a8add4e9e5fc2dcccdd1e2c52387b325d7467db72e7032786761d98b43bd2',299219,jsonb_build_array('SOUP WITH BOUILLI','thick brisket','eight pounds','every thing directed for the other soup','one hour sooner','five hours','take out the beef','keep hot','yelk of an egg','crumb of stale bread','Dutch oven')),
 (35,31,1938,'2926faa0f3e30b0691d6e96dc4ad6943c643ebb50947d8f4bcfad1a27fea763b',300251,jsonb_build_array('red wine','mushroom catsup','brown flour','green pickle','toasted bread','VEAL SOUP'))
)
insert into wnph.publication_source_observations(source_asset_id,observation_key,observation_kind,ordinal,coordinate_unit,x,y,width,height,confidence,derivation_method,source_format,processor,external_locator,metadata)
select a.id,format('virginia-house-wife:1824:soup-with-bouilli:scan:%s:machine-pixel-corroboration:v1',lpad(s.scan_sequence::text,4,'0')),
'layout_region',1,'pixel',0,0,1200,s.image_height,0.98,'bounded_machine_pixel_corroboration_v1','image/jpeg',
jsonb_build_object('provider','WNPH bounded source inspection','engine','ocrad.js 0.0.1','mode','whole_page_machine_corroboration'),
jsonb_build_object('asset_key',a.asset_key,'scan_sequence',s.scan_sequence,'printed_page',s.printed_page,'iiif_uri',format('https://tile.loc.gov/image-services/iiif/service:rbc:rbc0001:2015:2015pennell17897:%s/full/1200,/0/default.jpg',lpad(s.scan_sequence::text,4,'0'))),
jsonb_build_object('verification_role','machine_pixel_corroboration','human_visual_inspection',false,'source_image_verification_claim',false,'source_sha256',s.source_sha256,'source_byte_length',s.source_byte_length,
'comparison_source_key','textgrid:virginia-house-wife:1824','comparison_agreement',true,'agreement_scope','lexical_and_semantic_claim_support','typographic_exactness_human_adjudicated',false,'stable_signals',s.signals)
from scans s join package p on true join wnph.publication_source_assets a on a.source_package_id=p.id and a.asset_key=format('virginia-house-wife:1824:source-surface:%s',lpad(s.scan_sequence::text,4,'0'))
where not exists(select 1 from wnph.publication_source_observations o where o.source_asset_id=a.id and o.observation_key=format('virginia-house-wife:1824:soup-with-bouilli:scan:%s:machine-pixel-corroboration:v1',lpad(s.scan_sequence::text,4,'0')) and not exists(select 1 from wnph.publication_source_observations c where c.supersedes_observation_id=o.id));

do $$
declare
 v_package wnph.publication_source_packages%rowtype; v_case wnph.recovery_cases%rowtype; v_work wnph.historical_works%rowtype; v_surrogate wnph.surrogates%rowtype;
 v_loc_source wnph.evidence_sources%rowtype; v_textgrid_source wnph.evidence_sources%rowtype; v_soup_container uuid; v_gravy_unit uuid; v_block_id uuid; v_unit_id uuid; v_act_id uuid; v_locators jsonb; s record;
begin
 if exists(select 1 from wnph.transmission_acts where canonical_key='virginia-house-wife:1824:transmission:soup-with-bouilli:source-text-verification:v1') then return; end if;
 select * into strict v_package from wnph.publication_source_packages where canonical_key='virginia-house-wife:1824-functional-semantic-source:v1';
 select * into strict v_case from wnph.recovery_cases where canonical_key='virginia-house-wife:functional-semantic-cookbook-recovery-1';
 select * into strict v_work from wnph.historical_works where canonical_key='virginia-house-wife';
 select * into strict v_surrogate from wnph.surrogates where canonical_key='virginia-house-wife:loc-digital-73217897';
 select * into strict v_loc_source from wnph.evidence_sources where canonical_key='loc:item:73217897';
 select * into strict v_textgrid_source from wnph.evidence_sources where canonical_key='textgrid:virginia-house-wife:1824';
 select id into strict v_soup_container from wnph.publication_source_blocks b where b.source_package_id=v_package.id and b.block_key='virginia-house-wife:1824:sequence:soups' and not exists(select 1 from wnph.publication_source_blocks c where c.supersedes_block_id=b.id);
 select id into strict v_gravy_unit from wnph.publication_semantic_units u where u.source_package_id=v_package.id and u.unit_key='virginia-house-wife:1824:semantic:gravy-soup' and not exists(select 1 from wnph.publication_semantic_units c where c.supersedes_unit_id=u.id);
 select jsonb_agg(jsonb_build_object('asset_key',a.asset_key,'scan_sequence',m.scan_sequence,'printed_page',m.printed_page,'source_sha256',m.sha256,'source_byte_length',m.byte_length) order by m.scan_sequence) into v_locators
 from (values (34,30,'5c4a8add4e9e5fc2dcccdd1e2c52387b325d7467db72e7032786761d98b43bd2',299219),(35,31,'2926faa0f3e30b0691d6e96dc4ad6943c643ebb50947d8f4bcfad1a27fea763b',300251)) m(scan_sequence,printed_page,sha256,byte_length)
 join wnph.publication_source_assets a on a.source_package_id=v_package.id and a.asset_key=format('virginia-house-wife:1824:source-surface:%s',lpad(m.scan_sequence::text,4,'0'));
 v_block_id:=gen_random_uuid();
 insert into wnph.publication_source_blocks(id,source_package_id,block_key,parent_block_id,ordinal,block_type,semantic_role,text_content,properties,source_provenance,reading_state)
 values(v_block_id,v_package.id,'virginia-house-wife:1824:soup-with-bouilli',v_soup_container,3,'instruction','branched_soup_and_bouilli_service_protocol',
$bouilli$SOUP WITH BOUILLI.

Take the nicest part of the thick brisket of beef about eight pounds, put it into a pot with every thing directed for the other soup; make it exactly in the same way, only put it on an hour sooner that you may have time to prepare the bouilli, after it has boiled five hours take out the beef, cover up the soup and set it near the fire that it may keep hot. Take the skin off the beef, have the yelk of an egg well beaten, dip a feather in it and wash the top of your beef, sprinkle over it the crumb of stale bread finely grated, put in a Dutch oven previously heated, put the top on with coals enough to brown, but not burn the beef; let it stand nearly an hour and prepare your gravy thus:—Take a sufficient quantity of soup and the vegetables boiled in it; add to it a table-spoonful of red wine, and two of mushroom catsup, thicken with a little bit of butter and a little brown flour: make it very hot, pour it in your dish, and put the beef on it. Garnish it with green pickle, cut in thin slices, serve up the soup in a tureen with bits of toasted bread.$bouilli$,
 jsonb_build_object('printed_pages',jsonb_build_array(30,31),'historical_unit_type','branched_soup_and_bouilli_service_protocol','modern_safety_assessed',false,'modern_normalization_applied',false,'human_visual_inspection',false,
 'typographic_exactness_human_adjudicated',false,'next_heading','VEAL SOUP.','depends_on_unit_key','virginia-house-wife:1824:semantic:gravy-soup','process_branches',jsonb_build_array('hot_soup','bouilli_beef','gravy')),
 jsonb_build_object('text_authority','Library of Congress 1824 first-edition source surfaces are controlling; exact-1824 TextGrid comparison supplies the lexical reading','source_locators',v_locators,'verification_status','source_text_verified','source_verified',true,
 'controlling_witness','Library of Congress 1824 first edition','comparison_transcription_key','textgrid:virginia-house-wife:1824','comparison_transcription_is_authority',false,'machine_pixel_corroboration',true,'human_visual_inspection',false,
 'source_image_verification_claim',false,'typographic_exactness_human_adjudicated',false,'verification_scope','lexical_and_semantic_content_for_functional_semantic_recovery','derivation_method','exact_1824_comparison_transcription_corroborated_against_loc_pixels'),'verified');
 v_act_id:=gen_random_uuid();
 insert into wnph.transmission_acts(id,canonical_key,recovery_case_id,work_id,operation_type,purpose,method_note,epistemic_status,confidence,metadata)
 values(v_act_id,'virginia-house-wife:1824:transmission:soup-with-bouilli:source-text-verification:v1',v_case.id,v_work.id,'source_text_verification','Verify SOUP WITH BOUILLI against the selected 1824 Library of Congress witness for functional-semantic recovery.',
 'LOC scans 34–35 bound SOUP WITH BOUILLI through the next heading VEAL SOUP. The source inherits the preceding soup method, begins one hour earlier, and then branches the result into hot soup, browned bouilli beef, and a gravy made from soup and vegetables. Exact-1824 TextGrid supplies comparison wording. No human visual or glyph-level adjudication is claimed.',
 'system_recorded','high',jsonb_build_object('canonical_text_admission',true,'canonical_text_adjudication',false,'source_text_verified',true,'source_image_verified',false,'machine_pixel_corroboration',true,'human_visual_inspection',false,'page_image_is_controlling_witness',true,
 'comparison_transcription_key','textgrid:virginia-house-wife:1824','comparison_transcription_is_authority',false,'verification_scope','lexical_and_semantic_content_for_functional_semantic_recovery','typographic_exactness_human_adjudicated',false,
 'scan_locators',v_locators,'claim_promotion_target','verified_not_adjudicated','depends_on_unit_key','virginia-house-wife:1824:semantic:gravy-soup'));
 insert into wnph.transmission_act_objects(transmission_act_id,direction,object_role,surrogate_id,locator) values(v_act_id,'input','preferred_historical_source',v_surrogate.id,jsonb_build_object('lccn','73217897','scan_sequences',jsonb_build_array(34,35)));
 insert into wnph.transmission_act_objects(transmission_act_id,direction,object_role,publication_source_package_id,locator) values(v_act_id,'context','canonical_publication_source',v_package.id,'{}');
 insert into wnph.transmission_act_objects(transmission_act_id,direction,object_role,evidence_source_id,locator) values(v_act_id,'input','comparison_transcription',v_textgrid_source.id,jsonb_build_object('status','comparison_only','edition_year',1824));
 for s in select a.id,a.asset_key,m.scan_sequence,m.printed_page,m.sha256,m.byte_length from (values (34,30,'5c4a8add4e9e5fc2dcccdd1e2c52387b325d7467db72e7032786761d98b43bd2',299219),(35,31,'2926faa0f3e30b0691d6e96dc4ad6943c643ebb50947d8f4bcfad1a27fea763b',300251)) m(scan_sequence,printed_page,sha256,byte_length)
 join wnph.publication_source_assets a on a.source_package_id=v_package.id and a.asset_key=format('virginia-house-wife:1824:source-surface:%s',lpad(m.scan_sequence::text,4,'0')) loop
  insert into wnph.transmission_act_objects(transmission_act_id,direction,object_role,publication_source_asset_id,locator) values(v_act_id,'input','source_page_image',s.id,jsonb_build_object('asset_key',s.asset_key,'scan_sequence',s.scan_sequence,'printed_page',s.printed_page,'source_sha256',s.sha256,'source_byte_length',s.byte_length,'human_visual_inspection',false));
 end loop;
 insert into wnph.transmission_act_objects(transmission_act_id,direction,object_role,publication_source_block_id,locator) values(v_act_id,'output','verified_source_text',v_block_id,jsonb_build_object('block_key','virginia-house-wife:1824:soup-with-bouilli','reading_state','verified'));
 insert into wnph.transmission_act_evidence(transmission_act_id,source_id,support_role,confidence,note) values
 (v_act_id,v_loc_source.id,'supports','certain','LOC LCCN 73217897 scans 34–35 are the controlling 1824 source surfaces.'),(v_act_id,v_textgrid_source.id,'supports','high','Exact-1824 TextGrid agrees with the LOC pixel reading and supplies comparison wording only.');
 v_unit_id:=gen_random_uuid();
 insert into wnph.publication_semantic_units(id,expression_id,source_package_id,unit_key,parent_unit_id,ordinal,unit_type,source_title,semantic_status,confidence,derivation_method,properties,source_provenance)
 values(v_unit_id,v_package.expression_id,v_package.id,'virginia-house-wife:1824:semantic:soup-with-bouilli',v_gravy_unit,10,'branched_soup_and_bouilli_service_protocol','SOUP WITH BOUILLI.','verified',0.99,'source_text_verified_semantic_extraction_v1',
 jsonb_build_object('printed_pages',jsonb_build_array(30,31),'primary_function','derive a soup-and-bouilli service from the preceding soup process, preserving broth while finishing beef and gravy separately','historical_container','unheaded soup instruction sequence','modern_safety_assessed',false,'modern_normalization_applied',false,
 'human_visual_inspection',false,'atlas_execution_requires_downstream_normalization',true,'depends_on_unit_key','virginia-house-wife:1824:semantic:gravy-soup','process_branches',jsonb_build_array('hot_soup','bouilli_beef','gravy')),
 jsonb_build_object('source_verified',true,'source_block_id',v_block_id,'verification_status','source_text_verified','controlling_witness','LOC 1824','machine_pixel_corroboration',true,'human_visual_inspection',false,'typographic_exactness_human_adjudicated',false,'comparison_transcription_key','textgrid:virginia-house-wife:1824'));
 insert into wnph.publication_semantic_claims(semantic_unit_id,source_block_id,claim_key,ordinal,claim_kind,subject_key,predicate,object_text,quantity_value,quantity_unit,quantity_text,temporal_text,condition_text,claim_status,confidence,derivation_method,properties,source_provenance)
 select v_unit_id,v_block_id,x.claim_key,x.ordinal,x.claim_kind,x.subject_key,x.predicate,x.object_text,x.quantity_value,x.quantity_unit,x.quantity_text,x.temporal_text,x.condition_text,'verified',x.confidence,'source_text_verified_semantic_extraction_v1',x.properties,
 jsonb_build_object('source_pages',x.source_pages,'source_verified',true,'verification_status','source_text_verified','verified_source_block_id',v_block_id,'controlling_witness','LOC 1824','comparison_transcription','TextGrid exact 1824','machine_pixel_corroboration',true,'human_visual_inspection',false,'typographic_exactness_human_adjudicated',false,'modern_use_requires_downstream_safety_review',x.safety_review)
 from (values
 (1,'brisket','ingredient_quantity','beef','use_cut','nicest part of thick brisket',8::numeric,'pound','about eight pounds',null::text,null::text,0.99,jsonb_build_object(),jsonb_build_array(30),false),
 (2,'inherit-base','recipe_dependency','bouilli_soup','inherit_recipe_from','virginia-house-wife:1824:semantic:gravy-soup',null,null,null,'base soup preparation','every thing directed for the other soup; exactly same way',0.99,jsonb_build_object('dependency_type','ingredients_and_process'),jsonb_build_array(30),true),
 (3,'start-earlier','relative_timing','bouilli_soup','start_earlier_than','preceding soup schedule',1::numeric,'hour','one hour sooner','meal scheduling','to allow time to prepare bouilli',0.99,jsonb_build_object('planning_dependency',true),jsonb_build_array(30),false),
 (4,'boil-five-hours','historical_cooking_duration','beef','boil','within inherited soup process',5::numeric,'hour','five hours','before branching beef from soup',null,0.99,jsonb_build_object('modern_safety_assessed',false),jsonb_build_array(30),true),
 (5,'remove-beef','process_branch','beef','remove_from','soup after five hours',null,null,null,'after five hours',null,0.99,jsonb_build_object('branch','bouilli_beef'),jsonb_build_array(30),false),
 (6,'hold-soup-hot','historical_hot_holding','soup','hold_hot','cover and set near fire',null,null,null,'while bouilli is finished',null,0.99,jsonb_build_object('modern_safety_assessed',false,'do_not_use_as_modern_safety_rule',true,'branch','hot_soup'),jsonb_build_array(30),true),
 (7,'skin-beef','preparation','beef','remove','skin',null,null,null,'after removal from soup',null,0.99,jsonb_build_object('branch','bouilli_beef'),jsonb_build_array(30),false),
 (8,'egg-coat','coating','beef','coat_top_with','well-beaten egg yolk applied with feather',1::numeric,'egg_yolk','yelk of an egg','before bread crumbs',null,0.99,jsonb_build_object('historical_tool','feather','branch','bouilli_beef'),jsonb_build_array(30),true),
 (9,'bread-crumb-coat','coating','beef','sprinkle_with','finely grated crumb of stale bread',null,null,null,'after egg yolk',null,0.99,jsonb_build_object('branch','bouilli_beef'),jsonb_build_array(30),false),
 (10,'dutch-oven','cooking_equipment','beef','finish_in','previously heated Dutch oven',null,null,null,'after coating',null,0.99,jsonb_build_object('branch','bouilli_beef'),jsonb_build_array(30),false),
 (11,'brown-not-burn','cooking_endpoint','beef','brown','coals on top enough to brown but not burn',null,null,null,'Dutch oven finish',null,0.99,jsonb_build_object('branch','bouilli_beef'),jsonb_build_array(30),true),
 (12,'oven-duration','historical_cooking_duration','beef','stand_in_oven','nearly one hour',1::numeric,'hour_approximate','nearly an hour','after coating',null,0.99,jsonb_build_object('modern_safety_assessed',false,'branch','bouilli_beef'),jsonb_build_array(30),true),
 (13,'gravy-base','process_branch','bouilli_gravy','derive_from','sufficient soup and vegetables boiled in it',null,null,null,'while beef finishes',null,0.99,jsonb_build_object('branch','gravy'),jsonb_build_array(30),false),
 (14,'red-wine','ingredient_quantity','bouilli_gravy','contains','red wine',1::numeric,'tablespoon','one table-spoonful',null,null,0.99,jsonb_build_object('branch','gravy'),jsonb_build_array(30,31),false),
 (15,'mushroom-catsup','ingredient_quantity','bouilli_gravy','contains','mushroom catsup',2::numeric,'tablespoon','two table-spoonsful',null,null,0.99,jsonb_build_object('branch','gravy'),jsonb_build_array(31),false),
 (16,'gravy-thickener','thickening','bouilli_gravy','thicken_with','a little butter and a little brown flour',null,null,null,'after wine and catsup',null,0.99,jsonb_build_object('branch','gravy'),jsonb_build_array(31),false),
 (17,'gravy-heat','finishing','bouilli_gravy','heat','make very hot',null,null,null,'before plating',null,0.99,jsonb_build_object('branch','gravy'),jsonb_build_array(31),false),
 (18,'plate-beef-on-gravy','plating','bouilli','plate','pour gravy into dish and put beef on it',null,null,null,'at service',null,0.99,jsonb_build_object(),jsonb_build_array(31),false),
 (19,'green-pickle','garnish','bouilli','garnish_with','green pickle cut in thin slices',null,null,null,'at service',null,0.99,jsonb_build_object(),jsonb_build_array(31),false),
 (20,'serve-soup-separately','service','soup','serve_separately','in tureen with bits of toasted bread',null,null,null,'at same service as bouilli',null,0.99,jsonb_build_object('branch','hot_soup'),jsonb_build_array(31),false)
 ) x(ordinal,claim_key,claim_kind,subject_key,predicate,object_text,quantity_value,quantity_unit,quantity_text,temporal_text,condition_text,confidence,properties,source_pages,safety_review);
end $$;